// apps/desktop/src/renderer/modules/schedule/presentation/components/dialogs/CreateScheduleDialog.tsx
/**
 * CreateScheduleDialog Component
 *
 * 创建日程事件对话框
 * 功能：
 * 1. 表单输入：标题、描述、时间、地点
 * 2. 支持编辑模式
 * 3. 表单验证
 */

import { useState, useCallback, useEffect } from 'react';
import type { ScheduleClientDTO, CreateScheduleRequest, UpdateScheduleRequest } from '@dailyuse/contracts/schedule';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-shadcn';
import { Button } from '@dailyuse/ui-shadcn';
import { Input } from '@dailyuse/ui-shadcn';
import { Textarea } from '@dailyuse/ui-shadcn';
import { Label } from '@dailyuse/ui-shadcn';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@dailyuse/ui-shadcn';
import { Calendar, Clock, MapPin, Users, X } from 'lucide-react';

// ===================== 接口定义 =====================

interface CreateScheduleDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  editingSchedule?: ScheduleClientDTO | null;
  isLoading?: boolean;
  onSubmit?: (data: CreateScheduleRequest | UpdateScheduleRequest) => void;
  onCancel?: () => void;
}

interface FormData {
  title: string;
  description: string;
  startDate: string;
  startTime: string;
  endDate: string;
  endTime: string;
  priority: number | null;
  location: string;
  attendees: string[];
}

// ===================== 初始值 =====================

const initialFormData: FormData = {
  title: '',
  description: '',
  startDate: '',
  startTime: '',
  endDate: '',
  endTime: '',
  priority: null,
  location: '',
  attendees: [],
};

const priorityOptions = [
  { label: '最低 (1)', value: '1' },
  { label: '低 (2)', value: '2' },
  { label: '中 (3)', value: '3' },
  { label: '高 (4)', value: '4' },
  { label: '最高 (5)', value: '5' },
];

// ===================== 组件 =====================

export function CreateScheduleDialog({
  open,
  onOpenChange,
  editingSchedule,
  isLoading = false,
  onSubmit,
  onCancel,
}: CreateScheduleDialogProps) {
  const [formData, setFormData] = useState<FormData>(initialFormData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const isEditing = !!editingSchedule;

  // 编辑模式时填充表单
  useEffect(() => {
    if (editingSchedule) {
      const startDate = new Date(editingSchedule.startTime);
      const endDate = new Date(editingSchedule.endTime);

      setFormData({
        title: editingSchedule.title,
        description: editingSchedule.description || '',
        startDate: startDate.toISOString().split('T')[0],
        startTime: startDate.toTimeString().slice(0, 5),
        endDate: endDate.toISOString().split('T')[0],
        endTime: endDate.toTimeString().slice(0, 5),
        priority: editingSchedule.priority || null,
        location: editingSchedule.location || '',
        attendees: [...(editingSchedule.attendees || [])],
      });
    } else {
      setFormData(initialFormData);
    }
    setErrors({});
  }, [editingSchedule, open]);

  // 更新表单字段
  const updateField = useCallback((field: keyof FormData, value: string | number | null | string[]) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => ({ ...prev, [field]: '' }));
  }, []);

  // 表单验证
  const validate = useCallback((): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.title.trim()) {
      newErrors.title = '请输入标题';
    } else if (formData.title.length > 200) {
      newErrors.title = '标题最多200个字符';
    }

    if (!formData.startDate) {
      newErrors.startDate = '请选择开始日期';
    }

    if (!formData.startTime) {
      newErrors.startTime = '请选择开始时间';
    }

    if (!formData.endDate) {
      newErrors.endDate = '请选择结束日期';
    }

    if (!formData.endTime) {
      newErrors.endTime = '请选择结束时间';
    }

    // 检查结束时间是否晚于开始时间
    if (formData.startDate && formData.startTime && formData.endDate && formData.endTime) {
      const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
      const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();
      if (endTimestamp <= startTimestamp) {
        newErrors.endTime = '结束时间必须晚于开始时间';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [formData]);

  // 提交表单
  const handleSubmit = useCallback(() => {
    if (!validate()) return;

    const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
    const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();

    const data = {
      title: formData.title.trim(),
      description: formData.description.trim() || undefined,
      startTime: startTimestamp,
      endTime: endTimestamp,
      priority: formData.priority || undefined,
      location: formData.location.trim() || undefined,
      attendees: formData.attendees.length > 0 ? formData.attendees : undefined,
    };

    onSubmit?.(data);
  }, [formData, validate, onSubmit]);

  // 取消
  const handleCancel = useCallback(() => {
    setFormData(initialFormData);
    setErrors({});
    onCancel?.();
    onOpenChange(false);
  }, [onCancel, onOpenChange]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-full bg-primary/10">
              <Calendar className="h-5 w-5 text-primary" />
            </div>
            <DialogTitle>{isEditing ? '编辑日程事件' : '创建日程事件'}</DialogTitle>
          </div>
          <DialogDescription>
            {isEditing ? '修改日程事件信息' : '填写日程事件信息并创建'}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* 标题 */}
          <div className="space-y-2">
            <Label htmlFor="title">标题 *</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => updateField('title', e.target.value)}
              placeholder="输入日程标题"
              maxLength={200}
              className={errors.title ? 'border-destructive' : ''}
            />
            {errors.title && <p className="text-xs text-destructive">{errors.title}</p>}
          </div>

          {/* 描述 */}
          <div className="space-y-2">
            <Label htmlFor="description">描述</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => updateField('description', e.target.value)}
              placeholder="输入日程描述"
              rows={3}
              maxLength={1000}
            />
          </div>

          {/* 时间选择 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="startDate">开始日期 *</Label>
              <Input
                id="startDate"
                type="date"
                value={formData.startDate}
                onChange={(e) => updateField('startDate', e.target.value)}
                className={errors.startDate ? 'border-destructive' : ''}
              />
              {errors.startDate && <p className="text-xs text-destructive">{errors.startDate}</p>}
            </div>
            <div className="space-y-2">
              <Label htmlFor="startTime">开始时间 *</Label>
              <Input
                id="startTime"
                type="time"
                value={formData.startTime}
                onChange={(e) => updateField('startTime', e.target.value)}
                className={errors.startTime ? 'border-destructive' : ''}
              />
              {errors.startTime && <p className="text-xs text-destructive">{errors.startTime}</p>}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="endDate">结束日期 *</Label>
              <Input
                id="endDate"
                type="date"
                value={formData.endDate}
                onChange={(e) => updateField('endDate', e.target.value)}
                className={errors.endDate ? 'border-destructive' : ''}
              />
              {errors.endDate && <p className="text-xs text-destructive">{errors.endDate}</p>}
            </div>
            <div className="space-y-2">
              <Label htmlFor="endTime">结束时间 *</Label>
              <Input
                id="endTime"
                type="time"
                value={formData.endTime}
                onChange={(e) => updateField('endTime', e.target.value)}
                className={errors.endTime ? 'border-destructive' : ''}
              />
              {errors.endTime && <p className="text-xs text-destructive">{errors.endTime}</p>}
            </div>
          </div>

          {/* 优先级 */}
          <div className="space-y-2">
            <Label>优先级</Label>
            <Select
              value={formData.priority?.toString() || ''}
              onValueChange={(value) => updateField('priority', value ? parseInt(value) : null)}
            >
              <SelectTrigger>
                <SelectValue placeholder="选择优先级" />
              </SelectTrigger>
              <SelectContent>
                {priorityOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* 地点 */}
          <div className="space-y-2">
            <Label htmlFor="location" className="flex items-center gap-1">
              <MapPin className="h-4 w-4" />
              地点
            </Label>
            <Input
              id="location"
              value={formData.location}
              onChange={(e) => updateField('location', e.target.value)}
              placeholder="输入地点"
              maxLength={200}
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleCancel} disabled={isLoading}>
            取消
          </Button>
          <Button onClick={handleSubmit} disabled={isLoading}>
            {isLoading ? '处理中...' : isEditing ? '保存' : '创建'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default CreateScheduleDialog;

// apps/web/src/modules/schedule/presentation/components/CreateScheduleDialog.vue
<template>
  <v-dialog :model-value="visible" max-width="600" persistent @update:model-value="visible = $event">
    <v-card>
      <v-card-title class="d-flex justify-space-between align-center">
        <span>{{ isEditing ? '编辑日程事件' : '创建日程事件' }}</span>
        <v-btn icon="mdi-close" variant="text" @click="handleClose" />
      </v-card-title>

      <v-card-text>
        <v-form ref="formRef" @submit.prevent="handleSubmit">
          <v-text-field
            v-model="formData.title"
            label="标题 *"
            :rules="[rules.required, rules.maxLength(200)]"
            counter="200"
            variant="outlined"
            class="mb-2"
          />

          <v-textarea
            v-model="formData.description"
            label="描述"
            :rules="[rules.maxLength(1000)]"
            counter="1000"
            variant="outlined"
            rows="3"
            class="mb-2"
          />

          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="formData.startDate"
                label="开始日期 *"
                type="date"
                :rules="[rules.required]"
                variant="outlined"
                class="mb-2"
              />
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="formData.startTime"
                label="开始时间 *"
                type="time"
                :rules="[rules.required]"
                variant="outlined"
                class="mb-2"
              />
            </v-col>
          </v-row>

          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="formData.endDate"
                label="结束日期 *"
                type="date"
                :rules="[rules.required]"
                variant="outlined"
                class="mb-2"
              />
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="formData.endTime"
                label="结束时间 *"
                type="time"
                :rules="[rules.required]"
                variant="outlined"
                class="mb-2"
              />
            </v-col>
          </v-row>

          <v-select
            v-model="formData.priority"
            label="优先级"
            :items="priorityOptions"
            variant="outlined"
            clearable
            class="mb-2"
          />

          <v-text-field
            v-model="formData.location"
            label="地点"
            :rules="[rules.maxLength(200)]"
            counter="200"
            variant="outlined"
            prepend-inner-icon="mdi-map-marker"
            class="mb-2"
          />

          <v-combobox
            v-model="formData.attendees"
            label="参与者"
            multiple
            chips
            clearable
            variant="outlined"
            prepend-inner-icon="mdi-account-multiple"
            hint="输入邮箱或用户名后按回车添加"
            class="mb-2"
          />
        </v-form>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="handleClose">取消</v-btn>
        <v-btn color="primary" :loading="isLoading" @click="handleSubmit">
          {{ isEditing ? '保存' : '创建' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch, computed } from 'vue';
import { useScheduleEvent } from '../composables/useScheduleEvent';
import type { ScheduleClientDTO, ScheduleTaskClientDTO, ConflictDetectionResult, CreateScheduleRequest, UpdateScheduleRequest } from '@dailyuse/contracts/schedule';

// ===== Composables =====
const { createSchedule, updateSchedule, isLoading } = useScheduleEvent();

// ===== State =====
const visible = ref(false);
const editingSchedule = ref<ScheduleClientDTO | null>(null);

const isEditing = computed(() => !!editingSchedule.value);

// ===== State =====
const formRef = ref();
const formData = reactive({
  title: '',
  description: '',
  startDate: '',
  startTime: '',
  endDate: '',
  endTime: '',
  priority: null as number | null,
  location: '',
  attendees: [] as string[],
});

const priorityOptions = [
  { title: '最低 (1)', value: 1 },
  { title: '低 (2)', value: 2 },
  { title: '中 (3)', value: 3 },
  { title: '高 (4)', value: 4 },
  { title: '最高 (5)', value: 5 },
];

// ===== Validation Rules =====
const rules = {
  required: (value: string) => !!value || '此字段为必填项',
  maxLength: (max: number) => (value: string) =>
    !value || value.length <= max || `最多${max}个字符`,
};

// ===== Methods =====

/**
 * 重置表单
 */
function resetForm() {
  formData.title = '';
  formData.description = '';
  formData.startDate = '';
  formData.startTime = '';
  formData.endDate = '';
  formData.endTime = '';
  formData.priority = null;
  formData.location = '';
  formData.attendees = [];
  formRef.value?.reset();
}

/**
 * 关闭对话框
 */
function handleClose() {
  visible.value = false;
  resetForm();
}

/**
 * 提交表单
 */
async function handleSubmit() {
  const { valid } = await formRef.value.validate();
  if (!valid) return;

  // 转换日期时间为时间戳
  const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
  const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();

  // 验证时间范围
  if (startTimestamp >= endTimestamp) {
    alert('结束时间必须晚于开始时间');
    return;
  }

  if (!isEditing.value && startTimestamp < Date.now()) {
    alert('开始时间不能早于当前时间');
    return;
  }

  if (isEditing.value && editingSchedule.value) {
    // 编辑模式
    const updateData: UpdateScheduleRequest = {
      title: formData.title,
      description: formData.description || undefined,
      startTime: startTimestamp,
      endTime: endTimestamp,
      priority: formData.priority || undefined,
      location: formData.location || undefined,
      attendees: formData.attendees.length > 0 ? formData.attendees : undefined,
    };

    const result = await updateSchedule(editingSchedule.value.uuid, updateData);
    if (result) {
      handleClose();
    }
  } else {
    // 创建模式
    const requestData: CreateScheduleRequest = {
      title: formData.title,
      description: formData.description || undefined,
      startTime: startTimestamp,
      endTime: endTimestamp,
      priority: formData.priority || undefined,
      location: formData.location || undefined,
      attendees: formData.attendees.length > 0 ? formData.attendees : undefined,
    };

    const result = await createSchedule(requestData);
    if (result) {
      handleClose();
    }
  }
}

// ===== Public Methods =====

/**
 * 打开创建对话框
 */
function openForCreate() {
  editingSchedule.value = null;
  resetForm();
  
  // 设置默认值
  const now = new Date();
  const oneHourLater = new Date(now.getTime() + 60 * 60 * 1000);

  formData.startDate = now.toISOString().split('T')[0];
  formData.startTime = now.toTimeString().slice(0, 5);
  formData.endDate = oneHourLater.toISOString().split('T')[0];
  formData.endTime = oneHourLater.toTimeString().slice(0, 5);
  
  visible.value = true;
}

/**
 * 打开编辑对话框
 */
function openForEdit(schedule: ScheduleClientDTO) {
  if (!schedule) {
    console.error('[CreateScheduleDialog] openForEdit: schedule is required');
    return;
  }
  
  editingSchedule.value = schedule;
  
  // 填充表单数据
  formData.title = schedule.title;
  formData.description = schedule.description || '';
  formData.priority = schedule.priority || null;
  formData.location = schedule.location || '';
  formData.attendees = schedule.attendees ? [...schedule.attendees] : [];
  
  // 转换时间戳为日期时间
  const startDate = new Date(schedule.startTime);
  const endDate = new Date(schedule.endTime);
  
  formData.startDate = startDate.toISOString().split('T')[0];
  formData.startTime = startDate.toTimeString().slice(0, 5);
  formData.endDate = endDate.toISOString().split('T')[0];
  formData.endTime = endDate.toTimeString().slice(0, 5);
  
  visible.value = true;
}

/**
 * 通用打开方法（向后兼容）
 */
function openDialog(schedule?: ScheduleClientDTO) {
  if (schedule) {
    openForEdit(schedule);
  } else {
    openForCreate();
  }
}

// ===== Watchers =====
watch(visible, (newValue) => {
  if (!newValue) {
    // 对话框关闭时重置
    editingSchedule.value = null;
    resetForm();
  }
});

// ===== Expose Public API =====
defineExpose({
  openForCreate,
  openForEdit,
  openDialog,
});
</script>

<style scoped>
.v-card-title {
  background-color: rgba(var(--v-theme-primary), 0.1);
}
</style>
