// apps/web/src/modules/schedule/presentation/components/ScheduleTaskDetailDialog.vue
<template>
  <v-dialog :model-value="show" @update:model-value="$emit('update:show', $event)" max-width="900">
    <v-card>
      <!-- 对话框头部 -->
      <v-card-title class="d-flex align-center justify-space-between pa-4 bg-primary">
        <div class="d-flex align-center">
          <v-icon size="32" class="mr-3">mdi-calendar-clock</v-icon>
          <div class="text-white">
            <h2 class="text-h5 font-weight-bold">任务详情</h2>
            <p class="text-caption mb-0 opacity-80">Schedule Task Details</p>
          </div>
        </div>
        <v-btn icon="mdi-close" variant="text" color="white" @click="$emit('update:show', false)" />
      </v-card-title>

      <v-divider />

      <!-- 加载状态 -->
      <div v-if="isLoading" class="d-flex justify-center align-center py-12">
        <v-progress-circular indeterminate color="primary" size="64" />
      </div>

      <!-- 错误状态 -->
      <v-card-text v-else-if="error" class="pa-6">
        <v-alert type="error" variant="tonal">
          {{ error }}
        </v-alert>
      </v-card-text>

      <!-- 任务详情 -->
      <v-card-text v-else-if="task" class="pa-6">
        <v-row>
          <!-- 左侧：基本信息 -->
          <v-col cols="12" md="6">
            <v-card variant="tonal">
              <v-card-title class="text-h6 font-weight-bold pa-4">
                <v-icon start>mdi-information-outline</v-icon>
                基本信息
              </v-card-title>
              <v-divider />
              <v-card-text class="pa-4">
                <v-list density="compact">
                  <v-list-item>
                    <v-list-item-title class="text-caption text-medium-emphasis">任务名称</v-list-item-title>
                    <v-list-item-subtitle class="text-body-2 font-weight-medium">
                      {{ task.name }}
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item v-if="task.description">
                    <v-list-item-title class="text-caption text-medium-emphasis">描述</v-list-item-title>
                    <v-list-item-subtitle class="text-body-2">
                      {{ task.description }}
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item>
                    <v-list-item-title class="text-caption text-medium-emphasis">来源模块</v-list-item-title>
                    <v-list-item-subtitle>
                      <v-chip :color="getSourceModuleColor(task.sourceModule)" size="small" variant="flat">
                        {{ getSourceModuleText(task.sourceModule) }}
                      </v-chip>
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item>
                    <v-list-item-title class="text-caption text-medium-emphasis">任务状态</v-list-item-title>
                    <v-list-item-subtitle>
                      <v-chip :color="getTaskStatusColor(task.status)" size="small" variant="flat">
                        <v-icon start size="16">{{ getTaskStatusIcon(task.status) }}</v-icon>
                        {{ getTaskStatusText(task.status) }}
                      </v-chip>
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item>
                    <v-list-item-title class="text-caption text-medium-emphasis">启用状态</v-list-item-title>
                    <v-list-item-subtitle>
                      <v-chip :color="task.enabled ? 'success' : 'error'" size="small" variant="flat">
                        <v-icon start size="16">{{ task.enabled ? 'mdi-check' : 'mdi-close' }}</v-icon>
                        {{ task.enabled ? '已启用' : '已禁用' }}
                      </v-chip>
                    </v-list-item-subtitle>
                  </v-list-item>
                </v-list>
              </v-card-text>
            </v-card>
          </v-col>

          <!-- 右侧：执行信息 -->
          <v-col cols="12" md="6">
            <v-card variant="tonal" color="info">
              <v-card-title class="text-h6 font-weight-bold pa-4">
                <v-icon start>mdi-clock-outline</v-icon>
                执行信息
              </v-card-title>
              <v-divider />
              <v-card-text class="pa-4">
                <v-list density="compact">
                  <v-list-item>
                    <v-list-item-title class="text-caption text-medium-emphasis">执行次数</v-list-item-title>
                    <v-list-item-subtitle class="text-body-2 font-weight-medium">
                      {{ task.execution.executionCount }} 次
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item v-if="task.execution.nextRunAt">
                    <v-list-item-title class="text-caption text-medium-emphasis">下次执行</v-list-item-title>
                    <v-list-item-subtitle class="text-body-2">
                      {{ formatDateTime(task.execution.nextRunAt) }}
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item v-if="task.execution.lastRunAt">
                    <v-list-item-title class="text-caption text-medium-emphasis">上次执行</v-list-item-title>
                    <v-list-item-subtitle class="text-body-2">
                      {{ formatDateTime(task.execution.lastRunAt) }}
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item v-if="task.execution.lastExecutionStatus">
                    <v-list-item-title class="text-caption text-medium-emphasis">上次执行状态</v-list-item-title>
                    <v-list-item-subtitle>
                      <v-chip :color="getExecutionStatusColor(task.execution.lastExecutionStatus)" size="small">
                        {{ getExecutionStatusText(task.execution.lastExecutionStatus) }}
                      </v-chip>
                    </v-list-item-subtitle>
                  </v-list-item>

                  <v-list-item v-if="task.execution.consecutiveFailures > 0">
                    <v-list-item-title class="text-caption text-medium-emphasis">连续失败</v-list-item-title>
                    <v-list-item-subtitle>
                      <v-chip color="error" size="small">
                        {{ task.execution.consecutiveFailures }} 次
                      </v-chip>
                    </v-list-item-subtitle>
                  </v-list-item>
                </v-list>
              </v-card-text>
            </v-card>
          </v-col>
        </v-row>

        <!-- 调度配置 -->
        <v-card class="mt-4" variant="outlined">
          <v-card-title class="text-h6 font-weight-bold pa-4">
            <v-icon start>mdi-cog-outline</v-icon>
            调度配置
          </v-card-title>
          <v-divider />
          <v-card-text class="pa-4">
            <v-row>
              <v-col cols="6" md="3">
                <div class="text-caption text-medium-emphasis mb-1">Cron 表达式</div>
                <div class="text-body-2 font-weight-medium">{{ task.schedule.cronExpression }}</div>
              </v-col>
              <v-col cols="6" md="3">
                <div class="text-caption text-medium-emphasis mb-1">时区</div>
                <div class="text-body-2">{{ task.schedule.timezone }}</div>
              </v-col>
              <v-col cols="6" md="3" v-if="task.schedule.startDate">
                <div class="text-caption text-medium-emphasis mb-1">开始日期</div>
                <div class="text-body-2">{{ formatDate(task.schedule.startDate) }}</div>
              </v-col>
              <v-col cols="6" md="3" v-if="task.schedule.endDate">
                <div class="text-caption text-medium-emphasis mb-1">结束日期</div>
                <div class="text-body-2">{{ formatDate(task.schedule.endDate) }}</div>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>

        <!-- 执行历史记录 -->
        <v-card class="mt-4" variant="outlined">
          <v-card-title class="d-flex align-center justify-space-between pa-4">
            <div>
              <v-icon start>mdi-history</v-icon>
              <span class="text-h6 font-weight-bold">执行历史</span>
            </div>
            <v-btn
              color="primary"
              variant="tonal"
              size="small"
              prepend-icon="mdi-refresh"
              @click="handleRefreshExecutions"
              :loading="isLoadingHistory"
            >
              刷新
            </v-btn>
          </v-card-title>
          <v-divider />
          <v-card-text class="pa-0">
            <!-- 加载中 -->
            <div v-if="isLoadingHistory" class="d-flex justify-center align-center py-8">
              <v-progress-circular indeterminate color="primary" size="48" />
            </div>

            <!-- 执行记录列表 -->
            <v-list v-else-if="executions.length > 0" density="compact">
              <v-list-item
                v-for="(execution, index) in executions"
                :key="execution.uuid"
                :class="{ 'bg-grey-lighten-5': index % 2 === 0 }"
              >
                <template v-slot:prepend>
                  <v-icon :color="getExecutionStatusColor(execution.status)" size="20">
                    {{ getExecutionStatusIcon(execution.status) }}
                  </v-icon>
                </template>

                <v-list-item-title class="text-body-2">
                  {{ formatDateTime(execution.executionTime) }}
                </v-list-item-title>

                <v-list-item-subtitle class="text-caption">
                  <span v-if="execution.duration">耗时: {{ execution.duration }}ms</span>
                  <span v-if="execution.error" class="text-error ml-2">
                    {{ execution.error }}
                  </span>
                </v-list-item-subtitle>

                <template v-slot:append>
                  <v-chip :color="getExecutionStatusColor(execution.status)" size="x-small" variant="flat">
                    {{ getExecutionStatusText(execution.status) }}
                  </v-chip>
                </template>
              </v-list-item>
            </v-list>

            <!-- 空状态 -->
            <div v-else class="text-center py-8 text-medium-emphasis">
              <v-icon size="64" color="grey-lighten-1">mdi-calendar-remove</v-icon>
              <p class="text-body-2 mt-2 mb-0">暂无执行记录</p>
            </div>
          </v-card-text>
        </v-card>
      </v-card-text>

      <v-divider />

      <!-- 对话框底部 -->
      <v-card-actions class="pa-4">
        <v-spacer />
        <v-btn variant="text" @click="$emit('update:show', false)">关闭</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { watch } from 'vue';
import { useScheduleTaskDetail } from '../composables/useScheduleTaskDetail';

interface Props {
  show: boolean;
  taskUuid: string | null;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  'update:show': [value: boolean];
}>();

// 使用 composable
const {
  task,
  isLoading,
  error,
  executions,
  isLoadingExecutions: isLoadingHistory,
  loadTaskDetail,
  loadExecutions,
  refreshExecutions,
  clearState,
} = useScheduleTaskDetail();

// 监听 taskUuid 变化，自动加载数据
watch(() => [props.show, props.taskUuid], async ([show, uuid]) => {
  if (show && uuid && typeof uuid === 'string') {
    await loadTaskDetail(uuid);
    await loadExecutions(uuid);
  } else if (!show) {
    // 对话框关闭时清空状态
    clearState();
  }
}, { immediate: true });

/**
 * 刷新执行历史
 */
async function handleRefreshExecutions() {
  if (props.taskUuid) {
    await refreshExecutions(props.taskUuid);
  }
}

function formatDateTime(timestamp: number | string | null | undefined): string {
  if (!timestamp) return 'N/A';
  const time = typeof timestamp === 'string' ? new Date(timestamp).getTime() : timestamp;
  return new Date(time).toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

function formatDate(timestamp: number | string | null | undefined): string {
  if (!timestamp) return 'N/A';
  const time = typeof timestamp === 'string' ? new Date(timestamp).getTime() : timestamp;
  return new Date(time).toLocaleDateString('zh-CN');
}

function getSourceModuleColor(module: string): string {
  const colors: Record<string, string> = {
    reminder: 'primary',
    task: 'success',
    goal: 'warning',
  };
  return colors[module] || 'grey';
}

function getSourceModuleText(module: string): string {
  const texts: Record<string, string> = {
    reminder: '提醒模块',
    task: '任务模块',
    goal: '目标模块',
  };
  return texts[module] || module;
}

function getTaskStatusColor(status: string): string {
  const colors: Record<string, string> = {
    active: 'success',
    paused: 'warning',
    completed: 'info',
    cancelled: 'error',
  };
  return colors[status] || 'grey';
}

function getTaskStatusIcon(status: string): string {
  const icons: Record<string, string> = {
    active: 'mdi-play-circle',
    paused: 'mdi-pause-circle',
    completed: 'mdi-check-circle',
    cancelled: 'mdi-close-circle',
  };
  return icons[status] || 'mdi-help-circle';
}

function getTaskStatusText(status: string): string {
  const texts: Record<string, string> = {
    active: '运行中',
    paused: '已暂停',
    completed: '已完成',
    cancelled: '已取消',
  };
  return texts[status] || status;
}

function getExecutionStatusColor(status: string): string {
  const colors: Record<string, string> = {
    pending: 'grey',
    running: 'info',
    success: 'success',
    failed: 'error',
    timeout: 'warning',
    skipped: 'grey-lighten-1',
  };
  return colors[status] || 'grey';
}

function getExecutionStatusIcon(status: string): string {
  const icons: Record<string, string> = {
    pending: 'mdi-clock-outline',
    running: 'mdi-loading',
    success: 'mdi-check-circle',
    failed: 'mdi-alert-circle',
    timeout: 'mdi-timer-alert',
    skipped: 'mdi-skip-next',
  };
  return icons[status] || 'mdi-help-circle';
}

function getExecutionStatusText(status: string): string {
  const texts: Record<string, string> = {
    pending: '待执行',
    running: '执行中',
    success: '成功',
    failed: '失败',
    timeout: '超时',
    skipped: '跳过',
  };
  return texts[status] || status;
}
</script>

<style scoped>
.bg-primary {
  background-color: rgb(var(--v-theme-primary));
}
</style>

// apps/desktop/src/renderer/modules/schedule/presentation/components/dialogs/ScheduleTaskDetailDialog.tsx
/**
 * ScheduleTaskDetailDialog Component
 *
 * 调度任务详情对话框
 * 功能：
 * 1. 显示任务基本信息
 * 2. 显示执行信息
 * 3. 显示调度配置
 * 4. 显示执行历史
 */

import { useState, useCallback, useMemo } from 'react';
import type { ScheduleTaskClientDTO } from '@dailyuse/contracts/schedule';
import { ScheduleTaskStatus, SourceModule, ExecutionStatus } from '@dailyuse/contracts/schedule';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-shadcn';
import { Button } from '@dailyuse/ui-shadcn';
import { Badge } from '@dailyuse/ui-shadcn';
import { Card, CardContent, CardHeader, CardTitle } from '@dailyuse/ui-shadcn';
import { ScrollArea } from '@dailyuse/ui-shadcn';
import { Separator } from '@dailyuse/ui-shadcn';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@dailyuse/ui-shadcn';
import {
  CalendarClock,
  Clock,
  Info,
  Settings,
  History,
  Check,
  X,
  AlertTriangle,
  Play,
  Pause,
  Target,
  Bell,
  CheckSquare,
} from 'lucide-react';

// ===================== 接口定义 =====================

interface ScheduleTaskDetailDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  task: ScheduleTaskClientDTO | null;
  isLoading?: boolean;
  onPause?: (uuid: string) => void;
  onResume?: (uuid: string) => void;
  onDelete?: (uuid: string) => void;
}

// ===================== 工具函数 =====================

function formatDateTime(date: Date | number | null | undefined): string {
  if (!date) return '-';
  const d = typeof date === 'number' ? new Date(date) : date;
  return d.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatDate(date: Date | number | null | undefined): string {
  if (!date) return '-';
  const d = typeof date === 'number' ? new Date(date) : date;
  return d.toLocaleDateString('zh-CN');
}

const statusConfig: Record<string, { label: string; color: string; icon: typeof Check }> = {
  [ScheduleTaskStatus.ACTIVE]: { label: '活跃', color: 'bg-green-100 text-green-800', icon: Play },
  [ScheduleTaskStatus.PAUSED]: { label: '暂停', color: 'bg-yellow-100 text-yellow-800', icon: Pause },
  [ScheduleTaskStatus.COMPLETED]: { label: '已完成', color: 'bg-blue-100 text-blue-800', icon: Check },
  [ScheduleTaskStatus.CANCELLED]: { label: '已取消', color: 'bg-gray-100 text-gray-800', icon: X },
  [ScheduleTaskStatus.FAILED]: { label: '失败', color: 'bg-red-100 text-red-800', icon: AlertTriangle },
};

const sourceModuleConfig: Record<string, { label: string; color: string; icon: typeof Target }> = {
  [SourceModule.GOAL]: { label: '目标', color: 'bg-purple-100 text-purple-800', icon: Target },
  [SourceModule.REMINDER]: { label: '提醒', color: 'bg-orange-100 text-orange-800', icon: Bell },
  [SourceModule.TASK]: { label: '任务', color: 'bg-blue-100 text-blue-800', icon: CheckSquare },
};

const executionStatusConfig: Record<string, { label: string; color: string }> = {
  [ExecutionStatus.SUCCESS]: { label: '成功', color: 'bg-green-100 text-green-800' },
  [ExecutionStatus.FAILED]: { label: '失败', color: 'bg-red-100 text-red-800' },
  [ExecutionStatus.SKIPPED]: { label: '跳过', color: 'bg-gray-100 text-gray-800' },
};

// ===================== 组件 =====================

export function ScheduleTaskDetailDialog({
  open,
  onOpenChange,
  task,
  isLoading = false,
  onPause,
  onResume,
  onDelete,
}: ScheduleTaskDetailDialogProps) {
  const [activeTab, setActiveTab] = useState('info');

  const status = task ? statusConfig[task.status] : null;
  const sourceModule = task ? sourceModuleConfig[task.sourceModule] : null;
  const executionStatus = task?.execution.lastExecutionStatus
    ? executionStatusConfig[task.execution.lastExecutionStatus]
    : null;

  const handlePause = useCallback(() => {
    if (task) onPause?.(task.uuid);
  }, [task, onPause]);

  const handleResume = useCallback(() => {
    if (task) onResume?.(task.uuid);
  }, [task, onResume]);

  const handleDelete = useCallback(() => {
    if (task) onDelete?.(task.uuid);
  }, [task, onDelete]);

  if (!task) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[800px] max-h-[85vh]">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-full bg-primary/10">
              <CalendarClock className="h-5 w-5 text-primary" />
            </div>
            <div>
              <DialogTitle>任务详情</DialogTitle>
              <DialogDescription>Schedule Task Details</DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh]">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="info" className="gap-1">
                <Info className="h-4 w-4" />
                基本信息
              </TabsTrigger>
              <TabsTrigger value="schedule" className="gap-1">
                <Settings className="h-4 w-4" />
                调度配置
              </TabsTrigger>
              <TabsTrigger value="history" className="gap-1">
                <History className="h-4 w-4" />
                执行历史
              </TabsTrigger>
            </TabsList>

            {/* 基本信息 */}
            <TabsContent value="info" className="space-y-4 mt-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* 基本信息卡片 */}
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm flex items-center gap-1">
                      <Info className="h-4 w-4" />
                      基本信息
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <p className="text-xs text-muted-foreground">任务名称</p>
                      <p className="font-medium">{task.name}</p>
                    </div>
                    {task.description && (
                      <div>
                        <p className="text-xs text-muted-foreground">描述</p>
                        <p className="text-sm">{task.description}</p>
                      </div>
                    )}
                    <div>
                      <p className="text-xs text-muted-foreground">来源模块</p>
                      {sourceModule && (
                        <Badge className={sourceModule.color}>
                          {sourceModule.label}
                        </Badge>
                      )}
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">任务状态</p>
                      {status && (
                        <Badge className={status.color}>
                          <status.icon className="h-3 w-3 mr-1" />
                          {status.label}
                        </Badge>
                      )}
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">启用状态</p>
                      <Badge className={task.enabled ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}>
                        {task.enabled ? '已启用' : '已禁用'}
                      </Badge>
                    </div>
                  </CardContent>
                </Card>

                {/* 执行信息卡片 */}
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-sm flex items-center gap-1">
                      <Clock className="h-4 w-4" />
                      执行信息
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <p className="text-xs text-muted-foreground">执行次数</p>
                      <p className="font-medium">{task.execution.executionCount} 次</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">下次执行</p>
                      <p className="text-sm">{formatDateTime(task.execution.nextRunAt)}</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">上次执行</p>
                      <p className="text-sm">{formatDateTime(task.execution.lastRunAt)}</p>
                    </div>
                    {task.execution.lastExecutionStatus && (
                      <div>
                        <p className="text-xs text-muted-foreground">上次执行状态</p>
                        {executionStatus && (
                          <Badge className={executionStatus.color}>
                            {executionStatus.label}
                          </Badge>
                        )}
                      </div>
                    )}
                    {task.execution.consecutiveFailures > 0 && (
                      <div>
                        <p className="text-xs text-muted-foreground">连续失败</p>
                        <Badge variant="destructive">
                          {task.execution.consecutiveFailures} 次
                        </Badge>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </div>
            </TabsContent>

            {/* 调度配置 */}
            <TabsContent value="schedule" className="mt-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm flex items-center gap-1">
                    <Settings className="h-4 w-4" />
                    调度配置
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div>
                      <p className="text-xs text-muted-foreground">Cron 表达式</p>
                      <p className="font-mono text-sm">{task.schedule.cronExpression}</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">时区</p>
                      <p className="text-sm">{task.schedule.timezone}</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">开始日期</p>
                      <p className="text-sm">{formatDate(task.schedule.startDate)}</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">结束日期</p>
                      <p className="text-sm">{formatDate(task.schedule.endDate)}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* 执行历史 */}
            <TabsContent value="history" className="mt-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm flex items-center gap-1">
                    <History className="h-4 w-4" />
                    执行历史
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-center h-32 text-muted-foreground">
                    <p>执行历史记录加载中...</p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </ScrollArea>

        <Separator />

        <DialogFooter className="gap-2">
          {task.status === ScheduleTaskStatus.ACTIVE && (
            <Button variant="outline" onClick={handlePause}>
              <Pause className="h-4 w-4 mr-2" />
              暂停
            </Button>
          )}
          {task.status === ScheduleTaskStatus.PAUSED && (
            <Button variant="outline" onClick={handleResume}>
              <Play className="h-4 w-4 mr-2" />
              恢复
            </Button>
          )}
          <Button variant="destructive" onClick={handleDelete}>
            删除
          </Button>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            关闭
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default ScheduleTaskDetailDialog;
