// apps/desktop/src/renderer/modules/goal/presentation/components/GoalRecordDialog.tsx
/**
 * GoalRecordDialog Component
 *
 * 目标进度记录对话框 - 用于添加/编辑进度记录
 */

import { useState, useEffect } from 'react';
import type { GoalRecord, KeyResult } from '@dailyuse/goal/domain-client';
import type { CreateGoalRecordRequest } from '@dailyuse/contracts/goal';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-shadcn';
import { Button } from '@dailyuse/ui-shadcn';
import { Input } from '@dailyuse/ui-shadcn';
import { Label } from '@dailyuse/ui-shadcn';
import { Textarea } from '@dailyuse/ui-shadcn';
import { Badge } from '@dailyuse/ui-shadcn';
import { PlusCircle, Zap } from 'lucide-react';

interface GoalRecordDialogProps {
  open: boolean;
  goalUuid: string;
  keyResultUuid: string;
  keyResult?: KeyResult | null;
  record?: GoalRecord | null;
  goalColor?: string;
  onClose: () => void;
  /** 保存回调 - 使用 contracts 类型 */
  onSave: (data: CreateGoalRecordRequest) => Promise<void>;
}

// 快速选择值
const QUICK_VALUES = [1, 2, 5, 10];

export function GoalRecordDialog({
  open,
  goalUuid,
  keyResultUuid,
  keyResult,
  record,
  goalColor = '#3b82f6',
  onClose,
  onSave,
}: GoalRecordDialogProps) {
  const [value, setValue] = useState<number>(0);
  const [note, setNote] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isEditing = !!record;

  // 重置表单
  useEffect(() => {
    if (open) {
      if (record) {
        setValue(record.value);
        setNote(record.note || '');
      } else {
        setValue(0);
        setNote('');
      }
      setError(null);
    }
  }, [open, record]);

  const isValid = value > 0 && value <= 10000;

  const handleSave = async () => {
    if (!isValid) {
      setError('请输入有效的增加值（大于0且不超过10000）');
      return;
    }

    try {
      setLoading(true);
      setError(null);
      await onSave({ value, note: note.trim() || undefined });
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : '保存失败');
      console.error('[GoalRecordDialog] Failed to save:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleQuickValue = (quickValue: number) => {
    setValue(quickValue);
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <PlusCircle className="h-5 w-5" style={{ color: goalColor }} />
            {isEditing ? '编辑记录' : '添加记录'}
          </DialogTitle>
          {keyResult && (
            <DialogDescription>
              为关键结果 "{keyResult.title}" 添加进度记录
            </DialogDescription>
          )}
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* 增加值输入 */}
          <div className="space-y-2">
            <Label htmlFor="value">增加值 *</Label>
            <div className="relative">
              <Input
                id="value"
                type="number"
                placeholder="请输入本次增加的数值"
                value={value || ''}
                onChange={(e) => setValue(Number(e.target.value))}
                min={0.1}
                step={0.1}
                className="pr-16"
              />
              <Badge
                variant="secondary"
                className="absolute right-2 top-1/2 -translate-y-1/2"
                style={{ backgroundColor: `${goalColor}20`, color: goalColor }}
              >
                单位
              </Badge>
            </div>
            {value > 10000 && (
              <p className="text-sm text-destructive">增加值不能超过10000</p>
            )}
          </div>

          {/* 快速选择 */}
          <div className="space-y-2">
            <Label className="flex items-center gap-1">
              <Zap className="h-4 w-4" />
              快速选择
            </Label>
            <div className="flex flex-wrap gap-2">
              {QUICK_VALUES.map((quickValue) => (
                <Button
                  key={quickValue}
                  type="button"
                  size="sm"
                  variant={value === quickValue ? 'default' : 'outline'}
                  onClick={() => handleQuickValue(quickValue)}
                  style={
                    value === quickValue
                      ? { backgroundColor: goalColor, borderColor: goalColor }
                      : undefined
                  }
                >
                  {quickValue}
                </Button>
              ))}
            </div>
          </div>

          {/* 备注输入 */}
          <div className="space-y-2">
            <Label htmlFor="note">备注说明</Label>
            <Textarea
              id="note"
              placeholder="添加关于此次记录的详细说明..."
              value={note}
              onChange={(e) => setNote(e.target.value)}
              rows={3}
            />
          </div>

          {/* 当前进度预览 */}
          {keyResult && value > 0 && (
            <div className="rounded-lg border p-4 space-y-2">
              <div className="text-sm font-medium">进度预览</div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-muted-foreground">当前值</span>
                <span>{keyResult.progress.currentValue}</span>
              </div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-muted-foreground">增加值</span>
                <span style={{ color: goalColor }}>+{value}</span>
              </div>
              <div className="border-t pt-2 flex items-center justify-between text-sm font-medium">
                <span>预计新值</span>
                <span>{keyResult.progress.currentValue + value}</span>
              </div>
            </div>
          )}

          {/* 错误提示 */}
          {error && (
            <div className="rounded-lg border border-destructive bg-destructive/10 p-3 text-sm text-destructive">
              {error}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={loading}>
            取消
          </Button>
          <Button
            onClick={handleSave}
            disabled={!isValid || loading}
            style={{ backgroundColor: isValid ? goalColor : undefined }}
          >
            {loading ? '保存中...' : '保存'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default GoalRecordDialog;

// packages/app-vue/src/modules/goal/components/dialogs/GoalRecordDialog.vue
<template>
  <Dialog :open="visible" @update:open="(val) => (visible = val)">
    <DialogContent class="sm:max-w-[600px] gap-0 p-0">
      <!-- 对话框头部 -->
      <div class="flex items-center justify-between px-6 pt-6 pb-4">
        <Button variant="ghost" size="sm" @click="handleCancel">
          <X class="mr-1 h-4 w-4" />
          取消
        </Button>
        <div class="flex items-center">
          <PlusCircle class="mr-2 h-5 w-5 text-primary" />
          <span class="text-lg font-bold">{{ isEditing ? '编辑记录' : '添加记录' }}</span>
        </div>
        <Button size="sm" :disabled="!isValid" @click="handleSave">
          <Check class="mr-1 h-4 w-4" />
          保存
        </Button>
      </div>

      <Separator />

      <!-- 表单内容 -->
      <form class="flex flex-col gap-6 p-6" @submit.prevent="handleSave">
        <!-- 增加值输入 -->
        <div class="space-y-2">
          <Label for="change-amount">增加值</Label>
          <div class="relative flex items-center">
            <Plus class="absolute left-3 h-4 w-4 text-muted-foreground" />
            <Input
              id="change-amount"
              v-model.number="localRecord.changeAmount"
              type="number"
              class="pl-9 pr-16"
              min="0.1"
              step="0.1"
            />
            <Badge variant="secondary" class="absolute right-3 font-medium"> 单位 </Badge>
          </div>
          <p v-if="validationError" class="text-xs text-destructive">{{ validationError }}</p>
        </div>

        <!-- 备注输入 -->
        <div class="space-y-2">
          <Label for="record-note" class="flex items-center gap-1">
            <FileText class="h-4 w-4 text-muted-foreground" />
            备注说明
          </Label>
          <Textarea
            id="record-note"
            v-model="localRecord.note"
            placeholder="添加关于此次记录的详细说明..."
            :rows="3"
            class="resize-none"
          />
        </div>

        <!-- 快速选择值 -->
        <div>
          <div class="mb-3 flex items-center text-sm text-muted-foreground">
            <Zap class="mr-1 h-4 w-4" />
            快速选择
          </div>
          <div class="flex flex-wrap gap-2">
            <Badge
              v-for="quickValue in quickValues"
              :key="quickValue"
              :variant="localRecord.changeAmount === quickValue ? 'default' : 'outline'"
              class="cursor-pointer select-none px-3 py-1 text-sm transition-shadow hover:shadow-md"
              @click="localRecord.changeAmount = quickValue"
            >
              {{ quickValue }}
            </Badge>
          </div>
        </div>
      </form>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { computed, watch, ref } from 'vue';
import type { GoalRecordClientDTO } from '@dailyuse/contracts/goal';
import { Dialog, DialogContent } from '@dailyuse/ui-vue-shadcn';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { Input } from '@dailyuse/ui-vue-shadcn';
import { Label } from '@dailyuse/ui-vue-shadcn';
import { Textarea } from '@dailyuse/ui-vue-shadcn';
import { Badge } from '@dailyuse/ui-vue-shadcn';
import { Separator } from '@dailyuse/ui-vue-shadcn';
import { X, PlusCircle, Check, Plus, FileText, Zap } from 'lucide-vue-next';
// composables
import { useGoal } from '../../composables/useGoal';

const { createGoalRecord, goals } = useGoal();

const visible = ref(false);
const propKeyResultId = ref<string>('');
const propGoalId = ref<string>('');
const propRecord = ref<GoalRecordClientDTO | null>(null);

const quickValues = [1, 2, 5, 10];

// 本地表单数据：只需要 changeAmount 和 note
const localRecord = ref({
  changeAmount: 0,
  note: '',
});

const isEditing = computed(() => !!propRecord.value);

const valueRules = [
  (v: number) => !!v || '增加值不能为空',
  (v: number) => v > 0 || '增加值必须大于0',
  (v: number) => v <= 10000 || '增加值不能超过10000',
];

const validationError = computed(() => {
  const v = localRecord.value.changeAmount;
  for (const rule of valueRules) {
    const result = rule(v);
    if (result !== true) return result;
  }
  return '';
});

const isValid = computed(() => !validationError.value && localRecord.value.changeAmount > 0);

const handleCreateKeyResult = async () => {
  // 获取当前 KeyResult
  const currentGoal = goals.value.find((g: any) => g.id === propGoalId.value);
  if (!currentGoal) {
    console.error('未找到目标');
    return;
  }

  const currentKeyResult = currentGoal.keyResults?.find(
    (kr: any) => kr.id === propKeyResultId.value,
  );
  if (!currentKeyResult) {
    console.error('未找到关键结果');
    return;
  }

  // ✅ 新的数据模型：value 就是本次记录的独立值
  // 不需要再加上 previousValue
  await createGoalRecord(propGoalId.value, propKeyResultId.value, {
    value: localRecord.value.changeAmount, // ✅ 直接传递用户输入的值
    note: localRecord.value.note,
    recordedAt: Date.now(),
  });
};

const handleSave = () => {
  if (!isValid.value) return;

  if (isEditing.value) {
    console.warn('不允许编辑记录');
  } else {
    handleCreateKeyResult();
  }
  closeDialog();
};

const handleCancel = () => {
  closeDialog();
};

const openDialog = (goalId: string, keyResultId: string, record?: GoalRecordClientDTO) => {
  propGoalId.value = goalId;
  propKeyResultId.value = keyResultId;
  propRecord.value = record || null;
  visible.value = true;
};

const closeDialog = () => {
  visible.value = false;
};

// 监听弹窗显示，重置表单
watch(
  () => visible.value,
  (show) => {
    if (show) {
      if (propRecord.value) {
        // 编辑模式：显示已有记录
        localRecord.value = {
          changeAmount: propRecord.value.value, // 使用 value 属性
          note: propRecord.value.comment || '',
        };
      } else {
        // 创建模式：重置表单
        localRecord.value = {
          changeAmount: 0,
          note: '',
        };
      }
    }
  },
);

defineExpose({
  openDialog,
});
</script>
