// apps/desktop/src/renderer/modules/goal/presentation/components/KeyResultDialog.tsx
/**
 * KeyResultDialog Component
 *
 * 关键结果对话框 - 用于创建/编辑关键结果
 */

import { useState, useEffect, useMemo } from 'react';
import type { KeyResult, Goal } from '@dailyuse/goal/domain-client';
import type {
  AddKeyResultRequest,
  UpdateKeyResultRequest,
} from '@dailyuse/contracts/goal';
import { AggregationMethod, KeyResultValueType } from '@dailyuse/contracts/goal';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-shadcn';
import { Button } from '@dailyuse/ui-shadcn';
import { Input } from '@dailyuse/ui-shadcn';
import { Label } from '@dailyuse/ui-shadcn';
import { Textarea } from '@dailyuse/ui-shadcn';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@dailyuse/ui-shadcn';
import { Progress } from '@dailyuse/ui-shadcn';
import { Target } from 'lucide-react';

interface KeyResultDialogProps {
  open: boolean;
  goalUuid: string;
  goal?: Goal | null;
  keyResult?: KeyResult | null;
  onClose: () => void;
  /** 保存回调 - 使用 contracts 类型 */
  onSave: (data: AddKeyResultRequest | UpdateKeyResultRequest) => Promise<void>;
}

/**
 * 表单 UI 状态（内部使用）
 */
interface FormState {
  title: string;
  description: string;
  startValue: number;
  targetValue: number;
  currentValue: number;
  weight: number;
  aggregationMethod: AggregationMethod;
}

// 聚合方法选项
const AGGREGATION_METHODS = [
  { value: AggregationMethod.SUM, label: '求和', hint: '适合累计型指标' },
  { value: AggregationMethod.AVERAGE, label: '求平均', hint: '适合平均值型指标' },
  { value: AggregationMethod.MAX, label: '取最大值', hint: '适合峰值型指标' },
  { value: AggregationMethod.MIN, label: '取最小值', hint: '适合低值型指标' },
  { value: AggregationMethod.LAST, label: '取最后一次', hint: '适合绝对值型指标' },
];

const DEFAULT_FORM_STATE: FormState = {
  title: '',
  description: '',
  startValue: 0,
  targetValue: 100,
  currentValue: 0,
  weight: 1,
  aggregationMethod: AggregationMethod.SUM,
};

// ============ Helper Functions ============

/**
 * 将表单状态转换为 AddKeyResultRequest
 */
function formStateToAddRequest(goalUuid: string, form: FormState): AddKeyResultRequest {
  return {
    goalUuid,
    title: form.title,
    description: form.description || undefined,
    valueType: KeyResultValueType.INCREMENTAL, // 默认使用累积值类型
    aggregationMethod: form.aggregationMethod,
    targetValue: form.targetValue,
    currentValue: form.currentValue,
    weight: form.weight,
  };
}

/**
 * 将表单状态转换为 UpdateKeyResultRequest
 */
function formStateToUpdateRequest(form: FormState): UpdateKeyResultRequest {
  return {
    title: form.title,
    description: form.description || undefined,
    startValue: form.startValue,
    targetValue: form.targetValue,
    weight: form.weight,
  };
}

export function KeyResultDialog({
  open,
  goalUuid,
  goal,
  keyResult,
  onClose,
  onSave,
}: KeyResultDialogProps) {
  const [formState, setFormState] = useState<FormState>(DEFAULT_FORM_STATE);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isEditing = !!keyResult;
  const goalColor = goal?.color || '#3b82f6';

  // 重置表单
  useEffect(() => {
    if (open) {
      if (keyResult) {
        setFormState({
          title: keyResult.title,
          description: keyResult.description || '',
          startValue: 0, // 初始值默认为0
          targetValue: keyResult.progress.targetValue,
          currentValue: keyResult.progress.currentValue,
          weight: keyResult.weight,
          aggregationMethod: keyResult.progress.aggregationMethod || AggregationMethod.SUM,
        });
      } else {
        setFormState(DEFAULT_FORM_STATE);
      }
      setError(null);
    }
  }, [open, keyResult]);

  // 计算预览进度
  const progressPreview = useMemo(() => {
    const { startValue, currentValue, targetValue } = formState;
    const range = targetValue - startValue;
    if (range <= 0) return 0;
    const progress = ((currentValue - startValue) / range) * 100;
    return Math.min(Math.max(progress, 0), 100);
  }, [formState.startValue, formState.currentValue, formState.targetValue]);

  // 表单验证
  const isValid = useMemo(() => {
    return (
      formState.title.trim().length > 0 &&
      formState.targetValue > formState.startValue &&
      formState.weight >= 1 &&
      formState.weight <= 10
    );
  }, [formState]);

  const handleChange = <K extends keyof FormState>(
    key: K,
    value: FormState[K]
  ) => {
    setFormState((prev) => ({ ...prev, [key]: value }));
  };

  const handleSave = async () => {
    if (!isValid) {
      setError('请检查表单填写是否正确');
      return;
    }

    try {
      setLoading(true);
      setError(null);
      // 转换为 contracts 类型
      const request = isEditing 
        ? formStateToUpdateRequest(formState)
        : formStateToAddRequest(goalUuid, formState);
      await onSave(request);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : '保存失败');
      console.error('[KeyResultDialog] Failed to save:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Target className="h-5 w-5" style={{ color: goalColor }} />
            {isEditing ? '编辑关键结果' : '创建关键结果'}
          </DialogTitle>
          <DialogDescription>
            {isEditing
              ? '修改关键结果的信息'
              : '为目标添加一个新的关键结果，用于衡量目标进度'}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* 基本信息 */}
          <div className="space-y-4">
            <h4 className="font-medium">基本信息</h4>

            <div className="space-y-2">
              <Label htmlFor="title">名称 *</Label>
              <Input
                id="title"
                placeholder="例如：新增活跃用户数量"
                value={formState.title}
                onChange={(e) => handleChange('title', e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">描述</Label>
              <Textarea
                id="description"
                placeholder="描述这个关键结果..."
                value={formState.description}
                onChange={(e) => handleChange('description', e.target.value)}
                rows={2}
              />
            </div>
          </div>

          {/* 数值配置 */}
          <div className="space-y-4">
            <h4 className="font-medium">数值配置</h4>

            <div className="grid grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startValue">起始值</Label>
                <Input
                  id="startValue"
                  type="number"
                  value={formState.startValue}
                  onChange={(e) => handleChange('startValue', Number(e.target.value))}
                />
                <p className="text-xs text-muted-foreground">初始数值</p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="targetValue">目标值 *</Label>
                <Input
                  id="targetValue"
                  type="number"
                  value={formState.targetValue}
                  onChange={(e) => handleChange('targetValue', Number(e.target.value))}
                />
                <p className="text-xs text-muted-foreground">期望达到的数值</p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="currentValue">当前值</Label>
                <Input
                  id="currentValue"
                  type="number"
                  value={formState.currentValue}
                  onChange={(e) => handleChange('currentValue', Number(e.target.value))}
                />
                <p className="text-xs text-muted-foreground">目前的实际数值</p>
              </div>
            </div>
          </div>

          {/* 高级配置 */}
          <div className="space-y-4">
            <h4 className="font-medium">高级配置</h4>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="aggregationMethod">进度计算方法</Label>
                <Select
                  value={formState.aggregationMethod}
                  onValueChange={(value) =>
                    handleChange('aggregationMethod', value as AggregationMethod)
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="选择计算方法" />
                  </SelectTrigger>
                  <SelectContent>
                    {AGGREGATION_METHODS.map((method) => (
                      <SelectItem key={method.value} value={method.value}>
                        <div className="flex flex-col">
                          <span>{method.label}</span>
                          <span className="text-xs text-muted-foreground">
                            {method.hint}
                          </span>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="weight">权重 (1-10)</Label>
                <Input
                  id="weight"
                  type="number"
                  min={1}
                  max={10}
                  value={formState.weight}
                  onChange={(e) => handleChange('weight', Number(e.target.value))}
                />
                <p className="text-xs text-muted-foreground">
                  该关键结果在目标中的重要程度
                </p>
              </div>
            </div>
          </div>

          {/* 进度预览 */}
          {formState.title && (
            <div className="rounded-lg border p-4 space-y-3">
              <h4 className="font-medium">进度预览</h4>
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm truncate max-w-[70%]">
                  {formState.title || '关键结果名称'}
                </span>
                <span
                  className="text-lg font-bold"
                  style={{ color: goalColor }}
                >
                  {progressPreview.toFixed(1)}%
                </span>
              </div>
              <Progress
                value={progressPreview}
                className="h-3"
              />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>{formState.startValue}</span>
                <span>
                  {formState.currentValue} / {formState.targetValue}
                </span>
              </div>
            </div>
          )}

          {/* 错误提示 */}
          {error && (
            <div className="rounded-lg border border-destructive bg-destructive/10 p-3 text-sm text-destructive">
              {error}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={loading}>
            取消
          </Button>
          <Button
            onClick={handleSave}
            disabled={!isValid || loading}
            style={{ backgroundColor: isValid ? goalColor : undefined }}
          >
            {loading ? '保存中...' : isEditing ? '更新' : '创建'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default KeyResultDialog;

// packages/app-vue/src/modules/goal/components/dialogs/KeyResultDialog.vue
<template>
  <Dialog :open="visible" @update:open="(val) => (visible = val)">
    <DialogContent class="sm:max-w-[700px] max-h-[90vh] overflow-y-auto gap-0">
      <!-- 对话框头部 -->
      <DialogHeader class="pb-4">
        <DialogTitle class="flex items-center gap-3 text-xl">
          <Target class="h-5 w-5 text-primary" />
          {{ isEditing ? '更新关键结果' : '创建关键结果' }}
        </DialogTitle>
      </DialogHeader>

      <Separator />

      <form class="space-y-6 py-6" @submit.prevent>
        <!-- 基本信息 -->
        <div>
          <h3 class="text-base font-semibold mb-4 text-primary border-b-2 border-primary/10 pb-2">
            基本信息
          </h3>
          <div class="grid grid-cols-12 gap-4">
            <!-- 关键结果名称 -->
            <div class="col-span-12 grid gap-2">
              <Label for="kr-title">关键结果名称*</Label>
              <Input id="kr-title" v-model="keyResultTitle" placeholder="例如：新增活跃用户数量" />
            </div>

            <!-- 描述 -->
            <div class="col-span-12 grid gap-2">
              <Label for="kr-description">描述</Label>
              <Textarea
                id="kr-description"
                v-model="keyResultDescription"
                placeholder="可选：说明如何衡量和达成这个关键结果"
                class="min-h-[60px] resize-none"
              />
            </div>
          </div>
        </div>

        <!-- 数值配置 -->
        <div>
          <h3 class="text-base font-semibold mb-4 text-primary border-b-2 border-primary/10 pb-2">
            数值配置
          </h3>
          <div class="grid grid-cols-12 gap-4">
            <!-- 起始值 -->
            <div class="col-span-4 grid gap-2">
              <Label for="kr-start">起始值*</Label>
              <Input id="kr-start" v-model.number="keyResultStartValue" type="number" />
              <p class="text-xs text-muted-foreground">关键结果的初始数值</p>
            </div>

            <!-- 目标值 -->
            <div class="col-span-4 grid gap-2">
              <Label for="kr-target">目标值*</Label>
              <Input id="kr-target" v-model.number="keyResultTargetValue" type="number" />
              <p class="text-xs text-muted-foreground">期望达到的目标数值</p>
            </div>

            <!-- 当前值 -->
            <div class="col-span-4 grid gap-2">
              <Label for="kr-current">当前值</Label>
              <Input id="kr-current" v-model.number="keyResultCurrentValue" type="number" />
              <p class="text-xs text-muted-foreground">目前的实际数值</p>
            </div>
          </div>
        </div>

        <!-- 高级配置 -->
        <div>
          <h3 class="text-base font-semibold mb-4 text-primary border-b-2 border-primary/10 pb-2">
            高级配置
          </h3>
          <div class="grid grid-cols-12 gap-4">
            <!-- 计算方法 -->
            <div class="col-span-6 grid gap-2">
              <Label>进度计算方法*</Label>
              <Select v-model="keyResultCalculationMethod">
                <SelectTrigger>
                  <SelectValue placeholder="选择计算方法" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem
                    v-for="method in calculationMethods"
                    :key="method.value"
                    :value="method.value"
                  >
                    {{ method.title }}
                  </SelectItem>
                </SelectContent>
              </Select>
              <p class="text-xs text-muted-foreground">选择如何计算进度百分比</p>
            </div>

            <!-- 权重 -->
            <div class="col-span-6 grid gap-2">
              <Label for="kr-weight">权重*</Label>
              <Input
                id="kr-weight"
                v-model.number="keyResultWeight"
                type="number"
                min="1"
                max="10"
                step="1"
              />
              <p class="text-xs text-muted-foreground">该关键结果在目标中的重要程度 (1-10)</p>
            </div>
          </div>
        </div>

        <!-- 进度预览 -->
        <div v-if="progressPercentage >= 0">
          <h3 class="text-base font-semibold mb-3 text-primary border-b-2 border-primary/10 pb-2">
            进度预览
          </h3>
          <div
            class="rounded-lg border-2 border-primary/10 p-4 transition-all hover:border-primary/30 hover:shadow-md"
          >
            <div class="flex items-center justify-between mb-2">
              <span class="text-sm font-medium">{{ keyResultTitle || '关键结果名称' }}</span>
              <span class="text-base font-bold" :class="progressColor">
                {{ progressPercentage.toFixed(1) }}%
              </span>
            </div>

            <Progress
              :model-value="progressPercentage"
              class="h-3 mb-2"
              :class="progressBarClass"
            />

            <div class="flex justify-between text-xs text-muted-foreground">
              <span>{{ keyResultStartValue }}</span>
              <span>{{ keyResultCurrentValue }} / {{ keyResultTargetValue }}</span>
            </div>
          </div>
        </div>
      </form>

      <Separator />

      <DialogFooter class="pt-4 gap-2 sm:gap-0">
        <div class="flex-1" />
        <Button variant="outline" @click="handleCancel"> 取消 </Button>
        <Button :disabled="!isFormValid || loading" @click="handleSave">
          <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
          {{ isEditing ? '更新' : '创建' }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { GoalClientDTO, KeyResultClientDTO } from '@dailyuse/contracts/goal';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@dailyuse/ui-vue-shadcn';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { Input } from '@dailyuse/ui-vue-shadcn';
import { Label } from '@dailyuse/ui-vue-shadcn';
import { Textarea } from '@dailyuse/ui-vue-shadcn';
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@dailyuse/ui-vue-shadcn';
import { Separator } from '@dailyuse/ui-vue-shadcn';
import { Progress } from '@dailyuse/ui-vue-shadcn';
import { Target, Loader2 } from 'lucide-vue-next';

const AggregationMethod = {
  SUM: 'SUM',
  AVERAGE: 'AVERAGE',
  MAX: 'MAX',
  MIN: 'MIN',
  LAST: 'LAST',
} as const;

type EditableKeyResult = {
  id?: KeyResultClientDTO['id'];
  title: string;
  description: string | null;
  weight: number;
  order: number;
  progress: {
    valueType: string;
    aggregationMethod: string;
    initialValue: number;
    targetValue: number;
    currentValue: number;
    unit: string | null;
  };
};

const emit = defineEmits<{
  save: [
    payload: {
      goalId: string | null;
      keyResult: EditableKeyResult;
      isEditing: boolean;
      isInGoalEditing: boolean;
    },
  ];
  cancel: [];
}>();

const createDraftKeyResult = (): EditableKeyResult => ({
  title: '',
  description: null,
  weight: 5,
  order: 0,
  progress: {
    valueType: 'NUMBER',
    aggregationMethod: AggregationMethod.SUM,
    initialValue: 0,
    targetValue: 100,
    currentValue: 0,
    unit: null,
  },
});

const visible = ref(false);
const propKeyResult = ref<KeyResultClientDTO | null>(null);
const propGoalId = ref<string | null>(null);
const propGoal = ref<GoalClientDTO | null>(null);
const isInGoalEditing = computed(() => !!propGoal.value);

const localKeyResult = ref<EditableKeyResult>(createDraftKeyResult());
const loading = ref(false);
const isEditing = computed(() => !!propKeyResult.value);
const isFormValid = computed(() => {
  const title = keyResultTitle.value.trim();
  const weight = keyResultWeight.value;
  return title.length > 0 && weight >= 1 && weight <= 10;
});
const progressPercentage = computed(() => {
  const progress = localKeyResult.value.progress;
  if (!progress.targetValue || progress.targetValue <= 0) return 0;
  return Math.min(100, Math.max(0, (progress.currentValue / progress.targetValue) * 100));
});

const keyResultTitle = computed({
  get: () => localKeyResult.value.title || '',
  set: (val: string) => {
    localKeyResult.value.title = val;
  },
});

const keyResultDescription = computed({
  get: () => localKeyResult.value.description || '',
  set: (val: string) => {
    localKeyResult.value.description = val || null;
  },
});

const keyResultStartValue = computed({
  get: () => localKeyResult.value.progress.initialValue || 0,
  set: (val: number) => {
    localKeyResult.value.progress.initialValue = val;
  },
});

const keyResultTargetValue = computed({
  get: () => localKeyResult.value.progress.targetValue || 100,
  set: (val: number) => {
    localKeyResult.value.progress.targetValue = val;
  },
});

const keyResultCurrentValue = computed({
  get: () => localKeyResult.value.progress.currentValue || 0,
  set: (val: number) => {
    localKeyResult.value.progress.currentValue = val;
  },
});

const keyResultCalculationMethod = computed({
  get: () => localKeyResult.value.progress.aggregationMethod || 'SUM',
  set: (val: string) => {
    localKeyResult.value.progress.aggregationMethod = val;
  },
});

const keyResultWeight = computed({
  get: () => localKeyResult.value.weight || 5,
  set: (val: number) => {
    localKeyResult.value.weight = val;
  },
});

const calculationMethods = [
  { title: '累加 - 适用于递增指标', value: AggregationMethod.SUM },
  { title: '平均值 - 适用于波动指标', value: AggregationMethod.AVERAGE },
  { title: '最大值 - 取最高值', value: AggregationMethod.MAX },
  { title: '最小值 - 取最低值', value: AggregationMethod.MIN },
  { title: '取最后一次 - 适用于绝对值', value: AggregationMethod.LAST },
];

const progressColor = computed(() => {
  const progress = progressPercentage.value;
  if (progress >= 80) return 'text-green-600';
  if (progress >= 60) return 'text-yellow-600';
  if (progress >= 40) return 'text-orange-500';
  return 'text-red-600';
});

const progressBarClass = computed(() => {
  const progress = progressPercentage.value;
  if (progress >= 80) return '[&>div]:bg-green-500';
  if (progress >= 60) return '[&>div]:bg-yellow-500';
  if (progress >= 40) return '[&>div]:bg-orange-500';
  return '[&>div]:bg-red-500';
});

const handleSave = async () => {
  if (!isFormValid.value || loading.value) return;

  loading.value = true;
  try {
    emit('save', {
      goalId: propGoalId.value,
      keyResult: { ...localKeyResult.value },
      isEditing: isEditing.value,
      isInGoalEditing: isInGoalEditing.value,
    });
    closeDialog();
  } finally {
    loading.value = false;
  }
};

const handleCancel = () => {
  emit('cancel');
  closeDialog();
};
const closeDialog = () => {
  visible.value = false;
};
const openDialog = ({
  goalId,
  keyResult,
  goal,
}: {
  goalId?: string;
  keyResult?: KeyResultClientDTO;
  goal?: GoalClientDTO;
}) => {
  propGoalId.value = goalId || null;
  propKeyResult.value = keyResult || null;
  propGoal.value = goal || null;
  visible.value = true;
};

const openForCreateKeyResultInGoalEditing = (goal: GoalClientDTO) => {
  openDialog({ goal });
};

const openForUpdateKeyResultInGoalEditing = (
  goal: GoalClientDTO,
  keyResult: KeyResultClientDTO,
) => {
  openDialog({ goal, keyResult });
};

const openForCreateKeyResult = (goalId: string) => {
  openDialog({ goalId });
};

const openForUpdateKeyResult = (goalId: string, keyResult: KeyResultClientDTO) => {
  openDialog({ goalId, keyResult });
};

watch([() => visible.value, () => propKeyResult.value], ([newValue]) => {
  if (newValue) {
    if (propKeyResult.value) {
      localKeyResult.value = {
        id: propKeyResult.value.id,
        title: propKeyResult.value.title,
        description: propKeyResult.value.description,
        weight: propKeyResult.value.weight,
        order: propKeyResult.value.order,
        progress: {
          valueType: propKeyResult.value.progress.valueType as string,
          aggregationMethod: propKeyResult.value.progress.aggregationMethod as string,
          initialValue: propKeyResult.value.progress.initialValue,
          targetValue: propKeyResult.value.progress.targetValue,
          currentValue: propKeyResult.value.progress.currentValue,
          unit: propKeyResult.value.progress.unit,
        },
      };
    } else {
      localKeyResult.value = createDraftKeyResult();
    }
  } else {
    localKeyResult.value = createDraftKeyResult();
  }
});

defineExpose({
  openForCreateKeyResultInGoalEditing,
  openForUpdateKeyResultInGoalEditing,
  openForCreateKeyResult,
  openForUpdateKeyResult,
});
</script>
