// packages/ui-vue-shadcn/src/components/custom/schedule/ScheduleEventList.vue
<template>
  <Card>
    <CardHeader>
      <div class="flex items-center justify-between">
        <CardTitle>日程事件</CardTitle>
        <Button @click="$emit('create')">
          <Plus class="mr-2 h-4 w-4" />
          创建日程
        </Button>
      </div>
    </CardHeader>

    <CardContent>
      <!-- Loading -->
      <div v-if="loading" class="flex justify-center items-center py-8">
        <Loader2 class="h-8 w-8 animate-spin text-primary" />
      </div>

      <!-- Error -->
      <Alert v-else-if="error" variant="destructive" class="mb-4">
        <AlertCircle class="h-4 w-4" />
        <AlertTitle>错误</AlertTitle>
        <AlertDescription>{{ error }}</AlertDescription>
      </Alert>

      <!-- Empty State -->
      <div v-else-if="schedules.length === 0" class="text-center py-12">
        <CalendarOff class="mx-auto h-12 w-12 text-muted-foreground" />
        <h3 class="mt-4 text-lg font-semibold">暂无日程</h3>
        <p class="text-sm text-muted-foreground mt-2">点击右上角按钮创建您的第一个日程</p>
      </div>

      <!-- Schedule List -->
      <div v-else class="space-y-2">
        <div
          v-for="schedule in schedules"
          :key="schedule.uuid"
          class="flex items-start gap-4 p-4 rounded-lg border hover:bg-accent cursor-pointer transition-colors"
          @click="$emit('schedule-click', schedule)"
        >
          <div class="flex-shrink-0">
            <div
              class="w-10 h-10 rounded-full flex items-center justify-center"
              :class="getPriorityColorClass(schedule.priority)"
            >
              <Calendar class="h-5 w-5 text-white" />
            </div>
          </div>

          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <h4 class="font-semibold">{{ schedule.title }}</h4>
              <Badge v-if="schedule.hasConflict" variant="destructive" class="gap-1">
                <AlertCircle class="h-3 w-3" />
                冲突
              </Badge>
            </div>

            <div class="flex items-center gap-2 mt-1 text-sm text-muted-foreground">
              <Clock class="h-4 w-4" />
              <span>{{ formatDateTime(schedule.startTime) }} - {{ formatDateTime(schedule.endTime) }}</span>
              <span class="ml-2">({{ schedule.duration }}分钟)</span>
            </div>

            <div v-if="schedule.location" class="flex items-center gap-2 mt-1 text-sm text-muted-foreground">
              <MapPin class="h-4 w-4" />
              <span>{{ schedule.location }}</span>
            </div>

            <p v-if="schedule.description" class="mt-2 text-sm text-muted-foreground line-clamp-2">
              {{ schedule.description }}
            </p>
          </div>

          <Button
            variant="ghost"
            size="sm"
            @click.stop="$emit('delete', schedule.uuid)"
            class="flex-shrink-0"
          >
            <Trash2 class="h-4 w-4 text-destructive" />
          </Button>
        </div>
      </div>
    </CardContent>
  </Card>
</template>

<script setup lang="ts">
import { Card, CardContent, CardHeader, CardTitle } from '../../ui/card';
import { Button } from '../../ui/button';
import { Badge } from '../../ui/badge';
import { Alert, AlertDescription, AlertTitle } from '../../ui/alert';
import { Plus, Calendar, Clock, MapPin, Trash2, Loader2, AlertCircle, CalendarOff } from 'lucide-vue-next';
import type { ScheduleClientDTO } from '@dailyuse/contracts/schedule';

interface Props {
  schedules: ScheduleClientDTO[];
  loading?: boolean;
  error?: string | null;
}

interface Emits {
  (e: 'create'): void;
  (e: 'schedule-click', schedule: ScheduleClientDTO): void;
  (e: 'delete', uuid: string): void;
}

withDefaults(defineProps<Props>(), {
  loading: false,
  error: null,
});

defineEmits<Emits>();

function formatDateTime(timestamp: number): string {
  const date = new Date(timestamp);
  return date.toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function getPriorityColorClass(priority: number | null | undefined): string {
  if (!priority) return 'bg-gray-500';
  if (priority >= 5) return 'bg-red-500';
  if (priority >= 4) return 'bg-orange-500';
  if (priority >= 3) return 'bg-blue-500';
  return 'bg-green-500';
}
</script>

// apps/desktop/src/renderer/modules/schedule/presentation/components/ScheduleEventList.tsx
/**
 * ScheduleEventList Component
 *
 * 日程事件列表组件
 * 功能�?
 * 1. 显示日程事件列表
 * 2. 时间排序
 * 3. 快速操作（编辑、删除）
 * 4. 冲突提示
 */

import { useMemo, useCallback } from 'react';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import type { ScheduleClientDTO } from '../stores/scheduleStore';
import { Card, CardContent, CardHeader, CardTitle } from '@dailyuse/ui-react-shadcn';
import { Button } from '@dailyuse/ui-react-shadcn';
import { Badge } from '@dailyuse/ui-react-shadcn';
import { ScrollArea } from '@dailyuse/ui-react-shadcn';
import {
  Plus,
  Calendar,
  Clock,
  MapPin,
  Trash2,
  AlertTriangle,
  FileText,
} from 'lucide-react';

// ===================== 接口定义 =====================

interface ScheduleEventListProps {
  schedules: ScheduleClientDTO[];
  isLoading?: boolean;
  title?: string;
  showCreateButton?: boolean;
  onScheduleClick?: (schedule: ScheduleClientDTO) => void;
  onDelete?: (uuid: string) => void;
  onCreate?: () => void;
}

// ===================== 工具函数 =====================

function formatDateTime(date: Date | number): string {
  const d = typeof date === 'number' ? new Date(date) : date;
  return format(d, 'M月d'HH:mm', { locale: zhCN });
}

function getPriorityColor(priority?: number | null): string {
  if (!priority) return 'bg-gray-500';
  if (priority >= 4) return 'bg-red-500';
  if (priority >= 3) return 'bg-orange-500';
  if (priority >= 2) return 'bg-yellow-500';
  return 'bg-blue-500';
}

function formatDuration(minutes?: number): string {
  if (!minutes) return '';
  if (minutes < 60) return `${minutes}分钟`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}小时${mins}分钟` : `${hours}小时`;
}

// ===================== 组件 =====================

export function ScheduleEventList({
  schedules,
  isLoading = false,
  title = '日程事件',
  showCreateButton = true,
  onScheduleClick,
  onDelete,
  onCreate,
}: ScheduleEventListProps) {
  // 按开始时间排�?
  const sortedSchedules = useMemo(() => {
    return [...schedules].sort((a, b) => {
      const timeA = typeof a.startTime === 'number' ? a.startTime : new Date(a.startTime).getTime();
      const timeB = typeof b.startTime === 'number' ? b.startTime : new Date(b.startTime).getTime();
      return timeA - timeB;
    });
  }, [schedules]);

  const handleDelete = useCallback((e: React.MouseEvent, uuid: string) => {
    e.stopPropagation();
    onDelete?.(uuid);
  }, [onDelete]);

  return (
    <Card className="h-full flex flex-col">
      <CardHeader className="pb-2 shrink-0">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg">{title}</CardTitle>
          {showCreateButton && (
            <Button size="sm" onClick={onCreate}>
              <Plus className="h-4 w-4 mr-1" />
              创建日程
            </Button>
          )}
        </div>
      </CardHeader>

      <CardContent className="flex-1 p-0 overflow-hidden">
        {isLoading ? (
          <div className="flex items-center justify-center h-32">
            <div className="text-muted-foreground">加载中...</div>
          </div>
        ) : sortedSchedules.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-32 text-muted-foreground">
            <Calendar className="h-8 w-8 mb-2 opacity-50" />
            <p>暂无日程</p>
            <p className="text-xs mt-1">点击上方按钮创建第一个日</p>
          </div>
        ) : (
          <ScrollArea className="h-full">
            <div className="p-4 space-y-3">
              {sortedSchedules.map((schedule) => (
                <div
                  key={schedule.uuid}
                  className="flex items-start gap-3 p-3 rounded-lg border hover:shadow-md transition-all cursor-pointer group"
                  onClick={() => onScheduleClick?.(schedule)}
                >
                  {/* 优先级指示器 */}
                  <div
                    className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${getPriorityColor(
                      schedule.priority
                    )}`}
                  >
                    <Calendar className="h-5 w-5 text-white" />
                  </div>

                  {/* 内容 */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium truncate">{schedule.title}</span>
                      {schedule.hasConflict && (
                        <Badge variant="outline" className="text-yellow-600 border-yellow-600 shrink-0">
                          <AlertTriangle className="h-3 w-3 mr-1" />
                          冲突
                        </Badge>
                      )}
                    </div>

                    <div className="mt-1 space-y-0.5">
                      {/* 时间 */}
                      <div className="flex items-center gap-1 text-xs text-muted-foreground">
                        <Clock className="h-3 w-3" />
                        <span>{formatDateTime(schedule.startTime)}</span>
                        <span>-</span>
                        <span>{formatDateTime(schedule.endTime)}</span>
                        {schedule.duration && (
                          <span className="ml-1">({formatDuration(schedule.duration)})</span>
                        )}
                      </div>

                      {/* 地点 */}
                      {schedule.location && (
                        <div className="flex items-center gap-1 text-xs text-muted-foreground">
                          <MapPin className="h-3 w-3" />
                          <span className="truncate">{schedule.location}</span>
                        </div>
                      )}

                      {/* 描述 */}
                      {schedule.description && (
                        <div className="flex items-start gap-1 text-xs text-muted-foreground">
                          <FileText className="h-3 w-3 mt-0.5 shrink-0" />
                          <span className="line-clamp-2">{schedule.description}</span>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* 删除按钮 */}
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity shrink-0"
                    onClick={(e) => handleDelete(e, schedule.uuid)}
                  >
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </div>
              ))}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}

export default ScheduleEventList;
