// apps/desktop/src/renderer/modules/reminder/presentation/components/cards/ReminderTemplateCard.tsx
/**
 * ReminderTemplateCard - 提醒模板详情卡片
 *
 * 显示模板详细信息的对话框�?
 * - 标题栏带启用/禁用开�?
 * - 状态指�?
 * - 基本信息（标题、描述、触发器、配置）
 * - 统计数据（总实例、已完成、待处理�?
 * - 时间信息（创建、更新时间）
 * - 操作按钮（编辑、查看实例）
 *
 * @module reminder/presentation/components/cards
 */

import { useState, useCallback, useMemo } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  Button,
  Badge,
  Switch,
  Label,
  Separator,
  Card,
  CardContent,
  cn,
} from '@dailyuse/ui-react-shadcn';

import {
  Bell,
  FileText,
  Clock,
  Settings,
  Calendar,
  CalendarClock,
  Pencil,
  Eye,
  X,
  CheckCircle,
  AlertCircle,
  PauseCircle,
  Folder,
} from 'lucide-react';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import type { ReminderTemplateClientDTO } from '@dailyuse/contracts/reminder';

// ============ Types ============

export interface TemplateStats {
  total: number;
  completed: number;
  pending: number;
}

export interface ReminderTemplateCardProps {
  /** 模板数据 */
  template: ReminderTemplateClientDTO | null;
  /** 是否打开 */
  open: boolean;
  /** 统计数据 */
  stats?: TemplateStats;
  /** 关闭回调 */
  onClose: () => void;
  /** 编辑模板 */
  onEdit?: (template: ReminderTemplateClientDTO) => void;
  /** 查看实例 */
  onViewInstances?: (template: ReminderTemplateClientDTO) => void;
  /** 切换启用状�?*/
  onToggleEnabled?: (template: ReminderTemplateClientDTO, enabled: boolean) => Promise<void>;
}

// ============ Utils ============

function formatDate(dateValue?: string | number | Date): string {
  if (!dateValue) return '未知';
  const date = typeof dateValue === 'number' 
    ? new Date(dateValue)
    : typeof dateValue === 'string' 
      ? new Date(dateValue) 
      : dateValue;
  return format(date, 'yyyy年MM月dd日 HH:mm', { locale: zhCN });
}

function getStatusInfo(template: ReminderTemplateClientDTO) {
  if (!template.effectiveEnabled) {
    return {
      color: 'secondary' as const,
      icon: PauseCircle,
      text: '已暂',
    };
  }
  // 可以根据 nextTriggerTime 等字段判断更多状�?
  return {
    color: 'default' as const,
    icon: CheckCircle,
    text: '活跃',
  };
}

function getTriggerText(template: ReminderTemplateClientDTO): string {
  // �?trigger 配置获取触发器描�?
  if (template.triggerText) {
    return template.triggerText;
  }
  if (!template.trigger) {
    return '未设';
  }

  const { type } = template.trigger;
  switch (type) {
    case 'FIXED_TIME':
      return `固定时间: ${template.trigger.fixedTime?.time || '未设'}`;
    case 'INTERVAL':
      return `间隔: ${template.trigger.interval?.minutes || 0} 分钟`;
    default:
      return type || '未知';
  }
}

// ============ Component ============

export function ReminderTemplateCard({
  template,
  open,
  stats = { total: 0, completed: 0, pending: 0 },
  onClose,
  onEdit,
  onViewInstances,
  onToggleEnabled,
}: ReminderTemplateCardProps) {
  const [isTogglingStatus, setIsTogglingStatus] = useState(false);
  const [localEnabled, setLocalEnabled] = useState(template?.effectiveEnabled ?? true);

  // 状态信�?
  const statusInfo = useMemo(() => {
    if (!template) return null;
    return getStatusInfo(template);
  }, [template]);

  // 处理切换启用状�?
  const handleToggleStatus = useCallback(async (checked: boolean) => {
    if (!template || !onToggleEnabled) return;

    setIsTogglingStatus(true);
    try {
      await onToggleEnabled(template, checked);
      setLocalEnabled(checked);
    } finally {
      setIsTogglingStatus(false);
    }
  }, [template, onToggleEnabled]);

  // 处理编辑
  const handleEdit = useCallback(() => {
    if (template && onEdit) {
      onEdit(template);
    }
  }, [template, onEdit]);

  // 处理查看实例
  const handleViewInstances = useCallback(() => {
    if (template && onViewInstances) {
      onViewInstances(template);
    }
  }, [template, onViewInstances]);

  if (!template) return null;

  const StatusIcon = statusInfo?.icon || CheckCircle;

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        {/* 标题�?*/}
        <DialogHeader className="bg-primary text-primary-foreground -m-6 mb-4 p-6 rounded-t-lg">
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2 text-primary-foreground">
              <Bell className="h-5 w-5" />
              <span>{template.title}</span>
            </DialogTitle>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2">
                <Switch
                  checked={localEnabled}
                  onCheckedChange={handleToggleStatus}
                  disabled={isTogglingStatus}
                />
                <Label className="text-sm text-primary-foreground">
                  {localEnabled ? '已启用' : '已禁用'}
                </Label>
              </div>
              <Button
                variant="ghost"
                size="icon"
                className="text-primary-foreground hover:text-primary-foreground/80"
                onClick={onClose}
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </DialogHeader>

        {/* 状态指�?*/}
        <div className="flex items-center gap-2 py-2 bg-muted -mx-6 px-6">
          <Badge variant={statusInfo?.color}>
            <StatusIcon className="h-3 w-3 mr-1" />
            {statusInfo?.text}
          </Badge>
          {template.groupId && (
            <Badge variant="outline">
              <Folder className="h-3 w-3 mr-1" />
              分组�?
            </Badge>
          )}
        </div>

        <Separator className="my-4" />

        {/* 基本信息 */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold flex items-center gap-2 text-muted-foreground">
            基本信息
          </h3>

          <div className="space-y-3">
            {/* 标题 */}
            <div className="flex items-start gap-3">
              <FileText className="h-4 w-4 text-primary mt-0.5" />
              <div>
                <p className="text-xs text-muted-foreground">标题</p>
                <p className="text-sm">{template.title}</p>
              </div>
            </div>

            {/* 描述 */}
            {template.description && (
              <div className="flex items-start gap-3">
                <FileText className="h-4 w-4 text-blue-500 mt-0.5" />
                <div>
                  <p className="text-xs text-muted-foreground">描述</p>
                  <p className="text-sm text-wrap">{template.description}</p>
                </div>
              </div>
            )}

            {/* 触发�?*/}
            <div className="flex items-start gap-3">
              <Clock className="h-4 w-4 text-green-500 mt-0.5" />
              <div>
                <p className="text-xs text-muted-foreground">触发</p>
                <Badge variant="outline" className="mt-1">
                  {getTriggerText(template)}
                </Badge>
              </div>
            </div>

            {/* 触发配置 */}
            {template.trigger && (
              <div className="flex items-start gap-3">
                <Settings className="h-4 w-4 text-orange-500 mt-0.5" />
                <div>
                  <p className="text-xs text-muted-foreground">触发配置</p>
                  <div className="flex flex-wrap gap-1 mt-1">
                    <Badge variant="secondary" className="text-xs">
                      类型: {template.trigger.type || 'unknown'}
                    </Badge>
                    {template.trigger.interval && (
                      <Badge variant="secondary" className="text-xs">
                        间隔: {template.trigger.interval.minutes} 分钟
                      </Badge>
                    )}
                    {template.trigger.fixedTime && (
                      <Badge variant="secondary" className="text-xs">
                        时间: {template.trigger.fixedTime.time}
                      </Badge>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        <Separator className="my-4" />

        {/* 统计信息 */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold flex items-center gap-2 text-muted-foreground">
            统计数据
          </h3>

          <div className="grid grid-cols-3 gap-4">
            <Card className="bg-primary/10">
              <CardContent className="pt-4 text-center">
                <p className="text-2xl font-bold text-primary">{stats.total}</p>
                <p className="text-xs text-muted-foreground">总实</p>
              </CardContent>
            </Card>
            <Card className="bg-green-500/10">
              <CardContent className="pt-4 text-center">
                <p className="text-2xl font-bold text-green-600">{stats.completed}</p>
                <p className="text-xs text-muted-foreground">已完</p>
              </CardContent>
            </Card>
            <Card className="bg-orange-500/10">
              <CardContent className="pt-4 text-center">
                <p className="text-2xl font-bold text-orange-600">{stats.pending}</p>
                <p className="text-xs text-muted-foreground">待处</p>
              </CardContent>
            </Card>
          </div>
        </div>

        <Separator className="my-4" />

        {/* 时间信息 */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold flex items-center gap-2 text-muted-foreground">
            时间信息
          </h3>

          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <Calendar className="h-4 w-4 text-gray-500 mt-0.5" />
              <div>
                <p className="text-xs text-muted-foreground">创建时间</p>
                <p className="text-sm">{formatDate(template.createdAt)}</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <CalendarClock className="h-4 w-4 text-gray-500 mt-0.5" />
              <div>
                <p className="text-xs text-muted-foreground">更新时间</p>
                <p className="text-sm">{formatDate(template.updatedAt)}</p>
              </div>
            </div>
          </div>
        </div>

        <Separator className="my-4" />

        {/* 操作按钮 */}
        <div className="flex items-center justify-between pt-2">
          <div className="flex items-center gap-2">
            <Button onClick={handleEdit}>
              <Pencil className="h-4 w-4 mr-1" />
              编辑模板
            </Button>
            <Button variant="outline" onClick={handleViewInstances}>
              <Eye className="h-4 w-4 mr-1" />
              查看实例
            </Button>
          </div>
          <Button variant="ghost" onClick={onClose}>
            关闭
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ReminderTemplateCard;

// packages/app-vue/src/modules/reminder/components/ReminderTemplateCard.vue
<template>
  <Dialog :open="visible" @update:open="handleVisibleChange">
    <DialogContent
      data-testid="reminder-template-detail"
      class="flex max-h-[85vh] min-h-0 max-w-2xl flex-col overflow-hidden p-0"
    >
      <DialogHeader class="shrink-0 px-6 pt-6 pb-4">
        <div class="flex items-center gap-2">
          <component :is="getTemplateIcon()" class="h-6 w-6 text-primary" />
          <DialogTitle data-testid="reminder-template-detail-title">{{
            template?.name || t('reminder.templateDetail.fallbackTitle')
          }}</DialogTitle>
        </div>
        <DialogDescription class="text-sm text-muted-foreground">
          {{ t('reminder.templateDetail.description') }}
        </DialogDescription>
        <div class="flex items-center gap-2 mt-2">
          <Badge :variant="template?.effectiveEnabled ? 'default' : 'secondary'">
            {{ scheduleStateLabel }}
          </Badge>
          <Badge v-if="template?.groupId" variant="outline">
            <Folder class="h-3 w-3 mr-1" />
            {{ template?.groupName || t('reminder.templateDetail.groupedFallback') }}
          </Badge>
          <Badge v-if="template?.lifecycleSource === 'group'" variant="outline">
            {{ t('reminder.templateDetail.badgeGroupControlled') }}
          </Badge>
          <Badge v-else-if="template?.lifecycleSource === 'global'" variant="secondary">{{
            t('reminder.templateDetail.badgeGlobalPaused')
          }}</Badge>
        </div>
      </DialogHeader>

      <div class="min-h-0 flex-1 overflow-y-auto px-6 pb-4">
        <div v-if="template" class="space-y-6 py-2">
          <div class="space-y-3" data-testid="reminder-detail-schedule">
            <h3 class="flex items-center gap-2 text-sm font-semibold">
              <CalendarClock class="h-4 w-4" />
              {{ t('reminder.schedule.trigger') }}
            </h3>
            <Separator />
            <div class="grid gap-3 sm:grid-cols-3">
              <Card class="p-3">
                <p class="text-xs text-muted-foreground">{{ t('reminder.schedule.trigger') }}</p>
                <p class="mt-1 font-semibold">{{ triggerLabel }}</p>
              </Card>
              <Card class="p-3">
                <p class="text-xs text-muted-foreground">
                  {{ t('reminder.schedule.nextTrigger') }}
                </p>
                <p class="mt-1 font-semibold">{{ nextTriggerLabel }}</p>
              </Card>
              <Card class="p-3">
                <p class="text-xs text-muted-foreground">{{ t('reminder.schedule.recurrence') }}</p>
                <p class="mt-1 font-semibold">{{ recurrenceLabel }}</p>
              </Card>
            </div>
          </div>

          <!-- Basic Info -->
          <div class="space-y-3">
            <h3 class="text-sm font-semibold flex items-center gap-2">
              <Info class="h-4 w-4" />
              {{ t('reminder.templateDetail.sectionBasicInfo') }}
            </h3>
            <Separator />

            <div class="space-y-3">
              <div class="flex items-start gap-3">
                <FileText class="h-5 w-5 text-muted-foreground mt-0.5" />
                <div class="flex-1">
                  <p class="text-sm font-medium">{{ t('reminder.templateDetail.fieldTitle') }}</p>
                  <p class="text-sm text-muted-foreground">{{ template.name }}</p>
                </div>
              </div>

              <div v-if="template.description" class="flex items-start gap-3">
                <AlignLeft class="h-5 w-5 text-muted-foreground mt-0.5" />
                <div class="flex-1">
                  <p class="text-sm font-medium">
                    {{ t('reminder.templateDetail.fieldDescription') }}
                  </p>
                  <p class="text-sm text-muted-foreground">{{ template.description }}</p>
                </div>
              </div>

            </div>
          </div>

          <!-- Statistics -->
          <div class="space-y-3">
            <h3 class="text-sm font-semibold flex items-center gap-2">
              <BarChart3 class="h-4 w-4" />
              {{ t('reminder.templateDetail.sectionStats') }}
            </h3>
            <Separator />

            <div class="grid grid-cols-3 gap-4">
              <Card class="p-4 text-center">
                <div class="text-2xl font-bold text-primary">{{ stats.total }}</div>
                <div class="text-xs text-muted-foreground">
                  {{ t('reminder.templateDetail.statTotal') }}
                </div>
              </Card>
              <Card class="p-4 text-center">
                <div class="text-2xl font-bold text-success">{{ stats.completed }}</div>
                <div class="text-xs text-muted-foreground">
                  {{ t('reminder.templateDetail.statCompleted') }}
                </div>
              </Card>
              <Card class="p-4 text-center">
                <div class="text-2xl font-bold text-warning">{{ stats.pending }}</div>
                <div class="text-xs text-muted-foreground">
                  {{ t('reminder.templateDetail.statPending') }}
                </div>
              </Card>
            </div>
          </div>

          <!-- Time Info -->
          <div class="space-y-3">
            <h3 class="text-sm font-semibold flex items-center gap-2">
              <Calendar class="h-4 w-4" />
              {{ t('reminder.templateDetail.sectionTimeInfo') }}
            </h3>
            <Separator />

            <div class="space-y-3">
              <div class="flex items-start gap-3">
                <CalendarPlus class="h-5 w-5 text-muted-foreground mt-0.5" />
                <div class="flex-1">
                  <p class="text-sm font-medium">
                    {{ t('reminder.templateDetail.fieldCreatedAt') }}
                  </p>
                  <p class="text-sm text-muted-foreground">
                    {{ formatDate(template.createdAt) }}
                  </p>
                </div>
              </div>

              <div class="flex items-start gap-3">
                <CalendarCheck class="h-5 w-5 text-muted-foreground mt-0.5" />
                <div class="flex-1">
                  <p class="text-sm font-medium">
                    {{ t('reminder.templateDetail.fieldUpdatedAt') }}
                  </p>
                  <p class="text-sm text-muted-foreground">
                    {{ formatDate(template.updatedAt) }}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <!-- Status Toggle -->
          <div class="flex items-center justify-between rounded-lg border p-4">
            <div class="flex items-center gap-3">
              <Power
                :class="[
                  'h-5 w-5',
                  template.effectiveEnabled ? 'text-success' : 'text-muted-foreground',
                ]"
              />
              <div>
                <p class="text-sm font-medium">
                  {{ t('reminder.templateDetail.selfSwitchTitle') }}
                </p>
                <p class="text-xs text-muted-foreground">
                  {{ selfSwitchLabel }}
                </p>
                <p class="text-xs text-muted-foreground mt-1">
                  {{
                    t('reminder.templateDetail.effectiveStatusLine', {
                      status: effectiveStatusLabel,
                    })
                  }}
                </p>
              </div>
            </div>
            <Switch
              :checked="template.selfEnabled"
              :disabled="isTogglingStatus"
              @update:checked="handleToggleStatus"
            />
          </div>

          <div
            v-if="template.lifecycleSource !== 'template'"
            class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"
          >
            <p class="font-medium">{{ t('reminder.templateDetail.overrideTitle') }}</p>
            <p class="mt-1 text-xs text-amber-800">
              {{
                t('reminder.templateDetail.overrideDescription', {
                  reason: template.effectiveEnabledReason,
                  controller:
                    template.lifecycleSource === 'global'
                      ? t('reminder.templateDetail.overrideControllerGlobal')
                      : t('reminder.templateDetail.overrideControllerGroup'),
                })
              }}
            </p>
          </div>

          <div class="space-y-3">
            <h3 class="text-sm font-semibold flex items-center gap-2">
              <Power class="h-4 w-4" />
              {{ t('reminder.templateDetail.sectionLifecycle') }}
            </h3>
            <Separator />

            <div class="grid grid-cols-2 gap-3 text-sm">
              <Card class="p-3">
                <p class="font-medium">{{ t('reminder.templateDetail.selfSwitchTitle') }}</p>
                <p class="text-muted-foreground mt-1">
                  {{ selfSwitchShortLabel }}
                </p>
              </Card>
              <Card class="p-3">
                <p class="font-medium">{{ t('reminder.templateDetail.fieldEffectiveResult') }}</p>
                <p class="text-muted-foreground mt-1">
                  {{ effectiveResultLabel }}
                </p>
              </Card>
              <Card class="p-3">
                <p class="font-medium">{{ t('reminder.templateDetail.fieldGlobalSwitch') }}</p>
                <p class="text-muted-foreground mt-1">
                  {{ globalSwitchLabel }}
                </p>
              </Card>
              <Card class="p-3">
                <p class="font-medium">{{ t('reminder.templateDetail.fieldGroupControlMode') }}</p>
                <p class="text-muted-foreground mt-1">
                  {{ groupControlModeLabel }}
                </p>
              </Card>
              <Card class="p-3">
                <p class="font-medium">{{ t('reminder.templateDetail.fieldGroupSwitch') }}</p>
                <p class="text-muted-foreground mt-1">
                  {{ groupSwitchLabel }}
                </p>
              </Card>
            </div>
          </div>
        </div>
      </div>

      <DialogFooter class="shrink-0 border-t p-6 pt-4">
        <Button variant="default" @click="handleEdit">
          <Pencil class="h-4 w-4 mr-2" />
          {{ t('reminder.templateDetail.actionEdit') }}
        </Button>
        <Button variant="outline" @click="handleViewInstances">
          <Eye class="h-4 w-4 mr-2" />
          {{ t('reminder.templateDetail.actionViewInstances') }}
        </Button>
        <Button variant="ghost" @click="close">{{ t('common.close') }}</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { format } from 'date-fns';
import { useI18n } from 'vue-i18n';
import type { ReminderTemplateClientDTO } from '@dailyuse/contracts/reminder';
import {
  Bell,
  Info,
  FileText,
  AlignLeft,
  BarChart3,
  Calendar,
  CalendarPlus,
  CalendarCheck,
  CalendarClock,
  Power,
  Pencil,
  Eye,
  Folder,
} from '@lucide/vue';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-vue-shadcn';
import { Badge } from '@dailyuse/ui-vue-shadcn';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { Card } from '@dailyuse/ui-vue-shadcn';
import { Switch } from '@dailyuse/ui-vue-shadcn';
import { Separator } from '@dailyuse/ui-vue-shadcn';
import {
  getGlobalSwitchLabel,
  getGroupControlModeLabel,
  getGroupSwitchLabel,
  getTemplateEffectiveResultLabel,
  getTemplateEffectiveStatusLabel,
  getTemplateNextTriggerLabel,
  getTemplateRecurrenceLabel,
  getTemplateScheduleStateLabel,
  getTemplateTriggerLabel,
  getTemplateSelfSwitchLabel,
  getTemplateSelfSwitchShortLabel,
} from '../presentation/lifecycle-presentation';

const props = defineProps<{
  template?: ReminderTemplateClientDTO | null;
}>();

const emit = defineEmits<{
  'edit-template': [template: ReminderTemplateClientDTO];
  'view-instances': [templateId: string];
  'status-changed': [template: ReminderTemplateClientDTO, enabled: boolean];
}>();

const { locale, t } = useI18n();
const visible = ref(false);
const isTogglingStatus = ref(false);

// Mock stats - would come from API
const stats = computed(() => ({
  total: 0,
  completed: 0,
  pending: 0,
}));

const selfSwitchLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getTemplateSelfSwitchLabel(t, props.template);
});

const selfSwitchShortLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getTemplateSelfSwitchShortLabel(t, props.template);
});

const effectiveStatusLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getTemplateEffectiveStatusLabel(t, props.template);
});

const effectiveResultLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getTemplateEffectiveResultLabel(t, props.template);
});

const triggerLabel = computed(() => {
  if (!props.template) return t('reminder.templateDetail.notConfigured');
  return getTemplateTriggerLabel(t, props.template);
});

const nextTriggerLabel = computed(() => {
  if (!props.template) return t('reminder.schedule.noNextTrigger');
  return getTemplateNextTriggerLabel(t, props.template, locale.value);
});

const recurrenceLabel = computed(() => {
  if (!props.template) return t('reminder.schedule.notConfigured');
  return getTemplateRecurrenceLabel(t, props.template);
});

const scheduleStateLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getTemplateScheduleStateLabel(t, props.template);
});

const globalSwitchLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getGlobalSwitchLabel(t, props.template);
});

const groupControlModeLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getGroupControlModeLabel(t, props.template);
});

const groupSwitchLabel = computed(() => {
  if (!props.template) return t('common.unknown');
  return getGroupSwitchLabel(t, props.template);
});

const open = () => {
  visible.value = true;
};

const close = () => {
  visible.value = false;
};

const handleVisibleChange = (value: boolean) => {
  visible.value = value;
};

const handleToggleStatus = async (enabled: boolean) => {
  if (!props.template) return;

  isTogglingStatus.value = true;
  try {
    emit('status-changed', props.template, enabled);
  } finally {
    isTogglingStatus.value = false;
  }
};

const handleEdit = () => {
  if (props.template) {
    emit('edit-template', props.template);
    close();
  }
};

const handleViewInstances = () => {
  if (props.template) {
    emit('view-instances', props.template.id);
    close();
  }
};

const getTemplateIcon = () => {
  return Bell;
};

const formatDate = (timestamp: number | undefined): string => {
  if (!timestamp) return t('common.unknown');
  try {
    return format(new Date(timestamp), 'yyyy-MM-dd HH:mm:ss');
  } catch {
    return t('reminder.templateDetail.invalidTime');
  }
};

defineExpose({
  open,
  close,
});
</script>
