// packages/ui-vue/src/components/task/TaskInstanceCard.vue
<template>
  <div
    :class="[
      'flex items-center gap-3 p-4 min-h-[64px] transition-all duration-200 hover:bg-muted/50 group',
      { 'border-b border-border': showBorder, 'opacity-60': isCompleted }
    ]"
  >
    <!-- Completion Checkbox/Button -->
    <Button
      variant="ghost"
      size="icon"
      class="h-5 w-5 shrink-0 rounded-full p-0 hover:bg-transparent text-muted-foreground hover:text-primary transition-colors"
      @click="toggleComplete"
    >
      <CheckCircle2 v-if="isCompleted" class="h-5 w-5 text-primary" />
      <Circle v-else class="h-5 w-5" />
    </Button>

    <div class="flex-1 min-w-0 flex flex-col justify-center gap-0.5">
      <!-- Title -->
      <h3
        :class="[
          'text-sm font-medium leading-normal truncate transition-colors',
          { 'line-through text-muted-foreground': isCompleted, 'text-foreground': !isCompleted }
        ]"
      >
        {{ taskTitle }}
      </h3>

      <!-- Metadata -->
      <div class="flex items-center gap-2 text-xs text-muted-foreground">
        <component :is="isCompleted ? Check : Clock" class="h-3 w-3" />
        <span v-if="!isCompleted">{{ timeLabel }}</span>
        <span v-else>Completed at {{ formatCompletionTime }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { format } from 'date-fns';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { CheckCircle2, Circle, Clock, Check } from 'lucide-vue-next';
import type { TaskInstanceViewModel } from './types';

// Props
interface Props {
  task: TaskInstanceViewModel;
  showBorder?: boolean;
  taskTitle?: string;
}

const props = withDefaults(defineProps<Props>(), {
  showBorder: true,
});

// Emits
const emit = defineEmits<{
  complete: [uuid: string];
  undo: [uuid: string];
}>();

// Store - TODO: Connect to new domain model
// const taskStore = useTaskStore();

// Computed
const isCompleted = computed(() => props.task.isCompleted);

const taskTitle = computed(() => {
  return props.taskTitle || props.task.templateTitle || '任务';
});

const formatCompletionTime = computed(() => {
  return props.task.actualEndTime ? format(new Date(props.task.actualEndTime), 'HH:mm') : '';
});

const timeLabel = computed(() => {
  const timeConfig = props.task.timeConfig;

  if (timeConfig?.timeType === 'ALL_DAY') {
    return 'All Day';
  }

  if (timeConfig?.timeType === 'TIME_POINT' && timeConfig.timePoint !== null) {
    const hours = Math.floor(timeConfig.timePoint / 60);
    const minutes = timeConfig.timePoint % 60;
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}`;
  }

  if (timeConfig?.timeType === 'TIME_RANGE' && timeConfig.timeRange) {
    const startHours = Math.floor(timeConfig.timeRange.start / 60);
    const startMinutes = timeConfig.timeRange.start % 60;
    const endHours = Math.floor(timeConfig.timeRange.end / 60);
    const endMinutes = timeConfig.timeRange.end % 60;

    return `${startHours.toString().padStart(2, '0')}:${startMinutes.toString().padStart(2, '0')} - ${endHours.toString().padStart(2, '0')}:${endMinutes.toString().padStart(2, '0')}`;
  }

  return 'All Day';
});

const toggleComplete = () => {
  if (isCompleted.value) {
    emit('undo', props.task.uuid);
    return;
  }
  emit('complete', props.task.uuid);
};
</script>

// apps/desktop/src/renderer/modules/task/presentation/components/cards/TaskInstanceCard.tsx
/**
 * TaskInstanceCard Component
 *
 * 任务实例卡片 - 显示单个任务实例的状态和操作
 * 
 * EPIC-015 重构: 使用 Entity 类型
 */

import { useState } from 'react';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import type { TaskInstance, TaskTemplate } from '@dailyuse/task/domain-client';
import { Badge } from '@dailyuse/ui-react-shadcn';
import { Button } from '@dailyuse/ui-react-shadcn';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@dailyuse/ui-react-shadcn';
import {
  Check,
  CheckCircle,
  Circle,
  Clock,
  MoreHorizontal,
  SkipForward,
  X,
} from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@dailyuse/ui-react-shadcn';

interface TaskInstanceCardProps {
  instance: TaskInstance;
  template?: TaskTemplate | null;
  onComplete?: (uuid: string) => void;
  onSkip?: (uuid: string) => void;
  onClick?: (uuid: string) => void;
}

// 状态颜色配�?
const STATUS_COLORS: Record<string, { bg: string; text: string; icon: typeof Circle }> = {
  PENDING: { bg: 'bg-blue-100', text: 'text-blue-800', icon: Circle },
  COMPLETED: { bg: 'bg-green-100', text: 'text-green-800', icon: CheckCircle },
  SKIPPED: { bg: 'bg-yellow-100', text: 'text-yellow-800', icon: SkipForward },
  EXPIRED: { bg: 'bg-gray-100', text: 'text-gray-600', icon: X },
};

export function TaskInstanceCard({
  instance,
  template,
  onComplete,
  onSkip,
  onClick,
}: TaskInstanceCardProps) {
  const [isHovered, setIsHovered] = useState(false);

  const statusConfig = STATUS_COLORS[instance.status] || STATUS_COLORS.PENDING;
  const StatusIcon = statusConfig.icon;

  const handleComplete = (e: React.MouseEvent) => {
    e.stopPropagation();
    onComplete?.(instance.uuid);
  };

  const handleSkip = (e: React.MouseEvent) => {
    e.stopPropagation();
    onSkip?.(instance.uuid);
  };

  const handleClick = () => {
    onClick?.(instance.uuid);
  };

  // 格式化时间显�?
  const getTimeLabel = () => {
    const timeConfig = instance.timeConfig;

    if (timeConfig.timeType === 'ALL_DAY') {
      return '全天';
    }

    if (timeConfig.timeType === 'TIME_POINT' && timeConfig.timePoint != null) {
      const hours = Math.floor(timeConfig.timePoint / 60);
      const minutes = timeConfig.timePoint % 60;
      return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}`;
    }

    if (timeConfig.timeType === 'TIME_RANGE' && timeConfig.timeRange) {
      const startHours = Math.floor(timeConfig.timeRange.start / 60);
      const startMinutes = timeConfig.timeRange.start % 60;
      const endHours = Math.floor(timeConfig.timeRange.end / 60);
      const endMinutes = timeConfig.timeRange.end % 60;
      return `${startHours.toString().padStart(2, '0')}:${startMinutes.toString().padStart(2, '0')} - ${endHours.toString().padStart(2, '0')}:${endMinutes.toString().padStart(2, '0')}`;
    }

    return '全天';
  };

  return (
    <div
      className={`
        flex items-center gap-3 p-4 rounded-lg border bg-card transition-all cursor-pointer
        hover:shadow-md hover:border-primary/30
        ${instance.isCompleted ? 'opacity-70' : ''}
      `}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={handleClick}
    >
      {/* Complete Button / Status Icon */}
      <div className="shrink-0">
        {instance.isPending ? (
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  className="h-8 w-8 rounded-full hover:bg-green-100 hover:text-green-600"
                  onClick={handleComplete}
                >
                  <Circle className="h-5 w-5" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>完成任务</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        ) : (
          <div className={`h-8 w-8 rounded-full flex items-center justify-center ${statusConfig.bg}`}>
            <StatusIcon className={`h-5 w-5 ${statusConfig.text}`} />
          </div>
        )}
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0">
        <div className={`font-medium truncate ${instance.isCompleted ? 'line-through text-muted-foreground' : ''}`}>
          {template?.title || '未知任务'}
        </div>
        <div className="flex items-center gap-2 mt-1 text-sm text-muted-foreground">
          <Clock className="h-3.5 w-3.5" />
          <span>
            {instance.isCompleted
              ? `完成`${instance.actualEndTime ? format(instance.actualEndTime, 'HH:mm', { locale: zhCN }) : ''}`
              : getTimeLabel()}
          </span>
        </div>
      </div>

      {/* Status Badge */}
      <Badge className={`${statusConfig.bg} ${statusConfig.text} shrink-0`}>
        {instance.statusText}
      </Badge>

      {/* Actions (show on hover for pending tasks) */}
      {instance.isPending && (
        <div className={`flex items-center gap-1 transition-opacity ${isHovered ? 'opacity-100' : 'opacity-0'}`}>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost" className="h-8 w-8">
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={handleComplete}>
                <Check className="h-4 w-4 mr-2" />
                完成
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleSkip}>
                <SkipForward className="h-4 w-4 mr-2" />
                跳过
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      )}
    </div>
  );
}

export default TaskInstanceCard;
