// apps/desktop/src/renderer/modules/goal/presentation/components/GoalRecordCard.tsx
/**
 * GoalRecordCard Component
 *
 * 目标进度记录卡片组件 - 展示单条进度记录
 */

import type { GoalRecordClientDTO } from '@dailyuse/contracts/goal';
import { Card, CardContent } from '@dailyuse/ui-react-shadcn';
import { Badge } from '@dailyuse/ui-react-shadcn';
import { Button } from '@dailyuse/ui-react-shadcn';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@dailyuse/ui-react-shadcn';
import { Plus, Clock, FileText, Trash2 } from 'lucide-react';

interface GoalRecordCardProps {
  record: GoalRecordClientDTO;
  goalColor?: string;
  onDelete?: (recordId: string) => void;
  onClick?: (recordId: string) => void;
}

export function GoalRecordCard({
  record,
  goalColor = '#3b82f6',
  onDelete,
  onClick,
}: GoalRecordCardProps) {
  const handleCardClick = (e: React.MouseEvent) => {
    if ((e.target as HTMLElement).closest('button')) {
      return;
    }
    onClick?.(record.id);
  };

  const handleDelete = (e: React.MouseEvent) => {
    e.stopPropagation();
    onDelete?.(record.id);
  };

  return (
    <Card
      className="group transition-all duration-200 hover:shadow-md hover:-translate-y-0.5 hover:border-primary/30 cursor-pointer"
      onClick={handleCardClick}
    >
      <CardContent className="p-4">
        <div className="flex items-center gap-4">
          {/* 记录�?*/}
          <div className="flex items-center gap-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-full"
              style={{ backgroundColor: `${goalColor}20` }}
            >
              <Plus className="h-4 w-4" style={{ color: goalColor }} />
            </div>
            <div>
              <div className="text-lg font-bold">{record.value}</div>
              <div className="text-xs text-muted-foreground">本次记录</div>
            </div>
          </div>

          {/* 分隔�?*/}
          <div className="h-8 w-px bg-border" />

          {/* 记录时间 */}
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <Clock className="h-4 w-4 text-muted-foreground shrink-0" />
            <span className="text-sm text-muted-foreground truncate">
              {record.formattedRecordedAt}
            </span>
          </div>

          {/* 删除按钮 */}
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity text-destructive hover:text-destructive"
                  onClick={handleDelete}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>删除记录</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>

        {/* 备注信息 */}
        {record.note && (
          <div className="mt-3 pt-3 border-t">
            <div className="flex items-start gap-2">
              <FileText className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <p className="text-sm text-muted-foreground line-clamp-2">
                {record.note}
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default GoalRecordCard;

// packages/ui-vue-shadcn/src/components/custom/goal/GoalRecordCard.vue
<template>
  <Card class="group transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md hover:border-primary/30">
    <CardContent class="p-4">
      <div class="flex flex-col md:flex-row md:items-center gap-4">
        <!-- Record Value -->
        <div class="flex items-center flex-1">
          <div class="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary mr-3">
            <Plus class="h-4 w-4" />
          </div>
          <div>
            <div class="text-lg font-bold">{{ record.value }}</div>
            <div class="text-xs text-muted-foreground">本次记录值</div>
          </div>
        </div>

        <!-- Record Time -->
        <div class="flex items-center flex-1">
          <Clock class="h-4 w-4 text-muted-foreground mr-2" />
          <div class="text-sm">
            {{ record.formattedRecordedAt || formatDate(record.recordedAt) }}
          </div>
        </div>
      </div>

      <!-- Note -->
      <div v-if="record.note" class="mt-3 pt-3 border-t">
        <div class="flex items-start gap-2">
          <FileText class="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
          <div class="text-sm text-muted-foreground">
            {{ record.note }}
          </div>
        </div>
      </div>
    </CardContent>
  </Card>
</template>

<script setup lang="ts">
import { Card, CardContent } from '../../ui/card';
import { Plus, Clock, FileText } from 'lucide-vue-next';
import { format } from 'date-fns';
import type { GoalRecordClientDTO } from '@dailyuse/contracts/goal';

defineProps<{
  record: GoalRecordClientDTO;
}>();

function formatDate(date: string | number | Date): string {
  return format(new Date(date), 'yyyy/MM/dd HH:mm');
}
</script>
