// apps/desktop/src/renderer/modules/goal/presentation/components/GoalRecordCard.tsx
/**
 * GoalRecordCard Component
 *
 * 目标进度记录卡片组件 - 展示单条进度记录
 */

import type { GoalRecordClientDTO } from '@dailyuse/contracts/goal';
import { Card, CardContent } from '@dailyuse/ui-shadcn';
import { Badge } from '@dailyuse/ui-shadcn';
import { Button } from '@dailyuse/ui-shadcn';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@dailyuse/ui-shadcn';
import { Plus, Clock, FileText, Trash2 } from 'lucide-react';

interface GoalRecordCardProps {
  record: GoalRecordClientDTO;
  goalColor?: string;
  onDelete?: (recordUuid: string) => void;
  onClick?: (recordUuid: string) => void;
}

export function GoalRecordCard({
  record,
  goalColor = '#3b82f6',
  onDelete,
  onClick,
}: GoalRecordCardProps) {
  const handleCardClick = (e: React.MouseEvent) => {
    if ((e.target as HTMLElement).closest('button')) {
      return;
    }
    onClick?.(record.uuid);
  };

  const handleDelete = (e: React.MouseEvent) => {
    e.stopPropagation();
    onDelete?.(record.uuid);
  };

  return (
    <Card
      className="group transition-all duration-200 hover:shadow-md hover:-translate-y-0.5 hover:border-primary/30 cursor-pointer"
      onClick={handleCardClick}
    >
      <CardContent className="p-4">
        <div className="flex items-center gap-4">
          {/* 记录值 */}
          <div className="flex items-center gap-3">
            <div
              className="flex items-center justify-center w-8 h-8 rounded-full"
              style={{ backgroundColor: `${goalColor}20` }}
            >
              <Plus className="h-4 w-4" style={{ color: goalColor }} />
            </div>
            <div>
              <div className="text-lg font-bold">{record.value}</div>
              <div className="text-xs text-muted-foreground">本次记录值</div>
            </div>
          </div>

          {/* 分隔线 */}
          <div className="h-8 w-px bg-border" />

          {/* 记录时间 */}
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <Clock className="h-4 w-4 text-muted-foreground shrink-0" />
            <span className="text-sm text-muted-foreground truncate">
              {record.formattedRecordedAt}
            </span>
          </div>

          {/* 删除按钮 */}
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity text-destructive hover:text-destructive"
                  onClick={handleDelete}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>删除记录</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>

        {/* 备注信息 */}
        {record.note && (
          <div className="mt-3 pt-3 border-t">
            <div className="flex items-start gap-2">
              <FileText className="h-4 w-4 text-muted-foreground mt-0.5 shrink-0" />
              <p className="text-sm text-muted-foreground line-clamp-2">
                {record.note}
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default GoalRecordCard;

// apps/web/src/modules/goal/presentation/components/cards/GoalRecordCard.vue
<template>
  <v-card class="record-card" variant="outlined" elevation="0">
    <v-card-text class="pa-4">
      <v-row align="center" no-gutters>
        <!-- 记录值 -->
        <v-col cols="4">
          <div class="d-flex align-center">
            <v-avatar color="primary" variant="tonal" size="32" class="mr-3">
              <v-icon size="16">mdi-plus</v-icon>
            </v-avatar>
            <div>
              <div class="text-h6 font-weight-bold">{{ record.value }}</div>
              <div class="text-caption text-medium-emphasis">本次记录值</div>
            </div>
          </div>
        </v-col>

        <!-- 记录时间 -->
        <v-col cols="5">
          <div class="d-flex align-center">
            <v-icon color="medium-emphasis" size="16" class="mr-2"> mdi-clock-outline </v-icon>
            <div>
              {{ record.formattedRecordedAt || format(record.recordedAt, 'yyyy/MM/dd HH:mm') }}
            </div>
          </div>
        </v-col>
      </v-row>

      <!-- 备注信息 -->
      <div v-if="record.note" class="mt-3 pt-3 border-t">
        <div class="d-flex align-start">
          <v-icon color="medium-emphasis" size="16" class="mr-2 mt-1">
            mdi-note-text-outline
          </v-icon>
          <div class="text-body-2 text-medium-emphasis">
            {{ record.note }}
          </div>
        </div>
      </div>
    </v-card-text>
  </v-card>
</template>

<script setup lang="ts">
import type { GoalRecordClientDTO } from '@dailyuse/contracts/goal';
import { format } from 'date-fns';

defineProps<{
  record: GoalRecordClientDTO;
}>();
</script>

<style scoped>
.record-card {
  border-radius: 12px;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  border: 1px solid rgba(var(--v-theme-outline), 0.12);
  background: rgb(var(--v-theme-surface));
}

.record-card:hover {
  border-color: rgba(var(--v-theme-primary), 0.3);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transform: translateY(-1px);
}

.border-t {
  border-top: 1px solid rgba(var(--v-theme-outline), 0.12);
}

/* 响应式设计 */
@media (max-width: 600px) {
  .record-card .v-row {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }

  .record-card .v-col {
    width: 100%;
  }
}
</style>
