// apps/desktop/src/renderer/modules/schedule/presentation/components/dialogs/CreateScheduleDialog.tsx
/**
 * CreateScheduleDialog Component
 *
 * 创建日程事件对话�?
 * 功能�?
 * 1. 表单输入：标题、描述、时间、地�?
 * 2. 支持编辑模式
 * 3. 表单验证
 */

import { useState, useCallback, useEffect } from 'react';
import type { ScheduleClientDTO, CreateScheduleRequest, UpdateScheduleRequest } from '../../stores/scheduleStore';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-react-shadcn';
import { Button } from '@dailyuse/ui-react-shadcn';
import { Input } from '@dailyuse/ui-react-shadcn';
import { Textarea } from '@dailyuse/ui-react-shadcn';
import { Label } from '@dailyuse/ui-react-shadcn';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@dailyuse/ui-react-shadcn';
import { Calendar, Clock, MapPin, Users, X } from 'lucide-react';

// ===================== 接口定义 =====================

interface CreateScheduleDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  editingSchedule?: ScheduleClientDTO | null;
  isLoading?: boolean;
  onSubmit?: (data: CreateScheduleRequest | UpdateScheduleRequest) => void;
  onCancel?: () => void;
}

interface FormData {
  title: string;
  description: string;
  startDate: string;
  startTime: string;
  endDate: string;
  endTime: string;
  priority: number | null;
  location: string;
  attendees: string[];
}

// ===================== 初始�?=====================

const initialFormData: FormData = {
  title: '',
  description: '',
  startDate: '',
  startTime: '',
  endDate: '',
  endTime: '',
  priority: null,
  location: '',
  attendees: [],
};

const priorityOptions = [
  { label: '最高(1)', value: '1' },
  { label: '高(2)', value: '2' },
  { label: '中(3)', value: '3' },
  { label: '低(4)', value: '4' },
  { label: '最低(5)', value: '5' },
];

// ===================== 组件 =====================

export function CreateScheduleDialog({
  open,
  onOpenChange,
  editingSchedule,
  isLoading = false,
  onSubmit,
  onCancel,
}: CreateScheduleDialogProps) {
  const [formData, setFormData] = useState<FormData>(initialFormData);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const isEditing = !!editingSchedule;

  // 编辑模式时填充表�?
  useEffect(() => {
    if (editingSchedule) {
      const startDate = new Date(editingSchedule.startTime);
      const endDate = new Date(editingSchedule.endTime);

      setFormData({
        title: editingSchedule.title,
        description: editingSchedule.description || '',
        startDate: startDate.toISOString().split('T')[0],
        startTime: startDate.toTimeString().slice(0, 5),
        endDate: endDate.toISOString().split('T')[0],
        endTime: endDate.toTimeString().slice(0, 5),
        priority: editingSchedule.priority || null,
        location: editingSchedule.location || '',
        attendees: [...((editingSchedule as any).attendees || [])],
      });
    } else {
      setFormData(initialFormData);
    }
    setErrors({});
  }, [editingSchedule, open]);

  // 更新表单字段
  const updateField = useCallback((field: keyof FormData, value: string | number | null | string[]) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => ({ ...prev, [field]: '' }));
  }, []);

  // 表单验证
  const validate = useCallback((): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.title.trim()) {
      newErrors.title = '请输入标';
    } else if (formData.title.length > 200) {
      newErrors.title = '标题最'00个字';
    }

    if (!formData.startDate) {
      newErrors.startDate = '请选择开始日';
    }

    if (!formData.startTime) {
      newErrors.startTime = '请选择开始时';
    }

    if (!formData.endDate) {
      newErrors.endDate = '请选择结束日期';
    }

    if (!formData.endTime) {
      newErrors.endTime = '请选择结束时间';
    }

    // 检查结束时间是否晚于开始时�?
    if (formData.startDate && formData.startTime && formData.endDate && formData.endTime) {
      const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
      const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();
      if (endTimestamp <= startTimestamp) {
        newErrors.endTime = '结束时间必须晚于开始时';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [formData]);

  // 提交表单
  const handleSubmit = useCallback(() => {
    if (!validate()) return;

    const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
    const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();

    const data = {
      title: formData.title.trim(),
      description: formData.description.trim() || undefined,
      startTime: startTimestamp,
      endTime: endTimestamp,
      priority: formData.priority || undefined,
      location: formData.location.trim() || undefined,
      attendees: formData.attendees.length > 0 ? formData.attendees : undefined,
    };

    onSubmit?.(data);
  }, [formData, validate, onSubmit]);

  // 取消
  const handleCancel = useCallback(() => {
    setFormData(initialFormData);
    setErrors({});
    onCancel?.();
    onOpenChange(false);
  }, [onCancel, onOpenChange]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-full bg-primary/10">
              <Calendar className="h-5 w-5 text-primary" />
            </div>
            <DialogTitle>{isEditing ? '编辑日程事件' : '创建日程事件'}</DialogTitle>
          </div>
          <DialogDescription>
            {isEditing ? '修改日程事件信息' : '填写日程事件信息并创'}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* 标题 */}
          <div className="space-y-2">
            <Label htmlFor="title">标题 *</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => updateField('title', e.target.value)}
              placeholder="输入日程标题"
              maxLength={200}
              className={errors.title ? 'border-destructive' : ''}
            />
            {errors.title && <p className="text-xs text-destructive">{errors.title}</p>}
          </div>

          {/* 描述 */}
          <div className="space-y-2">
            <Label htmlFor="description">描述</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => updateField('description', e.target.value)}
              placeholder="输入日程描述"
              rows={3}
              maxLength={1000}
            />
          </div>

          {/* 时间选择 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="startDate">开始日值 *</Label>
              <Input
                id="startDate"
                type="date"
                value={formData.startDate}
                onChange={(e) => updateField('startDate', e.target.value)}
                className={errors.startDate ? 'border-destructive' : ''}
              />
              {errors.startDate && <p className="text-xs text-destructive">{errors.startDate}</p>}
            </div>
            <div className="space-y-2">
              <Label htmlFor="startTime">开始时值 *</Label>
              <Input
                id="startTime"
                type="time"
                value={formData.startTime}
                onChange={(e) => updateField('startTime', e.target.value)}
                className={errors.startTime ? 'border-destructive' : ''}
              />
              {errors.startTime && <p className="text-xs text-destructive">{errors.startTime}</p>}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="endDate">结束日期 *</Label>
              <Input
                id="endDate"
                type="date"
                value={formData.endDate}
                onChange={(e) => updateField('endDate', e.target.value)}
                className={errors.endDate ? 'border-destructive' : ''}
              />
              {errors.endDate && <p className="text-xs text-destructive">{errors.endDate}</p>}
            </div>
            <div className="space-y-2">
              <Label htmlFor="endTime">结束时间 *</Label>
              <Input
                id="endTime"
                type="time"
                value={formData.endTime}
                onChange={(e) => updateField('endTime', e.target.value)}
                className={errors.endTime ? 'border-destructive' : ''}
              />
              {errors.endTime && <p className="text-xs text-destructive">{errors.endTime}</p>}
            </div>
          </div>

          {/* 优先�?*/}
          <div className="space-y-2">
            <Label>优先</Label>
            <Select
              value={formData.priority?.toString() || ''}
              onValueChange={(value) => updateField('priority', value ? parseInt(value) : null)}
            >
              <SelectTrigger>
                <SelectValue placeholder="选择优先" />
              </SelectTrigger>
              <SelectContent>
                {priorityOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* 地点 */}
          <div className="space-y-2">
            <Label htmlFor="location" className="flex items-center gap-1">
              <MapPin className="h-4 w-4" />
              地点
            </Label>
            <Input
              id="location"
              value={formData.location}
              onChange={(e) => updateField('location', e.target.value)}
              placeholder="输入地点"
              maxLength={200}
            />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleCancel} disabled={isLoading}>
            取消
          </Button>
          <Button onClick={handleSubmit} disabled={isLoading}>
            {isLoading ? '处理中...' : isEditing ? '保存' : '创建'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default CreateScheduleDialog;

// packages/app-vue/src/modules/schedule/components/CreateScheduleDialog.vue
<template>
  <Dialog :open="modelValue" @update:open="$emit('update:modelValue', $event)">
    <DialogContent class="max-w-2xl">
      <DialogHeader>
        <DialogTitle>{{ isEditing ? '编辑日程事件' : '创建日程事件' }}</DialogTitle>
      </DialogHeader>

      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div class="space-y-4">
          <!-- 标题 -->
          <div>
            <Label for="title">标题 *</Label>
            <Input
              id="title"
              v-model="formData.title"
              placeholder="输入日程标题"
              maxlength="200"
              required
            />
            <p class="text-sm text-muted-foreground mt-1">{{ formData.title.length }}/200</p>
          </div>

          <!-- 描述 -->
          <div>
            <Label for="description">描述</Label>
            <Textarea
              id="description"
              v-model="formData.description"
              placeholder="输入描述信息"
              rows="3"
              maxlength="1000"
            />
            <p class="text-sm text-muted-foreground mt-1">{{ formData.description.length }}/1000</p>
          </div>

          <!-- 开始时间 -->
          <div class="grid grid-cols-2 gap-4">
            <div>
              <Label for="startDate">开始日期 *</Label>
              <Input
                id="startDate"
                v-model="formData.startDate"
                type="date"
                required
              />
            </div>
            <div>
              <Label for="startTime">开始时间 *</Label>
              <Input
                id="startTime"
                v-model="formData.startTime"
                type="time"
                required
              />
            </div>
          </div>

          <!-- 结束时间 -->
          <div class="grid grid-cols-2 gap-4">
            <div>
              <Label for="endDate">结束日期 *</Label>
              <Input
                id="endDate"
                v-model="formData.endDate"
                type="date"
                required
              />
            </div>
            <div>
              <Label for="endTime">结束时间 *</Label>
              <Input
                id="endTime"
                v-model="formData.endTime"
                type="time"
                required
              />
            </div>
          </div>

          <!-- 优先级 -->
          <div>
            <Label for="priority">优先级</Label>
            <Select v-model="formData.priority">
              <SelectTrigger>
                <SelectValue placeholder="选择优先级" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">最低 (1)</SelectItem>
                <SelectItem value="2">低 (2)</SelectItem>
                <SelectItem value="3">中 (3)</SelectItem>
                <SelectItem value="4">高 (4)</SelectItem>
                <SelectItem value="5">最高 (5)</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <!-- 地点 -->
          <div>
            <Label for="location">地点</Label>
            <div class="relative">
              <MapPin class="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
              <Input
                id="location"
                v-model="formData.location"
                placeholder="输入地点"
                class="pl-10"
                maxlength="200"
              />
            </div>
            <p class="text-sm text-muted-foreground mt-1">{{ formData.location.length }}/200</p>
          </div>

          <!-- 参与者 -->
          <div>
            <Label>参与者</Label>
            <div class="flex flex-wrap gap-2 mb-2">
              <Badge
                v-for="(attendee, index) in formData.attendees"
                :key="index"
                variant="secondary"
                class="gap-1"
              >
                {{ attendee }}
                <button
                  type="button"
                  @click="removeAttendee(index)"
                  class="hover:bg-destructive/20 rounded-full"
                >
                  <X class="h-3 w-3" />
                </button>
              </Badge>
            </div>
            <div class="flex gap-2">
              <Input
                v-model="newAttendee"
                placeholder="输入邮箱或用户名"
                @keydown.enter.prevent="addAttendee"
              />
              <Button type="button" variant="outline" size="sm" @click="addAttendee">
                添加
              </Button>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" @click="handleClose">
            取消
          </Button>
          <Button type="submit" :disabled="loading">
            <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
            {{ isEditing ? '保存' : '创建' }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@dailyuse/ui-vue-shadcn';
import { Input } from '@dailyuse/ui-vue-shadcn';
import { Textarea } from '@dailyuse/ui-vue-shadcn';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { Label } from '@dailyuse/ui-vue-shadcn';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@dailyuse/ui-vue-shadcn';
import { Badge } from '@dailyuse/ui-vue-shadcn';
import { MapPin, X, Loader2 } from 'lucide-vue-next';
import type { ScheduleJobClientDTO } from '@dailyuse/contracts/schedule';

interface Props {
  modelValue: boolean;
  schedule?: ScheduleJobClientDTO | null;
  loading?: boolean;
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void;
  (e: 'submit', data: any): void;
}

const props = withDefaults(defineProps<Props>(), {
  schedule: null,
  loading: false,
});

const emit = defineEmits<Emits>();

const isEditing = ref(false);
const newAttendee = ref('');

const formData = reactive({
  title: '',
  description: '',
  startDate: '',
  startTime: '',
  endDate: '',
  endTime: '',
  priority: '' as string,
  location: '',
  attendees: [] as string[],
});

function resetForm() {
  formData.title = '';
  formData.description = '';
  formData.startDate = '';
  formData.startTime = '';
  formData.endDate = '';
  formData.endTime = '';
  formData.priority = '';
  formData.location = '';
  formData.attendees = [];
  newAttendee.value = '';
}

function handleClose() {
  emit('update:modelValue', false);
  resetForm();
}

function addAttendee() {
  if (newAttendee.value.trim() && !formData.attendees.includes(newAttendee.value.trim())) {
    formData.attendees.push(newAttendee.value.trim());
    newAttendee.value = '';
  }
}

function removeAttendee(index: number) {
  formData.attendees.splice(index, 1);
}

function handleSubmit() {
  const startTimestamp = new Date(`${formData.startDate}T${formData.startTime}`).getTime();
  const endTimestamp = new Date(`${formData.endDate}T${formData.endTime}`).getTime();

  if (startTimestamp >= endTimestamp) {
    alert('结束时间必须晚于开始时间');
    return;
  }

  emit('submit', {
    title: formData.title,
    description: formData.description || undefined,
    startTime: startTimestamp,
    endTime: endTimestamp,
    duration: endTimestamp - startTimestamp,
    priority: formData.priority || undefined,
    location: formData.location || undefined,
    attendees: formData.attendees.length > 0 ? formData.attendees : undefined,
  });
}

watch(() => props.schedule, (schedule) => {
  if (schedule) {
    isEditing.value = true;
    formData.title = schedule.title;
    formData.description = schedule.description || '';
    formData.priority = String(schedule.priority || '');
    formData.location = schedule.location || '';
    formData.attendees = schedule.attendees ? [...schedule.attendees] : [];

    const startDate = new Date(schedule.startTime);
    const endDate = new Date(schedule.endTime);

    formData.startDate = startDate.toISOString().split('T')[0];
    formData.startTime = startDate.toTimeString().slice(0, 5);
    formData.endDate = endDate.toISOString().split('T')[0];
    formData.endTime = endDate.toTimeString().slice(0, 5);
  } else {
    isEditing.value = false;
    resetForm();
  }
}, { immediate: true });

watch(() => props.modelValue, (value) => {
  if (!value) {
    resetForm();
  } else if (!props.schedule) {
    const now = new Date();
    const oneHourLater = new Date(now.getTime() + 60 * 60 * 1000);

    formData.startDate = now.toISOString().split('T')[0];
    formData.startTime = now.toTimeString().slice(0, 5);
    formData.endDate = oneHourLater.toISOString().split('T')[0];
    formData.endTime = oneHourLater.toTimeString().slice(0, 5);
  }
});
</script>
