// apps/web/src/modules/reminder/presentation/components/ReminderInstanceSidebar.vue
<template>
  <v-navigation-drawer
    permanent
    location="right"
    width="380"
    class="reminder-instance-sidebar"
    elevation="1"
  >
    <!-- 标题栏 -->
    <v-toolbar flat color="primary" dark>
      <v-icon>mdi-bell-clock</v-icon>
      <v-toolbar-title class="ml-2">即将到来的提醒</v-toolbar-title>
      <v-spacer />
      <v-btn icon @click="refreshUpcoming" :loading="isLoading" size="small">
        <v-icon>mdi-refresh</v-icon>
      </v-btn>
      <v-btn icon @click="openSettings" size="small">
        <v-icon>mdi-cog</v-icon>
      </v-btn>
    </v-toolbar>

    <!-- 过滤器 -->
    <v-expand-transition>
      <v-card v-show="showFilters" flat class="pa-4 border-b">
        <v-row>
          <v-col cols="12">
            <v-select
              v-model="filters.days"
              label="时间范围"
              :items="[
                { value: 1, title: '今天' },
                { value: 3, title: '3天内' },
                { value: 7, title: '一周内' },
                { value: 30, title: '一个月内' },
              ]"
              variant="outlined"
              density="compact"
              @update:model-value="applyFilters"
            />
          </v-col>
          <v-col cols="12">
            <v-select
              v-model="filters.priorities"
              label="优先级"
              :items="[
                { value: 'urgent', title: '紧急' },
                { value: 'high', title: '高' },
                { value: 'normal', title: '普通' },
                { value: 'low', title: '低' },
              ]"
              multiple
              variant="outlined"
              density="compact"
              @update:model-value="applyFilters"
            />
          </v-col>
        </v-row>
      </v-card>
    </v-expand-transition>

    <!-- 统计信息 -->
    <v-card v-if="upcomingData" flat class="pa-4 border-b">
      <v-row>
        <v-col cols="4" class="text-center">
          <div class="text-h6 text-primary">{{ upcomingData.total || 0 }}</div>
          <div class="text-caption text-medium-emphasis">总数</div>
        </v-col>
        <v-col cols="4" class="text-center">
          <div class="text-h6 text-info">{{ todayCount }}</div>
          <div class="text-caption text-medium-emphasis">今天</div>
        </v-col>
        <v-col cols="4" class="text-center">
          <div class="text-h6 text-error">{{ overdueCount }}</div>
          <div class="text-caption text-medium-emphasis">逾期</div>
        </v-col>
      </v-row>
    </v-card>

    <!-- 提醒列表 -->
    <div class="flex-grow-1 overflow-y-auto">
      <!-- 加载状态 -->
      <div v-if="isLoading" class="pa-4">
        <v-skeleton-loader v-for="i in 3" :key="i" type="list-item-avatar-two-line" class="mb-2" />
      </div>

      <!-- 错误状态 -->
      <v-card v-else-if="error" flat class="pa-4 text-center">
        <v-icon size="48" color="error" class="mb-2">mdi-alert-circle</v-icon>
        <v-card-text>{{ error }}</v-card-text>
        <v-btn variant="outlined" @click="refreshUpcoming">重试</v-btn>
      </v-card>

      <!-- 空状态 -->
      <v-card v-else-if="groupedReminders.length === 0" flat class="pa-4 text-center">
        <v-icon size="48" color="disabled" class="mb-2">mdi-bell-off</v-icon>
        <v-card-text class="text-medium-emphasis">暂无即将到来的提醒</v-card-text>
      </v-card>

      <!-- 提醒列表 -->
      <div v-else>
        <div v-for="group in groupedReminders" :key="group.date">
          <!-- 日期分组头部 -->
          <v-list-subheader class="d-flex justify-space-between">
            <span>{{ formatGroupDate(group.date) }}</span>
            <v-chip size="small" variant="outlined">{{ group.reminders.length }}</v-chip>
          </v-list-subheader>

          <!-- 该日期的提醒列表 -->
          <v-list density="compact">
            <v-list-item
              v-for="reminder in group.reminders"
              :key="reminder.uuid"
              :class="getReminderClass(reminder)"
              @click="handleReminderClick(reminder)"
              class="reminder-item"
            >
              <!-- 优先级指示器 -->
              <template #prepend>
                <v-icon :color="getPriorityColor(reminder.priority)" size="small">
                  mdi-circle
                </v-icon>
              </template>

              <!-- 主要内容 -->
              <v-list-item-title class="text-wrap">
                {{ reminder.title || reminder.message }}
              </v-list-item-title>

              <v-list-item-subtitle v-if="reminder.message" class="text-wrap mt-1">
                {{ reminder.message }}
              </v-list-item-subtitle>

              <!-- 时间和标签 -->
              <div class="d-flex align-center justify-space-between mt-2">
                <v-chip
                  size="x-small"
                  :color="isOverdue(reminder.nextTriggerAt) ? 'error' : 'primary'"
                  variant="text"
                >
                  {{ formatTime(reminder.nextTriggerAt) }}
                </v-chip>

                <div v-if="reminder.metadata?.tags?.length" class="d-flex gap-1">
                  <v-chip
                    v-for="tag in reminder.metadata.tags.slice(0, 2)"
                    :key="tag"
                    size="x-small"
                    variant="outlined"
                  >
                    {{ tag }}
                  </v-chip>
                  <v-chip v-if="reminder.metadata.tags.length > 2" size="x-small" variant="text">
                    +{{ reminder.metadata.tags.length - 2 }}
                  </v-chip>
                </div>
              </div>

              <!-- 操作按钮 -->
              <!-- <template #append>
                <div class="reminder-actions">
                  <v-btn
                    icon
                    size="x-small"
                    variant="text"
                    @click.stop="snoozeReminder(reminder)"
                    title="延期"
                  >
                    <v-icon>mdi-clock-plus</v-icon>
                  </v-btn>
                  <v-btn
                    icon
                    size="x-small"
                    variant="text"
                    @click.stop="completeReminder(reminder)"
                    title="完成"
                  >
                    <v-icon>mdi-check</v-icon>
                  </v-btn>
                  <v-btn
                    icon
                    size="x-small"
                    variant="text"
                    @click.stop="dismissReminder(reminder)"
                    title="忽略"
                  >
                    <v-icon>mdi-close</v-icon>
                  </v-btn>
                </div>
              </template> -->
            </v-list-item>
          </v-list>

          <v-divider />
        </div>
      </div>
    </div>

    <!-- 底部操作 -->
    <v-card flat class="border-t pa-2">
      <div class="d-flex justify-space-between">
        <v-btn variant="text" size="small" @click="toggleFilters" prepend-icon="mdi-filter">
          过滤器
        </v-btn>
        <v-btn variant="text" size="small" @click="openAllReminders"> 查看全部 </v-btn>
      </div>
    </v-card>

    <!-- 设置弹窗 -->
    <v-dialog v-model="settingsOpen" max-width="400">
      <v-card>
        <v-card-title>
          <span class="text-h6">侧边栏设置</span>
        </v-card-title>

        <v-card-text>
          <v-row>
            <v-col cols="12">
              <v-select
                v-model="settings.defaultDays"
                label="默认显示天数"
                :items="[
                  { value: 1, title: '1天' },
                  { value: 3, title: '3天' },
                  { value: 7, title: '7天' },
                  { value: 30, title: '30天' },
                ]"
                variant="outlined"
              />
            </v-col>
            <v-col cols="12">
              <v-text-field
                v-model.number="settings.maxItems"
                label="最大显示数量"
                type="number"
                min="10"
                max="100"
                variant="outlined"
              />
            </v-col>
            <v-col cols="12">
              <v-select
                v-model="settings.refreshInterval"
                label="自动刷新间隔（秒）"
                :items="[
                  { value: 0, title: '关闭' },
                  { value: 30, title: '30秒' },
                  { value: 60, title: '1分钟' },
                  { value: 300, title: '5分钟' },
                ]"
                variant="outlined"
              />
            </v-col>
            <v-col cols="12">
              <v-checkbox v-model="settings.showCompleted" label="显示已完成的提醒" />
            </v-col>
          </v-row>
        </v-card-text>

        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="settingsOpen = false">取消</v-btn>
          <v-btn color="primary" @click="saveSettings">保存</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-navigation-drawer>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import type { ReminderContracts } from '@dailyuse/contracts';
import { useReminder } from '../composables/useReminder';
import { useRouter } from 'vue-router';
import { format, formatDistanceToNow, isToday, isPast, startOfDay } from 'date-fns';
import { zhCN } from 'date-fns/locale';

// ===== Props & Emits =====
interface Props {
  visible?: boolean;
  filters?: {
    days?: number;
    priorities?: string[];
    categories?: string[];
    tags?: string[];
  };
  settings?: {
    defaultDays?: number;
    maxItems?: number;
    refreshInterval?: number;
    showCompleted?: boolean;
  };
}

const props = withDefaults(defineProps<Props>(), {
  visible: true,
  filters: () => ({}),
  settings: () => ({}),
});

interface Emits {
  (e: 'reminder-click', reminder: any): void;
  (e: 'reminder-action', action: 'snooze' | 'complete' | 'dismiss', reminder: any): void;
  (e: 'filters-change', filters: any): void;
  (e: 'settings-change', settings: any): void;
}

const emit = defineEmits<Emits>();

// ===== Composables =====
const router = useRouter();
const { getUpcomingReminders, isLoading, error } = useReminder();

// ===== 响应式状态 =====
const showFilters = ref(false);
const settingsOpen = ref(false);
const upcomingData = ref<any>(null);

// 过滤器状态
const filters = ref({
  days: props.filters.days || 1, // 默认查看今天内的提醒
  priorities: props.filters.priorities || [],
  categories: props.filters.categories || [],
  tags: props.filters.tags || [],
});

// 设置状态
const settings = ref({
  defaultDays: props.settings.defaultDays || 7,
  maxItems: props.settings.maxItems || 50,
  refreshInterval: props.settings.refreshInterval || 60,
  showCompleted: props.settings.showCompleted || false,
});

// 自动刷新定时器
let refreshTimer: ReturnType<typeof setInterval> | null = null;

// ===== 计算属性 =====

/**
 * 分组的提醒实例
 */
const groupedReminders = computed(() => {
  if (!upcomingData.value?.reminders) return [];

  const groups = new Map<string, any[]>();

  upcomingData.value.reminders.forEach((reminder: any) => {
    // 使用 nextTriggerAt 而不是 scheduledTime
    const date = startOfDay(new Date(reminder.nextTriggerAt)).toISOString();
    if (!groups.has(date)) {
      groups.set(date, []);
    }
    groups.get(date)!.push(reminder);
  });

  return Array.from(groups.entries())
    .map(([date, reminders]) => ({
      date,
      reminders: reminders.sort(
        (a, b) => new Date(a.nextTriggerAt).getTime() - new Date(b.nextTriggerAt).getTime(),
      ),
    }))
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
});

/**
 * 今天的提醒数量
 */
const todayCount = computed(() => {
  if (!upcomingData.value?.reminders) return 0;
  return upcomingData.value.reminders.filter((reminder: any) =>
    isToday(new Date(reminder.nextTriggerAt)),
  ).length;
});

/**
 * 逾期的提醒数量
 */
const overdueCount = computed(() => {
  if (!upcomingData.value?.reminders) return 0;
  return upcomingData.value.reminders.filter((reminder: any) =>
    isPast(new Date(reminder.nextTriggerAt)),
  ).length;
});

// ===== 方法 =====

/**
 * 获取即将到来的提醒
 */
async function fetchUpcomingReminders(): Promise<void> {
  try {
    const response = await getUpcomingReminders({
      limit: settings.value.maxItems,
      days: filters.value.days,
    });
    // 将整个响应对象赋值，包含 reminders、total、fromDate、toDate 等属性
    upcomingData.value = response;
    console.log('📋 侧边栏获取到的提醒数据:', upcomingData.value);
  } catch (err: any) {
    console.error('获取即将到来的提醒失败:', err);
  }
}

/**
 * 刷新数据
 */
async function refreshUpcoming(): Promise<void> {
  await fetchUpcomingReminders();
}

/**
 * 应用过滤器
 */
async function applyFilters(): Promise<void> {
  emit('filters-change', filters.value);
  await fetchUpcomingReminders();
}

/**
 * 格式化分组日期
 */
function formatGroupDate(dateStr: string): string {
  const date = new Date(dateStr);
  if (isToday(date)) return '今天';
  return format(date, 'M月d日 EEEE', { locale: zhCN });
}

/**
 * 格式化时间
 */
function formatTime(timestamp: number): string {
  const date = new Date(timestamp);
  if (isPast(date)) {
    return `逾期 ${formatDistanceToNow(date, { locale: zhCN })}`;
  }
  return format(date, 'HH:mm');
}

/**
 * 检查是否逾期
 */
function isOverdue(timestamp: number): boolean {
  return isPast(new Date(timestamp));
}

/**
 * 获取提醒样式类
 */
function getReminderClass(reminder: any): string[] {
  const classes = [];

  if (isOverdue(reminder.nextTriggerAt)) {
    classes.push('overdue');
  }

  return classes;
}

/**
 * 获取优先级颜色
 */
function getPriorityColor(priority: string): string {
  const colors = {
    urgent: 'red',
    high: 'orange',
    normal: 'blue',
    low: 'grey',
  };
  return colors[priority as keyof typeof colors] || 'grey';
}

/**
 * 处理提醒点击
 */
function handleReminderClick(reminder: any): void {
  emit('reminder-click', reminder);
  router.push(`/reminders/templates/${reminder.templateUuid}/instances/${reminder.uuid}`);
}

// /**
//  * 延期提醒
//  */
// async function snoozeReminder(reminder: any): Promise<void> {
//   emit('reminder-action', 'snooze', reminder);
//   try {
//     await snoozeReminderAction(reminder.templateUuid, reminder.uuid, 300); // 延期5分钟
//     await refreshUpcoming();
//   } catch (err) {
//     console.error('延期提醒失败:', err);
//   }
// }

// /**
//  * 完成提醒
//  */
// async function completeReminder(reminder: any): Promise<void> {
//   emit('reminder-action', 'complete', reminder);
//   try {
//     await completeReminderAction(reminder.templateUuid, reminder.uuid);
//     await refreshUpcoming();
//   } catch (err) {
//     console.error('完成提醒失败:', err);
//   }
// }

// /**
//  * 忽略提醒
//  */
// async function dismissReminder(reminder: any): Promise<void> {
//   emit('reminder-action', 'dismiss', reminder);
//   try {
//     await dismissReminderAction(reminder.templateUuid, reminder.uuid);
//     await refreshUpcoming();
//   } catch (err) {
//     console.error('忽略提醒失败:', err);
//   }
// }

/**
 * 切换过滤器显示
 */
function toggleFilters(): void {
  showFilters.value = !showFilters.value;
}

/**
 * 打开设置
 */
function openSettings(): void {
  settingsOpen.value = true;
}

/**
 * 保存设置
 */
function saveSettings(): void {
  // 更新过滤器默认值
  filters.value.days = settings.value.defaultDays;

  // 重新设置自动刷新
  setupAutoRefresh();

  // 重新获取数据
  fetchUpcomingReminders();

  emit('settings-change', settings.value);
  settingsOpen.value = false;
}

/**
 * 查看全部提醒
 */
function openAllReminders(): void {
  router.push('/reminders');
}

/**
 * 设置自动刷新
 */
function setupAutoRefresh(): void {
  if (refreshTimer) {
    clearInterval(refreshTimer);
    refreshTimer = null;
  }

  if (settings.value.refreshInterval > 0) {
    refreshTimer = setInterval(() => {
      fetchUpcomingReminders();
    }, settings.value.refreshInterval * 1000);
  }
}

// ===== 生命周期 =====

onMounted(async () => {
  await fetchUpcomingReminders();
  setupAutoRefresh();
});

onUnmounted(() => {
  if (refreshTimer) {
    clearInterval(refreshTimer);
  }
});

// 监听设置变化
watch(() => settings.value.refreshInterval, setupAutoRefresh);
</script>

<style scoped>
.reminder-instance-sidebar {
  border-left: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
}

.reminder-item {
  transition: background-color 0.2s ease;
}

.reminder-item:hover {
  background-color: rgba(var(--v-theme-primary), 0.04);
}

.reminder-item.overdue {
  background-color: rgba(var(--v-theme-error), 0.08);
}

.reminder-actions {
  opacity: 0;
  transition: opacity 0.2s ease;
  display: flex;
  gap: 2px;
}

.reminder-item:hover .reminder-actions {
  opacity: 1;
}
</style>

// apps/desktop/src/renderer/modules/reminder/presentation/components/ReminderInstanceSidebar.tsx
/**
 * ReminderInstanceSidebar - 即将到来的提醒侧边栏
 *
 * 显示即将触发的提醒列表：
 * - 统计信息（总数、今天、逾期）
 * - 按日期分组的提醒列表
 * - 支持筛选和刷新
 * - 提醒操作（延期、完成、忽略）
 *
 * @module reminder/presentation/components
 */

import { useState, useCallback, useMemo } from 'react';
import {
  Button,
  Badge,
  Card,
  CardContent,
  Skeleton,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  ScrollArea,
  cn,
} from '@dailyuse/ui-shadcn';

import {
  Bell,
  RefreshCw,
  Settings,
  ChevronDown,
  AlertCircle,
  BellOff,
  Clock,
  CheckCircle,
  Filter,
} from 'lucide-react';
import { format, isToday, isBefore, startOfDay, parseISO, isValid } from 'date-fns';
import { zhCN } from 'date-fns/locale';

// ============ Types ============

export interface UpcomingReminder {
  uuid: string;
  title: string;
  message?: string;
  nextTriggerAt: string | Date;
  priority?: 'urgent' | 'high' | 'normal' | 'low';
  templateUuid?: string;
  metadata?: {
    tags?: string[];
  };
}

export interface GroupedReminders {
  date: string;
  reminders: UpcomingReminder[];
}

export interface UpcomingData {
  total: number;
  reminders: UpcomingReminder[];
}

export interface ReminderInstanceSidebarProps {
  /** 即将到来的提醒数据 */
  upcomingData?: UpcomingData | null;
  /** 加载状态 */
  isLoading?: boolean;
  /** 错误信息 */
  error?: string | null;
  /** 刷新回调 */
  onRefresh?: () => Promise<void>;
  /** 打开设置 */
  onOpenSettings?: () => void;
  /** 点击提醒 */
  onReminderClick?: (reminder: UpcomingReminder) => void;
  /** 延期提醒 */
  onSnooze?: (reminder: UpcomingReminder, minutes: number) => Promise<void>;
  /** 完成提醒 */
  onComplete?: (reminder: UpcomingReminder) => Promise<void>;
  /** 忽略提醒 */
  onDismiss?: (reminder: UpcomingReminder) => Promise<void>;
}

// ============ Utils ============

function parseDate(dateInput: string | Date): Date {
  if (dateInput instanceof Date) return dateInput;
  const parsed = parseISO(dateInput);
  return isValid(parsed) ? parsed : new Date();
}

function formatTime(dateInput: string | Date): string {
  const date = parseDate(dateInput);
  return format(date, 'HH:mm', { locale: zhCN });
}

function formatGroupDate(dateString: string): string {
  const date = parseISO(dateString);
  if (!isValid(date)) return dateString;
  
  if (isToday(date)) {
    return '今天';
  }
  
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  if (startOfDay(date).getTime() === startOfDay(tomorrow).getTime()) {
    return '明天';
  }
  
  return format(date, 'M月d日 EEEE', { locale: zhCN });
}

function isOverdue(dateInput: string | Date): boolean {
  const date = parseDate(dateInput);
  return isBefore(date, new Date());
}

function getPriorityColor(priority?: string): string {
  switch (priority) {
    case 'urgent': return 'text-red-500';
    case 'high': return 'text-orange-500';
    case 'normal': return 'text-blue-500';
    case 'low': return 'text-gray-400';
    default: return 'text-blue-500';
  }
}

// ============ Component ============

export function ReminderInstanceSidebar({
  upcomingData,
  isLoading = false,
  error,
  onRefresh,
  onOpenSettings,
  onReminderClick,
  onSnooze,
  onComplete,
  onDismiss,
}: ReminderInstanceSidebarProps) {
  const [showFilters, setShowFilters] = useState(false);
  const [filters, setFilters] = useState({
    days: 7,
    priorities: [] as string[],
  });
  const [isRefreshing, setIsRefreshing] = useState(false);

  // 按日期分组提醒
  const groupedReminders = useMemo((): GroupedReminders[] => {
    if (!upcomingData?.reminders) return [];

    const groups: Record<string, UpcomingReminder[]> = {};

    upcomingData.reminders.forEach((reminder) => {
      const date = parseDate(reminder.nextTriggerAt);
      const dateKey = format(date, 'yyyy-MM-dd');

      if (!groups[dateKey]) {
        groups[dateKey] = [];
      }
      groups[dateKey].push(reminder);
    });

    // 按日期排序
    return Object.entries(groups)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, reminders]) => ({
        date,
        reminders: reminders.sort((a, b) => {
          const dateA = parseDate(a.nextTriggerAt);
          const dateB = parseDate(b.nextTriggerAt);
          return dateA.getTime() - dateB.getTime();
        }),
      }));
  }, [upcomingData]);

  // 统计数据
  const todayCount = useMemo(() => {
    if (!upcomingData?.reminders) return 0;
    return upcomingData.reminders.filter(r => isToday(parseDate(r.nextTriggerAt))).length;
  }, [upcomingData]);

  const overdueCount = useMemo(() => {
    if (!upcomingData?.reminders) return 0;
    return upcomingData.reminders.filter(r => isOverdue(r.nextTriggerAt)).length;
  }, [upcomingData]);

  // 刷新
  const handleRefresh = useCallback(async () => {
    if (!onRefresh) return;
    setIsRefreshing(true);
    try {
      await onRefresh();
    } finally {
      setIsRefreshing(false);
    }
  }, [onRefresh]);

  // 点击提醒
  const handleReminderClick = useCallback((reminder: UpcomingReminder) => {
    onReminderClick?.(reminder);
  }, [onReminderClick]);

  return (
    <div className="w-[380px] h-full flex flex-col border-l bg-background">
      {/* 标题栏 */}
      <div className="flex items-center justify-between px-4 py-3 bg-primary text-primary-foreground">
        <div className="flex items-center gap-2">
          <Bell className="h-5 w-5" />
          <span className="font-semibold">即将到来的提醒</span>
        </div>
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8 text-primary-foreground hover:bg-primary-foreground/20"
            onClick={handleRefresh}
            disabled={isRefreshing || isLoading}
          >
            <RefreshCw className={cn("h-4 w-4", isRefreshing && "animate-spin")} />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8 text-primary-foreground hover:bg-primary-foreground/20"
            onClick={onOpenSettings}
          >
            <Settings className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* 筛选器 */}
      <Collapsible open={showFilters} onOpenChange={setShowFilters}>
        <CollapsibleTrigger asChild>
          <Button variant="ghost" className="w-full justify-between rounded-none border-b">
            <div className="flex items-center gap-2">
              <Filter className="h-4 w-4" />
              <span>筛选</span>
            </div>
            <ChevronDown className={cn("h-4 w-4 transition-transform", showFilters && "rotate-180")} />
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent className="p-4 border-b space-y-4">
          <div className="space-y-2">
            <label className="text-sm text-muted-foreground">时间范围</label>
            <Select
              value={String(filters.days)}
              onValueChange={(value) => setFilters(prev => ({ ...prev, days: Number(value) }))}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">今天</SelectItem>
                <SelectItem value="3">3天内</SelectItem>
                <SelectItem value="7">一周内</SelectItem>
                <SelectItem value="30">一个月内</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CollapsibleContent>
      </Collapsible>

      {/* 统计信息 */}
      {upcomingData && (
        <div className="grid grid-cols-3 gap-4 p-4 border-b">
          <div className="text-center">
            <p className="text-2xl font-bold text-primary">{upcomingData.total || 0}</p>
            <p className="text-xs text-muted-foreground">总数</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-blue-500">{todayCount}</p>
            <p className="text-xs text-muted-foreground">今天</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-bold text-red-500">{overdueCount}</p>
            <p className="text-xs text-muted-foreground">逾期</p>
          </div>
        </div>
      )}

      {/* 提醒列表 */}
      <ScrollArea className="flex-1">
        {/* 加载状态 */}
        {isLoading && (
          <div className="p-4 space-y-3">
            {[1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        )}

        {/* 错误状态 */}
        {!isLoading && error && (
          <div className="p-4 text-center">
            <AlertCircle className="h-12 w-12 text-destructive mx-auto mb-2" />
            <p className="text-sm text-muted-foreground mb-3">{error}</p>
            <Button variant="outline" size="sm" onClick={handleRefresh}>
              重试
            </Button>
          </div>
        )}

        {/* 空状态 */}
        {!isLoading && !error && groupedReminders.length === 0 && (
          <div className="p-4 text-center">
            <BellOff className="h-12 w-12 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">暂无即将到来的提醒</p>
          </div>
        )}

        {/* 提醒列表 */}
        {!isLoading && !error && groupedReminders.length > 0 && (
          <div className="divide-y">
            {groupedReminders.map((group) => (
              <div key={group.date}>
                {/* 日期分组头部 */}
                <div className="flex items-center justify-between px-4 py-2 bg-muted/50">
                  <span className="text-sm font-medium">{formatGroupDate(group.date)}</span>
                  <Badge variant="outline" className="text-xs">
                    {group.reminders.length}
                  </Badge>
                </div>

                {/* 该日期的提醒列表 */}
                <div className="divide-y divide-dashed">
                  {group.reminders.map((reminder) => (
                    <div
                      key={reminder.uuid}
                      className={cn(
                        "px-4 py-3 cursor-pointer hover:bg-accent/50 transition-colors",
                        isOverdue(reminder.nextTriggerAt) && "bg-red-50"
                      )}
                      onClick={() => handleReminderClick(reminder)}
                    >
                      <div className="flex items-start gap-2">
                        {/* 优先级指示器 */}
                        <div className={cn("mt-1.5 w-2 h-2 rounded-full", getPriorityColor(reminder.priority).replace('text-', 'bg-'))} />

                        {/* 主要内容 */}
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium truncate">
                            {reminder.title || reminder.message}
                          </p>
                          {reminder.message && reminder.title && (
                            <p className="text-xs text-muted-foreground line-clamp-2 mt-1">
                              {reminder.message}
                            </p>
                          )}

                          {/* 时间和标签 */}
                          <div className="flex items-center gap-2 mt-2">
                            <Badge
                              variant={isOverdue(reminder.nextTriggerAt) ? "destructive" : "secondary"}
                              className="text-xs"
                            >
                              <Clock className="h-3 w-3 mr-1" />
                              {formatTime(reminder.nextTriggerAt)}
                            </Badge>

                            {reminder.metadata?.tags?.slice(0, 2).map((tag) => (
                              <Badge key={tag} variant="outline" className="text-xs">
                                {tag}
                              </Badge>
                            ))}
                            {(reminder.metadata?.tags?.length ?? 0) > 2 && (
                              <span className="text-xs text-muted-foreground">
                                +{(reminder.metadata?.tags?.length ?? 0) - 2}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </ScrollArea>

      {/* 底部操作 */}
      <div className="p-3 border-t flex items-center justify-between">
        <Button variant="ghost" size="sm" onClick={() => setShowFilters(!showFilters)}>
          <Filter className="h-4 w-4 mr-1" />
          筛选
        </Button>
        <Button variant="ghost" size="sm" onClick={handleRefresh} disabled={isRefreshing}>
          <RefreshCw className={cn("h-4 w-4 mr-1", isRefreshing && "animate-spin")} />
          刷新
        </Button>
      </div>
    </div>
  );
}

export default ReminderInstanceSidebar;
