// packages/app-vue/src/modules/task/components/dialogs/TaskCompleteDialog.vue
<!--
  任务完成确认对话框
  
  功能：
  1. 显示任务信息
  2. 显示关联的 Goal/KeyResult 信息
  3. 根据 AggregationMethod 显示不同的输入提示
  4. 用户手动输入 Record 值
  5. 防止误触，提供二次确认
-->
<template>
  <Dialog
    :open="show"
    @update:open="
      (val: boolean) => {
        if (!val) cancel();
      }
    "
  >
    <DialogContent class="max-w-[600px]">
      <DialogHeader class="bg-green-600 -m-6 mb-0 p-4 rounded-t-lg">
        <DialogTitle class="flex items-center text-white">
          <CheckCircle class="h-5 w-5 mr-2 text-white" />
          完成任务
        </DialogTitle>
      </DialogHeader>

      <div class="pt-4 space-y-4">
        <!-- 任务信息 -->
        <div class="p-3 bg-muted/30 rounded-lg">
          <h3 class="text-lg font-semibold mb-1">{{ taskTitle }}</h3>
          <p class="text-xs text-muted-foreground flex items-center gap-1">
            <Calendar class="h-3 w-3" />
            {{ formatDate(instanceDate) }}
          </p>
        </div>

        <!-- 关联的目标信息 -->
        <Alert v-if="goalBinding" class="border-l-4 border-l-blue-500">
          <AlertDescription>
            <div class="flex flex-col gap-2">
              <div class="flex items-center">
                <Target class="h-4 w-4 mr-2 shrink-0" />
                <strong class="mr-2">关联目标：</strong>
                <span>{{ goalBinding.goalTitle }}</span>
              </div>
              <div class="flex items-center">
                <Key class="h-4 w-4 mr-2 shrink-0" />
                <strong class="mr-2">关键结果：</strong>
                <span>{{ goalBinding.keyResultTitle }}</span>
              </div>
              <div class="flex items-center">
                <Calculator class="h-4 w-4 mr-2 shrink-0" />
                <strong class="mr-2">计算方式：</strong>
                <Badge
                  :class="getAggregationMethodBadgeClass(goalBinding.aggregationMethod)"
                  class="text-xs"
                >
                  {{ getAggregationMethodText(goalBinding.aggregationMethod) }}
                </Badge>
              </div>

              <!-- 当前进度详情 -->
              <Separator class="my-2" />
              <div class="flex flex-col gap-1">
                <div class="flex justify-between items-center">
                  <div class="flex items-center">
                    <CheckCircle class="h-4 w-4 mr-2" />
                    <strong>当前进度</strong>
                  </div>
                  <Badge
                    :class="
                      getProgressBadgeClass(goalBinding.currentValue, goalBinding.targetValue)
                    "
                    class="text-xs"
                  >
                    {{ calculatePercentage(goalBinding.currentValue, goalBinding.targetValue) }}%
                  </Badge>
                </div>

                <div class="flex justify-between items-center text-sm">
                  <span class="text-muted-foreground">当前值：</span>
                  <strong>{{ goalBinding.currentValue }} {{ goalBinding.unit || '' }}</strong>
                </div>

                <div class="flex justify-between items-center text-sm">
                  <span class="text-muted-foreground">目标值：</span>
                  <strong>{{ goalBinding.targetValue }} {{ goalBinding.unit || '' }}</strong>
                </div>

                <div class="flex justify-between items-center text-sm">
                  <span class="text-muted-foreground">还需完成：</span>
                  <strong
                    :class="getRemainingClass(goalBinding.currentValue, goalBinding.targetValue)"
                  >
                    {{ Math.max(0, goalBinding.targetValue - goalBinding.currentValue) }}
                    {{ goalBinding.unit || '' }}
                  </strong>
                </div>

                <!-- 进度条 -->
                <Progress
                  :model-value="
                    calculatePercentage(goalBinding.currentValue, goalBinding.targetValue)
                  "
                  class="mt-2 h-2"
                />
              </div>
            </div>
          </AlertDescription>
        </Alert>

        <!-- 输入本次完成值（仅在有 Goal 绑定时显示） -->
        <div v-if="goalBinding" class="space-y-3">
          <div class="space-y-2">
            <Label :for="'record-value'">{{ getInputLabel(goalBinding.aggregationMethod) }}</Label>
            <div class="relative">
              <div class="absolute left-3 top-1/2 -translate-y-1/2">
                <component
                  :is="getAggregationMethodIconComponent(goalBinding.aggregationMethod)"
                  class="h-4 w-4"
                  :class="
                    recordValue !== null && recordValue > 0
                      ? 'text-green-500'
                      : 'text-muted-foreground'
                  "
                />
              </div>
              <Input
                id="record-value"
                v-model.number="recordValue"
                type="number"
                :step="getInputStep(goalBinding.aggregationMethod)"
                :min="0"
                class="pl-10"
                :class="goalBinding.unit ? 'pr-16' : ''"
                autofocus
              />
              <div
                v-if="goalBinding.unit"
                class="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground"
              >
                {{ goalBinding.unit }}
              </div>
            </div>
            <p class="text-xs text-muted-foreground">
              {{ getInputHint(goalBinding.aggregationMethod) }}
            </p>
          </div>

          <!-- 预测结果 -->
          <Alert
            v-if="recordValue !== null && recordValue > 0"
            class="bg-green-50 border-green-200"
          >
            <AlertDescription>
              <div class="text-xs">
                <strong>完成后预计：</strong>
                {{ predictProgress() }}
              </div>
            </AlertDescription>
          </Alert>

          <!-- 快捷值（可选） -->
          <div v-if="showQuickValues && quickValues.length > 0">
            <div class="text-xs text-muted-foreground mb-2">快捷值：</div>
            <div class="flex flex-wrap gap-2">
              <Badge
                v-for="value in quickValues"
                :key="value"
                :variant="recordValue === value ? 'default' : 'outline'"
                class="cursor-pointer text-xs"
                @click="recordValue = value"
              >
                {{ value }} {{ goalBinding.unit || '' }}
              </Badge>
            </div>
          </div>
        </div>

        <!-- 无 Goal 绑定时的提示 -->
        <Alert v-else class="bg-green-50 border-green-200">
          <AlertDescription>
            <div class="text-sm flex items-center gap-1">
              <Info class="h-4 w-4 shrink-0" />
              此任务未关联目标，点击确认后将直接完成。
            </div>
          </AlertDescription>
        </Alert>

        <!-- 完成备注（可选） -->
        <div class="space-y-2">
          <Label for="completion-note">完成备注（可选）</Label>
          <Textarea
            id="completion-note"
            v-model="note"
            placeholder="记录本次完成的情况..."
            :rows="3"
          />
        </div>

        <!-- 实际耗时（可选） -->
        <div class="space-y-2">
          <Label for="duration-input">实际耗时（可选）</Label>
          <div class="relative">
            <div class="absolute left-3 top-1/2 -translate-y-1/2">
              <Clock class="h-4 w-4 text-muted-foreground" />
            </div>
            <Input
              id="duration-input"
              v-model.number="duration"
              type="number"
              :min="0"
              :step="5"
              placeholder="记录实际花费的时间（分钟）"
              class="pl-10 pr-12"
            />
            <div class="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">
              分钟
            </div>
          </div>
        </div>
      </div>

      <DialogFooter class="pt-4">
        <Button variant="ghost" :disabled="isSubmitting" @click="cancel"> 取消 </Button>
        <Button
          :disabled="!isValid || isSubmitting"
          @click="confirm"
          class="bg-green-600 hover:bg-green-700"
        >
          <Loader2 v-if="isSubmitting" class="h-4 w-4 mr-1 animate-spin" />
          <Check v-else class="h-4 w-4 mr-1" />
          确认完成
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { format } from 'date-fns';
import {
  AggregationMethod,
  type GoalClientDTO,
  type KeyResultClientDTO,
} from '@dailyuse/contracts/goal';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  Alert,
  AlertDescription,
  Badge,
  Button,
  Input,
  Label,
  Textarea,
  Separator,
  Progress,
} from '@dailyuse/ui-vue-shadcn';
import {
  CheckCircle,
  Calendar,
  Target,
  Key,
  Calculator,
  Check,
  Info,
  Clock,
  Loader2,
  PlusCircle,
  ArrowUpCircle,
  TrendingUp,
  ArrowDownCircle,
  RefreshCw,
  Hash,
} from 'lucide-vue-next';

// ===================== 接口定义 =====================

interface GoalBinding {
  goalId: string;
  goalTitle: string;
  keyResultId: string;
  keyResultTitle: string;
  aggregationMethod: AggregationMethod;
  currentValue: number;
  targetValue: number;
  unit?: string;
}

interface Props {
  taskId: string;
  taskTitle: string;
  instanceDate: number | Date;
  goalBinding?: GoalBinding;
  showQuickValues?: boolean;
}

interface CompleteTaskData {
  recordValue?: number;
  note?: string;
  duration?: number;
}

const props = withDefaults(defineProps<Props>(), {
  showQuickValues: true,
});

const emit = defineEmits<{
  confirm: [data: CompleteTaskData];
  cancel: [];
}>();

// ===================== 响应式数据 =====================

const show = ref(true);
const recordValue = ref<number | null>(null);
const note = ref('');
const duration = ref<number | null>(null);
const isSubmitting = ref(false);

// ===================== 计算属性 =====================

// 根据历史数据或默认值生成快捷值
const quickValues = computed(() => {
  if (!props.goalBinding) return [];

  const { aggregationMethod, targetValue, currentValue } = props.goalBinding;

  switch (aggregationMethod) {
    case AggregationMethod.SUM:
      // 累加型：建议常用的增量值
      return [1, 5, 10, 20, 50];

    case AggregationMethod.MAX:
      // 最大值：建议接近目标的值
      const remaining = targetValue - currentValue;
      return [
        Math.floor(remaining * 0.5),
        Math.floor(remaining * 0.7),
        Math.floor(remaining * 0.9),
        remaining,
        targetValue,
      ].filter((v) => v > 0);

    case AggregationMethod.AVERAGE:
      // 平均值：建议目标值附近的值
      return [
        Math.floor(targetValue * 0.8),
        Math.floor(targetValue * 0.9),
        targetValue,
        Math.floor(targetValue * 1.1),
        Math.floor(targetValue * 1.2),
      ].filter((v) => v > 0);

    default:
      return [];
  }
});

// 根据 AggregationMethod 返回不同的标签
const getInputLabel = (method?: AggregationMethod) => {
  if (!props.goalBinding) {
    return '本次完成量';
  }

  switch (method) {
    case AggregationMethod.SUM:
      return '本次完成量（将累加到当前进度）';
    case AggregationMethod.MAX:
      return '本次达到的最高值';
    case AggregationMethod.AVERAGE:
      return '本次的值（将计算平均值）';
    case AggregationMethod.MIN:
      return '本次的最小值';
    case AggregationMethod.LAST:
      return '最新的值（将覆盖当前值）';
    default:
      return '本次完成量';
  }
};

// 输入提示
const getInputHint = (method?: AggregationMethod) => {
  if (!props.goalBinding) {
    return '请输入本次完成的数量';
  }

  const unit = props.goalBinding.unit || '单位';

  switch (method) {
    case AggregationMethod.SUM:
      return `例如：跑步 5 公里，输入 5`;
    case AggregationMethod.MAX:
      return `例如：考试分数 85 分，输入 85`;
    case AggregationMethod.AVERAGE:
      return `例如：每日学习 2 小时，输入 2`;
    case AggregationMethod.MIN:
      return `输入本次的最小值`;
    case AggregationMethod.LAST:
      return `输入最新的值`;
    default:
      return '';
  }
};

// 步长
const getInputStep = (method?: AggregationMethod) => {
  return 0.01;
};

// 图标组件
const getAggregationMethodIconComponent = (method?: AggregationMethod) => {
  switch (method) {
    case AggregationMethod.SUM:
      return PlusCircle;
    case AggregationMethod.MAX:
      return ArrowUpCircle;
    case AggregationMethod.AVERAGE:
      return TrendingUp;
    case AggregationMethod.MIN:
      return ArrowDownCircle;
    case AggregationMethod.LAST:
      return RefreshCw;
    default:
      return Hash;
  }
};

// Badge class for aggregation method
const getAggregationMethodBadgeClass = (method?: AggregationMethod) => {
  switch (method) {
    case AggregationMethod.SUM:
      return 'bg-blue-100 text-blue-800';
    case AggregationMethod.MAX:
      return 'bg-green-100 text-green-800';
    case AggregationMethod.AVERAGE:
      return 'bg-cyan-100 text-cyan-800';
    case AggregationMethod.MIN:
      return 'bg-yellow-100 text-yellow-800';
    case AggregationMethod.LAST:
      return 'bg-purple-100 text-purple-800';
    default:
      return 'bg-gray-100 text-gray-800';
  }
};

// 文本
const getAggregationMethodText = (method?: AggregationMethod) => {
  switch (method) {
    case AggregationMethod.SUM:
      return '累加型';
    case AggregationMethod.MAX:
      return '最大值';
    case AggregationMethod.AVERAGE:
      return '平均值';
    case AggregationMethod.MIN:
      return '最小值';
    case AggregationMethod.LAST:
      return '最新值';
    default:
      return '未知';
  }
};

// 校验
const validateRecordValue = () => {
  if (!props.goalBinding) {
    return true; // 没有绑定目标时不校验
  }

  if (recordValue.value === null || recordValue.value === undefined) {
    return '请输入完成值';
  }

  if (recordValue.value < 0) {
    return '值不能为负数';
  }

  return true;
};

const isValid = computed(() => {
  if (props.goalBinding) {
    // 有目标绑定时必须输入值
    return validateRecordValue() === true && recordValue.value !== null && recordValue.value > 0;
  }
  // 没有目标绑定时可以直接完成
  return true;
});

// 预测完成后的进度
const predictProgress = () => {
  if (!props.goalBinding || !recordValue.value) return '';

  const { aggregationMethod, currentValue, targetValue, unit } = props.goalBinding;
  let predictedValue = currentValue;

  switch (aggregationMethod) {
    case AggregationMethod.SUM:
      predictedValue = currentValue + recordValue.value;
      break;
    case AggregationMethod.MAX:
      predictedValue = Math.max(currentValue, recordValue.value);
      break;
    case AggregationMethod.LAST:
      predictedValue = recordValue.value;
      break;
    case AggregationMethod.AVERAGE:
      // 简化：假设只有一个记录，实际应该从后端获取记录数
      predictedValue = (currentValue + recordValue.value) / 2;
      break;
    default:
      predictedValue = currentValue + recordValue.value;
  }

  const percentage = calculatePercentage(predictedValue, targetValue);

  return `${predictedValue} / ${targetValue} ${unit || ''} (${percentage}%)`;
};

// 计算百分比
const calculatePercentage = (current: number, target: number) => {
  if (target === 0) return 0;
  return Math.min(Math.round((current / target) * 100), 100);
};

// 获取进度 Badge 样式
const getProgressBadgeClass = (current: number, target: number) => {
  const percentage = (current / target) * 100;
  if (percentage >= 100) return 'bg-green-100 text-green-800';
  if (percentage >= 70) return 'bg-blue-100 text-blue-800';
  if (percentage >= 40) return 'bg-yellow-100 text-yellow-800';
  return 'bg-red-100 text-red-800';
};

// 获取剩余量的样式类
const getRemainingClass = (current: number, target: number) => {
  const remaining = target - current;
  if (remaining <= 0) return 'text-green-600';
  if (remaining / target <= 0.3) return 'text-blue-600';
  if (remaining / target <= 0.6) return 'text-yellow-600';
  return 'text-red-600';
};

// 格式化日期
const formatDate = (date: number | Date) => {
  const dateObj = typeof date === 'number' ? new Date(date) : date;
  return format(dateObj, 'yyyy-MM-dd EEEE');
};

// ===================== 事件处理 =====================

const confirm = () => {
  if (!isValid.value || isSubmitting.value) return;

  isSubmitting.value = true;

  const data: CompleteTaskData = {
    note: note.value || undefined,
    duration: duration.value || undefined,
  };

  // 只有在有目标绑定且用户输入了值时才传递 recordValue
  if (props.goalBinding && recordValue.value !== null && recordValue.value > 0) {
    data.recordValue = recordValue.value;
  }

  emit('confirm', data);
  show.value = false;
};

const cancel = () => {
  emit('cancel');
  show.value = false;
};
</script>

// apps/desktop/src/renderer/modules/task/presentation/components/dialogs/TaskCompleteDialog.tsx
/**
 * TaskCompleteDialog Component
 *
 * 任务完成确认对话�?
 * 功能�?
 * 1. 显示任务信息
 * 2. 显示关联�?Goal/KeyResult 信息
 * 3. 根据 AggregationMethod 显示不同的输入提�?
 * 4. 用户手动输入 Record �?
 * 5. 防止误触，提供二次确�?
 */

import { useState, useCallback, useMemo } from 'react';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import { KeyResultCalculationMethod as AggregationMethod } from '@dailyuse/contracts/goal';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@dailyuse/ui-react-shadcn';
import { Button } from '@dailyuse/ui-react-shadcn';
import { Badge } from '@dailyuse/ui-react-shadcn';
import { Progress } from '@dailyuse/ui-react-shadcn';
import { Input } from '@dailyuse/ui-react-shadcn';
import { Textarea } from '@dailyuse/ui-react-shadcn';
import { Label } from '@dailyuse/ui-react-shadcn';
import { Alert, AlertDescription } from '@dailyuse/ui-react-shadcn';
import {
  CheckCircle,
  Target,
  Key,
  Calculator,
  Clock,
  FileText,
  Info,
  PlusCircle,
  ArrowUpCircle,
  TrendingUp,
  ArrowDownCircle,
  RefreshCw,
} from 'lucide-react';

// ===================== 接口定义 =====================

interface GoalBinding {
  goalId: string;
  goalTitle: string;
  keyResultId: string;
  keyResultTitle: string;
  aggregationMethod: AggregationMethod;
  currentValue: number;
  targetValue: number;
  unit?: string;
}

interface TaskCompleteDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  taskTitle: string;
  instanceDate: number | Date;
  goalBinding?: GoalBinding;
  showQuickValues?: boolean;
  isLoading?: boolean;
  onConfirm?: (data: CompleteTaskData) => void;
  onCancel?: () => void;
}

interface CompleteTaskData {
  recordValue?: number;
  note?: string;
  duration?: number;
}

// ===================== 工具函数 =====================

const getAggregationMethodText = (method?: AggregationMethod): string => {
  const textMap: Record<AggregationMethod, string> = {
    [AggregationMethod.Sum]: '累加',
    [AggregationMethod.Max]: '最大',
    [AggregationMethod.Average]: '平均',
    [AggregationMethod.Min]: '最小',
    [AggregationMethod.Last]: '最新',
  };
  return method ? textMap[method] || '未知' : '未知';
};

const getAggregationMethodColor = (method?: AggregationMethod): string => {
  const colorMap: Record<AggregationMethod, string> = {
    [AggregationMethod.Sum]: 'bg-blue-100 text-blue-800',
    [AggregationMethod.Max]: 'bg-green-100 text-green-800',
    [AggregationMethod.Average]: 'bg-cyan-100 text-cyan-800',
    [AggregationMethod.Min]: 'bg-yellow-100 text-yellow-800',
    [AggregationMethod.Last]: 'bg-purple-100 text-purple-800',
  };
  return method ? colorMap[method] || 'bg-gray-100 text-gray-800' : 'bg-gray-100 text-gray-800';
};

const getAggregationMethodIcon = (method?: AggregationMethod) => {
  switch (method) {
    case AggregationMethod.Sum:
      return <PlusCircle className="h-4 w-4" />;
    case AggregationMethod.Max:
      return <ArrowUpCircle className="h-4 w-4" />;
    case AggregationMethod.Average:
      return <TrendingUp className="h-4 w-4" />;
    case AggregationMethod.Min:
      return <ArrowDownCircle className="h-4 w-4" />;
    case AggregationMethod.Last:
      return <RefreshCw className="h-4 w-4" />;
    default:
      return <Calculator className="h-4 w-4" />;
  }
};

const getInputLabel = (method?: AggregationMethod, hasGoalBinding?: boolean): string => {
  if (!hasGoalBinding) return '本次完成';
  
  const labelMap: Record<AggregationMethod, string> = {
    [AggregationMethod.Sum]: '本次完成量（将累加到当前进度',
    [AggregationMethod.Max]: '本次达到的最高',
    [AggregationMethod.Average]: '本次的值（将计算平均值）',
    [AggregationMethod.Min]: '本次的最小',
    [AggregationMethod.Last]: '最新的值（将覆盖当前值）',
  };
  return method ? labelMap[method] || '本次完成' : '本次完成';
};

const getInputHint = (method?: AggregationMethod): string => {
  const hintMap: Record<AggregationMethod, string> = {
    [AggregationMethod.Sum]: '例如：跑了 5 公里，输入 5',
    [AggregationMethod.Max]: '例如：考试分数 85 分，输入 85',
    [AggregationMethod.Average]: '例如：每日学习 2 小时，输入 2',
    [AggregationMethod.Min]: '输入本次的最小值',
    [AggregationMethod.Last]: '输入最新值',
  };
  return method ? hintMap[method] || '请输入本次完成的数量' : '请输入本次完成的数量';
};

const calculatePercentage = (current: number, target: number): number => {
  if (target === 0) return 0;
  return Math.min(Math.round((current / target) * 100), 100);
};

const getProgressColor = (current: number, target: number): string => {
  const percentage = (current / target) * 100;
  if (percentage >= 100) return 'text-green-600';
  if (percentage >= 70) return 'text-blue-600';
  if (percentage >= 40) return 'text-yellow-600';
  return 'text-red-600';
};

// ===================== 组件 =====================

export function TaskCompleteDialog({
  open,
  onOpenChange,
  taskTitle,
  instanceDate,
  goalBinding,
  showQuickValues = true,
  isLoading = false,
  onConfirm,
  onCancel,
}: TaskCompleteDialogProps) {
  const [recordValue, setRecordValue] = useState<number | null>(null);
  const [note, setNote] = useState('');
  const [duration, setDuration] = useState<number | null>(null);

  // 快捷�?
  const quickValues = useMemo(() => {
    if (!goalBinding) return [];

    const { aggregationMethod, targetValue, currentValue } = goalBinding;

    switch (aggregationMethod) {
      case AggregationMethod.Sum:
        return [1, 5, 10, 20, 50];
      case AggregationMethod.Max: {
        const remaining = targetValue - currentValue;
        return [
          Math.floor(remaining * 0.5),
          Math.floor(remaining * 0.7),
          Math.floor(remaining * 0.9),
          remaining,
          targetValue,
        ].filter((v) => v > 0);
      }
      case AggregationMethod.Average:
        return [
          Math.floor(targetValue * 0.8),
          Math.floor(targetValue * 0.9),
          targetValue,
          Math.floor(targetValue * 1.1),
          Math.floor(targetValue * 1.2),
        ].filter((v) => v > 0);
      default:
        return [];
    }
  }, [goalBinding]);

  // 校验
  const isValid = useMemo(() => {
    if (goalBinding) {
      return recordValue !== null && recordValue > 0;
    }
    return true;
  }, [goalBinding, recordValue]);

  // 预测完成后的进度
  const predictProgress = useCallback(() => {
    if (!goalBinding || !recordValue) return '';

    const { aggregationMethod, currentValue, targetValue, unit } = goalBinding;
    let predictedValue = currentValue;

    switch (aggregationMethod) {
      case AggregationMethod.Sum:
        predictedValue = currentValue + recordValue;
        break;
      case AggregationMethod.Max:
        predictedValue = Math.max(currentValue, recordValue);
        break;
      case AggregationMethod.Last:
        predictedValue = recordValue;
        break;
      case AggregationMethod.Average:
        predictedValue = (currentValue + recordValue) / 2;
        break;
      default:
        predictedValue = currentValue + recordValue;
    }

    const percentage = calculatePercentage(predictedValue, targetValue);
    return `${predictedValue} / ${targetValue} ${unit || ''} (${percentage}%)`;
  }, [goalBinding, recordValue]);

  const handleConfirm = () => {
    if (!isValid || isLoading) return;

    const data: CompleteTaskData = {
      note: note || undefined,
      duration: duration || undefined,
    };

    if (goalBinding && recordValue !== null && recordValue > 0) {
      data.recordValue = recordValue;
    }

    onConfirm?.(data);
    onOpenChange(false);
  };

  const handleCancel = () => {
    onCancel?.();
    onOpenChange(false);
  };

  const formatDate = (date: number | Date): string => {
    const dateObj = typeof date === 'number' ? new Date(date) : date;
    return format(dateObj, 'yyyy-MM-dd EEEE', { locale: zhCN });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-full bg-green-100">
              <CheckCircle className="h-5 w-5 text-green-600" />
            </div>
            <DialogTitle>完成任务</DialogTitle>
          </div>
          <DialogDescription>
            确认完成任务并记录相关信�?
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* 任务信息 */}
          <div className="p-4 rounded-lg bg-secondary/50">
            <h3 className="font-medium text-lg mb-1">{taskTitle}</h3>
            <p className="text-sm text-muted-foreground flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatDate(instanceDate)}
            </p>
          </div>

          {/* 关联目标信息 */}
          {goalBinding && (
            <Alert className="border-blue-200 bg-blue-50">
              <AlertDescription>
                <div className="space-y-3">
                  <div className="flex items-center gap-2 text-sm">
                    <Target className="h-4 w-4 text-blue-600" />
                    <span className="font-medium">关联目标</span>
                    <span>{goalBinding.goalTitle}</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <Key className="h-4 w-4 text-blue-600" />
                    <span className="font-medium">关键结果</span>
                    <span>{goalBinding.keyResultTitle}</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <Calculator className="h-4 w-4 text-blue-600" />
                    <span className="font-medium">计算方式</span>
                    <Badge className={getAggregationMethodColor(goalBinding.aggregationMethod)}>
                      {getAggregationMethodText(goalBinding.aggregationMethod)}
                    </Badge>
                  </div>

                  {/* 当前进度 */}
                  <div className="pt-2 border-t border-blue-200 space-y-2">
                    <div className="flex justify-between items-center">
                      <span className="text-sm font-medium">当前进度</span>
                      <Badge className={getProgressColor(goalBinding.currentValue, goalBinding.targetValue)}>
                        {calculatePercentage(goalBinding.currentValue, goalBinding.targetValue)}%
                      </Badge>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">当前值：</span>
                      <span className="font-medium">
                        {goalBinding.currentValue} {goalBinding.unit || ''}
                      </span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">目标值：</span>
                      <span className="font-medium">
                        {goalBinding.targetValue} {goalBinding.unit || ''}
                      </span>
                    </div>
                    <Progress
                      value={calculatePercentage(goalBinding.currentValue, goalBinding.targetValue)}
                      className="h-2"
                    />
                  </div>
                </div>
              </AlertDescription>
            </Alert>
          )}

          {/* 输入完成�?*/}
          {goalBinding && (
            <div className="space-y-3">
              <div className="space-y-2">
                <Label className="flex items-center gap-2">
                  {getAggregationMethodIcon(goalBinding.aggregationMethod)}
                  {getInputLabel(goalBinding.aggregationMethod, true)}
                </Label>
                <div className="flex items-center gap-2">
                  <Input
                    type="number"
                    value={recordValue || ''}
                    onChange={(e) => setRecordValue(e.target.value ? Number(e.target.value) : null)}
                    placeholder={getInputHint(goalBinding.aggregationMethod)}
                    min={0}
                    step={0.01}
                    className="flex-1"
                    autoFocus
                  />
                  {goalBinding.unit && (
                    <span className="text-sm text-muted-foreground">{goalBinding.unit}</span>
                  )}
                </div>
              </div>

              {/* 预测结果 */}
              {recordValue !== null && recordValue > 0 && (
                <Alert className="border-green-200 bg-green-50">
                  <CheckCircle className="h-4 w-4 text-green-600" />
                  <AlertDescription>
                    <span className="font-medium">完成后预计：</span> {predictProgress()}
                  </AlertDescription>
                </Alert>
              )}

              {/* 快捷�?*/}
              {showQuickValues && quickValues.length > 0 && (
                <div className="space-y-2">
                  <span className="text-sm text-muted-foreground">快捷值：</span>
                  <div className="flex flex-wrap gap-2">
                    {quickValues.map((value) => (
                      <Badge
                        key={value}
                        variant={recordValue === value ? 'default' : 'outline'}
                        className="cursor-pointer hover:bg-primary/10"
                        onClick={() => setRecordValue(value)}
                      >
                        {value} {goalBinding.unit || ''}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* 无目标绑定提�?*/}
          {!goalBinding && (
            <Alert className="border-green-200 bg-green-50">
              <Info className="h-4 w-4 text-green-600" />
              <AlertDescription>
                此任务未关联目标，点击确认后将直接完成�?
              </AlertDescription>
            </Alert>
          )}

          {/* 完成备注 */}
          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <FileText className="h-4 w-4" />
              完成备注（可选）
            </Label>
            <Textarea
              value={note}
              onChange={(e) => setNote(e.target.value)}
              placeholder="记录本次完成的情况..."
              rows={3}
            />
          </div>

          {/* 实际耗时 */}
          <div className="space-y-2">
            <Label className="flex items-center gap-2">
              <Clock className="h-4 w-4" />
              实际耗时（可选）
            </Label>
            <div className="flex items-center gap-2">
              <Input
                type="number"
                value={duration || ''}
                onChange={(e) => setDuration(e.target.value ? Number(e.target.value) : null)}
                placeholder="记录实际花费的时"
                min={0}
                step={5}
                className="flex-1"
              />
              <span className="text-sm text-muted-foreground">分钟</span>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleCancel} disabled={isLoading}>
            取消
          </Button>
          <Button
            onClick={handleConfirm}
            disabled={!isValid || isLoading}
            className="bg-green-600 hover:bg-green-700"
          >
            <CheckCircle className="h-4 w-4 mr-2" />
            确认完成
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default TaskCompleteDialog;
