// apps/web/src/modules/reminder/presentation/components/dialogs/TemplateMoveDialog.vue
<template>
  <v-dialog v-model="visible" max-width="500px" persistent>
    <v-card>
      <v-card-title class="d-flex align-center bg-primary text-white">
        <v-icon class="mr-2">mdi-folder-move</v-icon>
        <span class="text-h5">移动模板</span>
      </v-card-title>

      <v-card-text class="pt-4">
        <!-- 当前模板信息 -->
        <v-alert
          v-if="template"
          type="info"
          variant="tonal"
          density="compact"
          class="mb-4"
        >
          <div class="text-subtitle-2">当前模板</div>
          <div class="text-body-2 mt-1">
            <v-icon size="small" class="mr-1">{{ template.icon || 'mdi-bell' }}</v-icon>
            {{ template.title }}
          </div>
          <div v-if="template.groupUuid" class="text-caption mt-1 text-grey-darken-1">
            <v-icon size="small" class="mr-1">mdi-folder</v-icon>
            当前分组: {{ getCurrentGroupName() }}
          </div>
        </v-alert>

        <!-- 目标分组选择 -->
        <v-select
          v-model="selectedGroupUuid"
          label="目标分组 *"
          :items="groupOptions"
          variant="outlined"
          prepend-inner-icon="mdi-folder"
          placeholder="选择要移动到的分组"
          :rules="groupRules"
          clearable
          required
        >
          <template #selection="{ item }">
            <v-icon :icon="item?.raw?.icon || 'mdi-folder'" class="mr-2" :color="item?.raw?.color" />
            {{ item?.title || '' }}
          </template>
          <template #item="{ props, item }">
            <v-list-item v-bind="props">
              <template #prepend>
                <v-icon :icon="item?.raw?.icon || 'mdi-folder'" :color="item?.raw?.color" />
              </template>
              <template #append v-if="item.value === template?.groupUuid">
                <v-chip size="small" color="primary" variant="tonal">
                  当前分组
                </v-chip>
              </template>
            </v-list-item>
          </template>
          <template #no-data>
            <v-list-item>
              <v-list-item-title class="text-grey">
                暂无可用分组
              </v-list-item-title>
            </v-list-item>
          </template>
        </v-select>

        <!-- 移出分组选项 -->
        <v-checkbox
          v-model="moveToRoot"
          label="移出所有分组（移动到根目录）"
          color="warning"
          hide-details
          class="mt-2"
          @update:model-value="handleMoveToRootChange"
        />

        <!-- 提示信息 -->
        <v-alert
          v-if="moveToRoot"
          type="warning"
          variant="tonal"
          density="compact"
          class="mt-4"
        >
          模板将从当前分组移出，成为独立模板
        </v-alert>

        <!-- 分组信息预览 -->
        <v-card
          v-if="selectedGroupUuid && !moveToRoot"
          variant="outlined"
          class="mt-4"
        >
          <v-card-text>
            <div class="text-subtitle-2 mb-2">目标分组信息</div>
            <v-list density="compact">
              <v-list-item>
                <template #prepend>
                  <v-icon size="small">mdi-information</v-icon>
                </template>
                <v-list-item-title class="text-body-2">
                  名称: {{ getGroupName(selectedGroupUuid) }}
                </v-list-item-title>
              </v-list-item>
              <v-list-item>
                <template #prepend>
                  <v-icon size="small">mdi-counter</v-icon>
                </template>
                <v-list-item-title class="text-body-2">
                  包含模板: {{ getGroupTemplateCount(selectedGroupUuid) }} 个
                </v-list-item-title>
              </v-list-item>
              <v-list-item>
                <template #prepend>
                  <v-icon size="small">mdi-check-circle</v-icon>
                </template>
                <v-list-item-title class="text-body-2">
                  状态: {{ getGroupStatus(selectedGroupUuid) }}
                </v-list-item-title>
              </v-list-item>
            </v-list>
          </v-card-text>
        </v-card>
      </v-card-text>

      <v-divider />

      <v-card-actions class="pa-4">
        <v-spacer />
        <v-btn
          color="grey-darken-1"
          variant="text"
          @click="close"
          :disabled="isMoving"
        >
          取消
        </v-btn>
        <v-btn
          color="primary"
          variant="elevated"
          @click="handleMove"
          :loading="isMoving"
          :disabled="!canMove"
        >
          移动
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import type { ReminderTemplateClientDTO, ReminderGroupClientDTO } from '@dailyuse/contracts/reminder';
// 导入根分组常量和工具函数（从主包导出，不是从命名空间）
import { ROOT_GROUP_CONFIG, isRootGroup, getRootGroupUuid, isOnDesktop } from '@dailyuse/contracts/reminder';
import { useReminder } from '../../composables/useReminder';
import { useSnackbar } from '@/shared/composables/useSnackbar';

type ReminderTemplate = ReminderTemplateClientDTO;
type ReminderTemplateGroup = ReminderGroupClientDTO;



// Props
interface Props {
  modelValue?: boolean;
  template?: ReminderTemplate | null;
}

const props = defineProps<Props>();

// Emits
const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  moved: [templateUuid: string, targetGroupUuid: string]; // 移除 null，始终使用根分组 UUID
  closed: [];
}>();

// Composables
const { reminderTemplates, reminderGroups, refreshAll } = useReminder();
const snackbar = useSnackbar();

// 响应式状态
const visible = ref(false);
const selectedGroupUuid = ref<string | null>(null);
const moveToRoot = ref(false);
const isMoving = ref(false);

// 分组选项 - 使用真实数据
const groupOptions = computed(() => {
  return reminderGroups.value.map(group => ({
    title: group.name,
    value: group.uuid,
    icon: group.icon || 'mdi-folder',
    color: group.enabled ? (group.color || 'primary') : 'grey',
    subtitle: group.description,
  }));
});

// 验证规则
const groupRules = [
  (v: string) => {
    if (moveToRoot.value) return true;
    return !!v || '请选择目标分组';
  },
];

// 是否可以移动
const canMove = computed(() => {
  if (!props.template) return false;
  if (moveToRoot.value) return true;
  if (!selectedGroupUuid.value) return false;
  // 不能移动到当前分组
  return selectedGroupUuid.value !== props.template.groupUuid;
});

// 获取当前分组名称
const getCurrentGroupName = (): string => {
  if (!props.template?.groupUuid) return '无';
  const group = reminderGroups.value.find(g => g.uuid === props.template!.groupUuid);
  return group?.name || '未知分组';
};

// 获取分组名称
const getGroupName = (groupUuid: string): string => {
  const group = reminderGroups.value.find(g => g.uuid === groupUuid);
  return group?.name || '未知';
};

// 获取分组状态
const getGroupStatus = (groupUuid: string): string => {
  const group = reminderGroups.value.find(g => g.uuid === groupUuid);
  return group?.enabled ? '已启用' : '已禁用';
};

// 获取分组模板数量
const getGroupTemplateCount = (groupUuid: string): number => {
  return reminderTemplates.value.filter(t => t.groupUuid === groupUuid).length;
};

// 处理移出分组选项变化
const handleMoveToRootChange = (value: boolean | null) => {
  if (value) {
    selectedGroupUuid.value = null;
  }
};

// 打开对话框
const open = () => {
  resetForm();
  visible.value = true;
};

// 关闭对话框
const close = () => {
  visible.value = false;
  emit('update:modelValue', false);
  emit('closed');
  setTimeout(resetForm, 300);
};

// 重置表单
const resetForm = () => {
  selectedGroupUuid.value = null;
  moveToRoot.value = false;
};

// 执行移动
const handleMove = async () => {
  if (!props.template || !canMove.value) return;

  isMoving.value = true;

  try {
    // 使用根分组 UUID 代替 null
    const targetGroupUuid = moveToRoot.value ? null : selectedGroupUuid.value;

    console.log('移动模板:', {
      templateUuid: props.template.uuid,
      fromGroup: props.template.groupUuid,
      toGroup: targetGroupUuid,
      isMovingToDesktop: moveToRoot.value,
    });

    // 调用应用服务移动模板
    const { reminderTemplateApplicationService } = await import('../../../application/services');
    await reminderTemplateApplicationService.moveTemplateToGroup(
      props.template.uuid,
      targetGroupUuid
    );

    // 触发刷新（应用服务已经更新了 store）
    emit('moved', props.template.uuid, targetGroupUuid || getRootGroupUuid());
    close();
  } catch (error) {
    console.error('移动模板失败:', error);
    // 错误提示已在应用服务中处理
  } finally {
    isMoving.value = false;
  }
};

// 监听 modelValue 变化
watch(() => props.modelValue, (newVal) => {
  visible.value = !!newVal;
});

// 监听 visible 变化
watch(visible, (newVal) => {
  emit('update:modelValue', newVal);
});

// 监听 selectedGroupUuid 变化
watch(selectedGroupUuid, (newVal) => {
  if (newVal) {
    moveToRoot.value = false;
  }
});

// 当父组件传入模板时，默认选择当前分组（便于快速移动）
watch(
  () => props.template,
  (newTemplate) => {
    if (!newTemplate) return;
    // 允许用户先选择当前分组作为默认目标
    selectedGroupUuid.value = newTemplate.groupUuid || null;
  },
  { immediate: true },
);

defineExpose({
  open,
  close,
});
</script>

<style scoped>
:deep(.v-select .v-input__details) {
  padding-inline-start: 12px;
}
</style>

// apps/desktop/src/renderer/modules/reminder/presentation/components/dialogs/TemplateMoveDialog.tsx
/**
 * TemplateMoveDialog - 移动模板到其他分组对话框
 *
 * 功能：
 * - 显示当前模板信息
 * - 选择目标分组
 * - 支持移出所有分组（移动到根目录）
 * - 显示目标分组预览信息
 *
 * @module reminder/presentation/components/dialogs
 */

import { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/shared/components/ui/dialog';
import { Button } from '@/shared/components/ui/button';
import { Label } from '@/shared/components/ui/label';
import { Checkbox } from '@/shared/components/ui/checkbox';
import { Alert, AlertDescription } from '@/shared/components/ui/alert';
import { Card, CardContent } from '@/shared/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/shared/components/ui/select';
import { Separator } from '@/shared/components/ui/separator';
import {
  FolderInput,
  Bell,
  Folder,
  Info,
  CheckCircle,
  AlertTriangle,
} from 'lucide-react';
import type { ReminderTemplateClientDTO, ReminderGroupClientDTO } from '@dailyuse/contracts/reminder';

// ============ Types ============

export interface TemplateMoveDialogProps {
  /** 是否打开 */
  open: boolean;
  /** 要移动的模板 */
  template: ReminderTemplateClientDTO | null;
  /** 可用的分组列表 */
  groups: ReminderGroupClientDTO[];
  /** 获取分组内模板数量 */
  getGroupTemplateCount?: (groupUuid: string) => number;
  /** 关闭回调 */
  onClose: () => void;
  /** 移动回调 */
  onMove: (templateUuid: string, targetGroupUuid: string | null) => Promise<void>;
}

// ============ Component ============

export function TemplateMoveDialog({
  open,
  template,
  groups,
  getGroupTemplateCount,
  onClose,
  onMove,
}: TemplateMoveDialogProps) {
  const [selectedGroupUuid, setSelectedGroupUuid] = useState<string>('');
  const [moveToRoot, setMoveToRoot] = useState(false);
  const [isMoving, setIsMoving] = useState(false);

  // 初始化状态
  useEffect(() => {
    if (open) {
      setSelectedGroupUuid('');
      setMoveToRoot(false);
    }
  }, [open]);

  // 当前分组名称
  const currentGroupName = useMemo(() => {
    if (!template?.groupUuid) return null;
    const group = groups.find(g => g.uuid === template.groupUuid);
    return group?.name || '未知分组';
  }, [template, groups]);

  // 分组选项（排除当前分组）
  const groupOptions = useMemo(() => {
    return groups
      .filter(g => g.uuid !== template?.groupUuid)
      .map(g => ({
        value: g.uuid,
        label: g.name,
        icon: g.icon,
        color: g.color,
        templateCount: getGroupTemplateCount?.(g.uuid) || 0,
        enabled: g.enabled,
      }));
  }, [groups, template, getGroupTemplateCount]);

  // 选中的分组信息
  const selectedGroup = useMemo(() => {
    if (!selectedGroupUuid) return null;
    return groups.find(g => g.uuid === selectedGroupUuid);
  }, [selectedGroupUuid, groups]);

  // 处理移出分组选项变化
  const handleMoveToRootChange = useCallback((checked: boolean) => {
    setMoveToRoot(checked);
    if (checked) {
      setSelectedGroupUuid('');
    }
  }, []);

  // 是否可以移动
  const canMove = useMemo(() => {
    if (moveToRoot) return true;
    if (!selectedGroupUuid) return false;
    if (selectedGroupUuid === template?.groupUuid) return false;
    return true;
  }, [moveToRoot, selectedGroupUuid, template]);

  // 处理移动
  const handleMove = useCallback(async () => {
    if (!template || !canMove) return;

    setIsMoving(true);
    try {
      const targetGroupUuid = moveToRoot ? null : selectedGroupUuid;
      await onMove(template.uuid, targetGroupUuid);
      onClose();
    } catch (error) {
      console.error('移动模板失败:', error);
    } finally {
      setIsMoving(false);
    }
  }, [template, canMove, moveToRoot, selectedGroupUuid, onMove, onClose]);

  if (!template) return null;

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        {/* 标题 */}
        <DialogHeader className="bg-primary text-primary-foreground -m-6 mb-4 p-6 rounded-t-lg">
          <DialogTitle className="flex items-center gap-2 text-primary-foreground">
            <FolderInput className="h-5 w-5" />
            移动模板
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* 当前模板信息 */}
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>
              <div className="text-sm font-medium">当前模板</div>
              <div className="flex items-center gap-2 mt-1">
                <Bell className="h-4 w-4" />
                <span>{template.title}</span>
              </div>
              {currentGroupName && (
                <div className="flex items-center gap-2 mt-1 text-muted-foreground">
                  <Folder className="h-4 w-4" />
                  <span>当前分组: {currentGroupName}</span>
                </div>
              )}
            </AlertDescription>
          </Alert>

          {/* 目标分组选择 */}
          <div className="space-y-2">
            <Label>目标分组 *</Label>
            <Select
              value={selectedGroupUuid}
              onValueChange={setSelectedGroupUuid}
              disabled={moveToRoot}
            >
              <SelectTrigger>
                <Folder className="h-4 w-4 mr-2" />
                <SelectValue placeholder="选择要移动到的分组" />
              </SelectTrigger>
              <SelectContent>
                {groupOptions.length === 0 ? (
                  <div className="py-2 px-3 text-sm text-muted-foreground">
                    暂无可用分组
                  </div>
                ) : (
                  groupOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      <div className="flex items-center gap-2">
                        <Folder
                          className="h-4 w-4"
                          style={{ color: option.color }}
                        />
                        <span>{option.label}</span>
                        {option.value === template.groupUuid && (
                          <span className="text-xs text-primary ml-2">(当前分组)</span>
                        )}
                      </div>
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
          </div>

          {/* 移出分组选项 */}
          <div className="flex items-center space-x-2">
            <Checkbox
              id="moveToRoot"
              checked={moveToRoot}
              onCheckedChange={handleMoveToRootChange}
            />
            <Label htmlFor="moveToRoot" className="text-sm cursor-pointer">
              移出所有分组（移动到根目录）
            </Label>
          </div>

          {/* 移到根目录提示 */}
          {moveToRoot && (
            <Alert variant="default" className="bg-orange-50 border-orange-200">
              <AlertTriangle className="h-4 w-4 text-orange-500" />
              <AlertDescription className="text-orange-700">
                模板将从当前分组移出，成为独立模板
              </AlertDescription>
            </Alert>
          )}

          {/* 目标分组预览 */}
          {selectedGroup && !moveToRoot && (
            <Card>
              <CardContent className="pt-4">
                <div className="text-sm font-medium mb-2">目标分组信息</div>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <Info className="h-4 w-4 text-muted-foreground" />
                    <span>名称: {selectedGroup.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Folder className="h-4 w-4 text-muted-foreground" />
                    <span>包含模板: {getGroupTemplateCount?.(selectedGroup.uuid) || 0} 个</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-4 w-4 text-muted-foreground" />
                    <span>状态: {selectedGroup.enabled ? '已启用' : '已禁用'}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        <Separator className="my-4" />

        {/* 操作按钮 */}
        <DialogFooter>
          <Button
            variant="ghost"
            onClick={onClose}
            disabled={isMoving}
          >
            取消
          </Button>
          <Button
            onClick={handleMove}
            disabled={!canMove || isMoving}
          >
            {isMoving ? '移动中...' : '移动'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default TemplateMoveDialog;
