// packages/app-vue/src/modules/reminder/components/TemplateMoveDialog.vue
<template>
  <Dialog :open="visible" @update:open="handleVisibleChange">
    <DialogContent class="max-w-md">
      <DialogHeader>
        <div class="flex items-center gap-2">
          <FolderInput class="h-5 w-5 text-primary" />
          <DialogTitle>{{ t('reminder.templateMove.title') }}</DialogTitle>
        </div>
      </DialogHeader>

      <div class="space-y-4">
        <!-- Current Template Info -->
        <Alert v-if="template">
          <Info class="h-4 w-4" />
          <AlertTitle>{{ t('reminder.templateMove.currentTemplate') }}</AlertTitle>
          <AlertDescription>
            <div class="flex items-center gap-2 mt-1">
              <Bell class="h-4 w-4" />
              <span class="font-medium">{{ template.name }}</span>
            </div>
            <div v-if="template.groupId" class="flex items-center gap-2 mt-1 text-xs">
              <Folder class="h-3 w-3" />
              <span>{{ t('reminder.templateMove.currentGroup') }} {{ getCurrentGroupName() }}</span>
            </div>
          </AlertDescription>
        </Alert>

        <!-- Target Group Selection -->
        <div class="space-y-2">
          <Label>{{ t('reminder.templateMove.targetGroup') }}</Label>
          <Select v-model="selectedGroupId" :disabled="moveToRoot">
            <SelectTrigger>
              <SelectValue :placeholder="t('reminder.templateMove.selectTargetGroup')" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem
                v-for="group in groupOptions"
                :key="group.id"
                :value="group.id"
                :disabled="group.id === template?.groupId"
              >
                <div class="flex items-center gap-2">
                  <component :is="getGroupIcon(group.icon)" class="h-4 w-4" />
                  <span>{{ group.name }}</span>
                  <Badge v-if="group.id === template?.groupId" variant="outline" class="ml-auto"
                    >> {{ t('reminder.templateMove.current') }}
                  </Badge>
                </div>
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <!-- Move to Root Option -->
        <div class="flex items-center space-x-2">
          <Checkbox
            id="move-to-root"
            v-model:checked="moveToRoot"
            @update:checked="handleMoveToRootChange"
          />
          <Label
            for="move-to-root"
            class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
          >
            {{ t('reminder.templateMove.removeFromAllGroups') }}
          </Label>
        </div>

        <!-- Warning Alert -->
        <Alert v-if="moveToRoot" variant="destructive">
          <AlertCircle class="h-4 w-4" />
          <AlertTitle>{{ t('reminder.templateMove.warning') }}</AlertTitle>
          <AlertDescription>
            {{ t('reminder.templateMove.warningDescription') }}
          </AlertDescription>
        </Alert>

        <!-- Target Group Info -->
        <Card v-if="selectedGroupId && !moveToRoot" class="p-4">
          <h4 class="text-sm font-semibold mb-2">
            {{ t('reminder.templateMove.targetGroupInfo') }}
          </h4>
          <div class="space-y-2 text-sm">
            <div class="flex items-center gap-2">
              <Info class="h-4 w-4 text-muted-foreground" />
              <span>{{ t('reminder.templateMove.name') }} {{ getGroupName(selectedGroupId) }}</span>
            </div>
            <div class="flex items-center gap-2">
              <Hash class="h-4 w-4 text-muted-foreground" />
              <span
                >{{ t('reminder.templateMove.templates') }}
                {{ getGroupTemplateCount(selectedGroupId) }}</span
              >
            </div>
            <div class="flex items-center gap-2">
              <CheckCircle2 class="h-4 w-4 text-muted-foreground" />
              <span
                >{{ t('reminder.templateMove.status') }} {{ getGroupStatus(selectedGroupId) }}</span
              >
            </div>
          </div>
        </Card>
      </div>

      <DialogFooter class="flex-row justify-end gap-2">
        <Button variant="ghost" @click="close" :disabled="isMoving">
          {{ t('reminder.templateMove.cancel') }}
        </Button>
        <Button variant="default" @click="handleMove" :disabled="!canMove || isMoving">
          <Loader2 v-if="isMoving" class="h-4 w-4 mr-2 animate-spin" />
          {{ t('reminder.templateMove.move') }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import {
  FolderInput,
  Info,
  Bell,
  Folder,
  AlertCircle,
  Hash,
  CheckCircle2,
  Loader2,
  FolderOpen,
} from 'lucide-vue-next';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@dailyuse/ui-vue-shadcn';
import { Button } from '@dailyuse/ui-vue-shadcn';
import { Label } from '@dailyuse/ui-vue-shadcn';
import { Badge } from '@dailyuse/ui-vue-shadcn';
import { Card } from '@dailyuse/ui-vue-shadcn';
import { Checkbox } from '@dailyuse/ui-vue-shadcn';
import { Alert, AlertDescription, AlertTitle } from '@dailyuse/ui-vue-shadcn';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@dailyuse/ui-vue-shadcn';

import type { ReminderMoveGroup, ReminderMoveTemplate } from '../types';

const { t } = useI18n();

const props = withDefaults(
  defineProps<{
    template?: ReminderMoveTemplate | null;
    groups?: ReminderMoveGroup[];
    templates?: ReminderMoveTemplate[];
  }>(),
  {
    template: null,
    groups: () => [],
    templates: () => [],
  },
);

const emit = defineEmits<{
  moved: [templateId: string, targetGroupId: string | null];
  closed: [];
}>();

const visible = ref(false);
const selectedGroupId = ref<string | undefined>(undefined);
const moveToRoot = ref(false);
const isMoving = ref(false);

const groupOptions = computed(() => {
  return props.groups.map((group) => ({
    id: group.id,
    name: group.name,
    icon: group.icon || 'mdi-folder',
    enabled: group.enabled,
  }));
});

const canMove = computed(() => {
  if (!props.template) return false;
  if (moveToRoot.value) return true;
  if (!selectedGroupId.value) return false;
  return selectedGroupId.value !== props.template.groupId;
});

const getCurrentGroupName = (): string => {
  if (!props.template?.groupId) return t('reminder.templateMove.none');
  const group = props.groups.find((g) => g.id === props.template!.groupId);
  return group?.name || t('reminder.templateMove.unknownGroup');
};

const getGroupName = (groupId: string): string => {
  const group = props.groups.find((g) => g.id === groupId);
  return group?.name || t('reminder.templateMove.unknown');
};

const getGroupStatus = (groupId: string): string => {
  const group = props.groups.find((g) => g.id === groupId);
  return group?.enabled ? t('reminder.templateMove.enabled') : t('reminder.templateMove.disabled');
};

const getGroupTemplateCount = (groupId: string): number => {
  return props.templates.filter((t) => t.groupId === groupId).length;
};

const getGroupIcon = (icon?: string) => {
  return icon === 'mdi-folder-open' ? FolderOpen : Folder;
};

const handleMoveToRootChange = (value: boolean) => {
  if (value) {
    selectedGroupId.value = undefined;
  }
};

const open = () => {
  resetForm();
  visible.value = true;
};

const close = () => {
  visible.value = false;
  emit('closed');
  setTimeout(resetForm, 300);
};

const handleVisibleChange = (value: boolean) => {
  visible.value = value;
  if (!value) {
    emit('closed');
    setTimeout(resetForm, 300);
  }
};

const resetForm = () => {
  selectedGroupId.value = props.template?.groupId || undefined;
  moveToRoot.value = false;
};

const handleMove = async () => {
  if (!props.template || !canMove.value) return;

  isMoving.value = true;
  try {
    const targetGroupId = moveToRoot.value ? null : (selectedGroupId.value ?? null);
    emit('moved', props.template.id, targetGroupId);
    close();
  } finally {
    isMoving.value = false;
  }
};

watch(
  () => props.template,
  (newTemplate) => {
    if (newTemplate) {
      selectedGroupId.value = newTemplate.groupId || undefined;
    }
  },
  { immediate: true },
);

watch(selectedGroupId, (newVal) => {
  if (newVal) {
    moveToRoot.value = false;
  }
});

defineExpose({
  open,
  close,
});
</script>

// apps/desktop/src/renderer/modules/reminder/presentation/components/dialogs/TemplateMoveDialog.tsx
/**
 * TemplateMoveDialog - 移动模板到其他分组对话框
 *
 * 功能�?
 * - 显示当前模板信息
 * - 选择目标分组
 * - 支持移出所有分组（移动到根目录�?
 * - 显示目标分组预览信息
 *
 * @module reminder/presentation/components/dialogs
 */

import { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  Button,
  Label,
  Checkbox,
  Alert,
  AlertDescription,
  Card,
  CardContent,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Separator,
} from '@dailyuse/ui-react-shadcn';

import {
  FolderInput,
  Bell,
  Folder,
  Info,
  CheckCircle,
  AlertTriangle,
} from 'lucide-react';
import type { ReminderTemplateClientDTO, ReminderGroupClientDTO } from '@dailyuse/contracts/reminder';

// ============ Types ============

export interface TemplateMoveDialogProps {
  /** 是否打开 */
  open: boolean;
  /** 要移动的模板 */
  template: ReminderTemplateClientDTO | null;
  /** 可用的分组列�?*/
  groups: ReminderGroupClientDTO[];
  /** 获取分组内模板数�?*/
  getGroupTemplateCount?: (groupId: string) => number;
  /** 关闭回调 */
  onClose: () => void;
  /** 移动回调 */
  onMove: (templateId: string, targetGroupId: string | null) => Promise<void>;
}

// ============ Component ============

export function TemplateMoveDialog({
  open,
  template,
  groups,
  getGroupTemplateCount,
  onClose,
  onMove,
}: TemplateMoveDialogProps) {
  const [selectedGroupId, setSelectedGroupId] = useState<string>('');
  const [moveToRoot, setMoveToRoot] = useState(false);
  const [isMoving, setIsMoving] = useState(false);

  // 初始化状�?
  useEffect(() => {
    if (open) {
      setSelectedGroupId('');
      setMoveToRoot(false);
    }
  }, [open]);

  // 当前分组名称
  const currentGroupName = useMemo(() => {
    if (!template?.groupId) return null;
    const group = groups.find(g => g.id === template.groupId);
    return group?.name || '未知分组';
  }, [template, groups]);

  // 分组选项（排除当前分组）
  const groupOptions = useMemo(() => {
    return groups
      .filter(g => g.id !== template?.groupId)
      .map(g => ({
        value: g.id,
        label: g.name,
        icon: g.icon,
        color: g.color,
        templateCount: getGroupTemplateCount?.(g.id) || 0,
        enabled: g.enabled,
      }));
  }, [groups, template, getGroupTemplateCount]);

  // 选中的分组信�?
  const selectedGroup = useMemo(() => {
    if (!selectedGroupId) return null;
    return groups.find(g => g.id === selectedGroupId);
  }, [selectedGroupId, groups]);

  // 处理移出分组选项变化
  const handleMoveToRootChange = useCallback((checked: boolean) => {
    setMoveToRoot(checked);
    if (checked) {
      setSelectedGroupId('');
    }
  }, []);

  // 是否可以移动
  const canMove = useMemo(() => {
    if (moveToRoot) return true;
    if (!selectedGroupId) return false;
    if (selectedGroupId === template?.groupId) return false;
    return true;
  }, [moveToRoot, selectedGroupId, template]);

  // 处理移动
  const handleMove = useCallback(async () => {
    if (!template || !canMove) return;

    setIsMoving(true);
    try {
      const targetGroupId = moveToRoot ? null : selectedGroupId;
      await onMove(template.id, targetGroupId);
      onClose();
    } catch (error) {
      console.error('移动模板失败:', error);
    } finally {
      setIsMoving(false);
    }
  }, [template, canMove, moveToRoot, selectedGroupId, onMove, onClose]);

  if (!template) return null;

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        {/* 标题 */}
        <DialogHeader className="bg-primary text-primary-foreground -m-6 mb-4 p-6 rounded-t-lg">
          <DialogTitle className="flex items-center gap-2 text-primary-foreground">
            <FolderInput className="h-5 w-5" />
            移动模板
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* 当前模板信息 */}
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>
              <div className="text-sm font-medium">当前模板</div>
              <div className="flex items-center gap-2 mt-1">
                <Bell className="h-4 w-4" />
                <span>{template.title}</span>
              </div>
              {currentGroupName && (
                <div className="flex items-center gap-2 mt-1 text-muted-foreground">
                  <Folder className="h-4 w-4" />
                  <span>当前分组: {currentGroupName}</span>
                </div>
              )}
            </AlertDescription>
          </Alert>

          {/* 目标分组选择 */}
          <div className="space-y-2">
            <Label>目标分组 *</Label>
            <Select
              value={selectedGroupId}
              onValueChange={setSelectedGroupId}
              disabled={moveToRoot}
            >
              <SelectTrigger>
                <Folder className="h-4 w-4 mr-2" />
                <SelectValue placeholder="选择要移动到的分" />
              </SelectTrigger>
              <SelectContent>
                {groupOptions.length === 0 ? (
                  <div className="py-2 px-3 text-sm text-muted-foreground">
                    暂无可用分组
                  </div>
                ) : (
                  groupOptions.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      <div className="flex items-center gap-2">
                        <Folder
                          className="h-4 w-4"
                          style={{ color: option.color ?? undefined }}
                        />
                        <span>{option.label}</span>
                        {option.value === template.groupId && (
                          <span className="text-xs text-primary ml-2">(当前分组)</span>
                        )}
                      </div>
                    </SelectItem>
                  ))
                )}
              </SelectContent>
            </Select>
          </div>

          {/* 移出分组选项 */}
          <div className="flex items-center space-x-2">
            <Checkbox
              id="moveToRoot"
              checked={moveToRoot}
              onCheckedChange={handleMoveToRootChange}
            />
            <Label htmlFor="moveToRoot" className="text-sm cursor-pointer">
              移出所有分组（移动到根目录�?
            </Label>
          </div>

          {/* 移到根目录提�?*/}
          {moveToRoot && (
            <Alert variant="default" className="bg-orange-50 border-orange-200">
              <AlertTriangle className="h-4 w-4 text-orange-500" />
              <AlertDescription className="text-orange-700">
                模板将从当前分组移出，成为独立模�?
              </AlertDescription>
            </Alert>
          )}

          {/* 目标分组预览 */}
          {selectedGroup && !moveToRoot && (
            <Card>
              <CardContent className="pt-4">
                <div className="text-sm font-medium mb-2">目标分组信息</div>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <Info className="h-4 w-4 text-muted-foreground" />
                    <span>名称: {selectedGroup.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Folder className="h-4 w-4 text-muted-foreground" />
                    <span>包含模板: {getGroupTemplateCount?.(selectedGroup.id) || 0} 个</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-4 w-4 text-muted-foreground" />
                    <span>状态: {selectedGroup.enabled ? '已启用' : '已禁用'}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        <Separator className="my-4" />

        {/* 操作按钮 */}
        <DialogFooter>
          <Button
            variant="ghost"
            onClick={onClose}
            disabled={isMoving}
          >
            取消
          </Button>
          <Button
            onClick={handleMove}
            disabled={!canMove || isMoving}
          >
            {isMoving ? '移动中...' : '移动'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default TemplateMoveDialog;
